import crypto from 'node:crypto';
import {NextRequest,NextResponse} from 'next/server';
import {requireUser,unauthorized,UnauthorizedError} from '@/lib/auth';
import {logOp} from '@/lib/logs';
import {prisma} from '@/lib/prisma';
import {putObject} from '@/lib/s3';
import {fileType,safeFilename,validateFile} from '@/lib/validation';
export const runtime='nodejs'; export const dynamic='force-dynamic';
function ymd(d:Date){return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
export async function POST(req:NextRequest){try{const user=await requireUser(); const form=await req.formData(); const workOrderId=String(form.get('workOrderId')||''), categoryId=String(form.get('categoryId')||''), version=String(form.get('version')||'V1.0').slice(0,30); const up=form.get('file'); if(!workOrderId||!categoryId)return NextResponse.json({message:'缺少工单或分类参数'},{status:400}); if(!(up instanceof File))return NextResponse.json({message:'请选择文件'},{status:400}); const err=validateFile(up.name,up.type,up.size); if(err)return NextResponse.json({message:err},{status:400}); const [wo,cat]=await Promise.all([prisma.workOrder.findFirst({where:{id:workOrderId,deletedAt:null}}),prisma.resourceCategory.findUnique({where:{id:categoryId}})]); if(!wo||!cat)return NextResponse.json({message:'工单或分类不存在'},{status:404}); const ft=fileType(up.name,up.type); const key=`work-orders/${wo.code}/${cat.code}/${ymd(new Date())}/${crypto.randomUUID()}-${safeFilename(up.name)}`; await putObject({key,body:Buffer.from(await up.arrayBuffer()),contentType:up.type||'application/octet-stream',originalName:up.name}); const f=await prisma.resourceFile.create({data:{workOrderId:wo.id,categoryId:cat.id,originalName:up.name,mimeType:up.type||'application/octet-stream',fileType:ft,fileSize:up.size,objectKey:key,version:version||'V1.0',uploadedById:user.id}}); await logOp({userId:user.id,action:'upload',targetType:'resource_file',targetId:f.id,detail:{workOrderCode:wo.code,categoryCode:cat.code,objectKey:key}}); return NextResponse.json({file:{...f,createdAt:f.createdAt.toISOString(),updatedAt:f.updatedAt.toISOString(),viewUrl:`/api/resource-files/${f.id}/view`,downloadUrl:`/api/resource-files/${f.id}/download`}})}catch(e){if(e instanceof UnauthorizedError)return unauthorized(); console.error(e); return NextResponse.json({message:'上传失败，请检查对象存储配置'},{status:500})}}
