'use client';
import { useEffect, useRef, useState } from 'react';
import { useModalLayer } from '@/components/useModalLayer';
type Mark={x:number;y:number;ex:number;ey:number;type:'box'|'arrow'};
export default function QuickPhotoAnnotator({file,onDone,onClose}:{file:File;onDone:(file:File)=>void;onClose:()=>void}) {
  const canvas=useRef<HTMLCanvasElement>(null),layer=useRef<HTMLDivElement>(null),picture=useRef<HTMLImageElement|null>(null);
  const [marks,setMarks]=useState<Mark[]>([]),[draft,setDraft]=useState<Mark|null>(null),[mode,setMode]=useState<'box'|'arrow'>('box'),[ready,setReady]=useState(false);
  useModalLayer({open:true,layerRef:layer,onClose});
  useEffect(()=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{picture.current=img;setReady(true);};img.src=url;return()=>URL.revokeObjectURL(url);},[file]);
  useEffect(()=>{const c=canvas.current,img=picture.current;if(!c||!img||!ready)return;c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);ctx.strokeStyle='#ff3b19';ctx.lineWidth=Math.max(4,c.width/220);for(const m of [...marks,...(draft?[draft]:[])]){ctx.beginPath();if(m.type==='box')ctx.rect(m.x,m.y,m.ex-m.x,m.ey-m.y);else{ctx.moveTo(m.x,m.y);ctx.lineTo(m.ex,m.ey);const a=Math.atan2(m.ey-m.y,m.ex-m.x),s=Math.max(18,c.width/35);ctx.moveTo(m.ex-s*Math.cos(a-.5),m.ey-s*Math.sin(a-.5));ctx.lineTo(m.ex,m.ey);ctx.lineTo(m.ex-s*Math.cos(a+.5),m.ey-s*Math.sin(a+.5));}ctx.stroke();}},[marks,draft,ready]);
  function pos(e:React.PointerEvent<HTMLCanvasElement>){const c=e.currentTarget,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}
  return <div ref={layer} className="qq-modal" tabIndex={-1}><section className="qq-annotator" role="dialog" aria-modal="true" aria-label="标注现场图片"><header><b>圈出需要注意的位置</b><button onClick={onClose}>取消</button></header><div className="qq-tools"><button aria-pressed={mode==='box'} onClick={()=>setMode('box')}>圈框</button><button aria-pressed={mode==='arrow'} onClick={()=>setMode('arrow')}>箭头</button><button disabled={!marks.length} onClick={()=>setMarks(m=>m.slice(0,-1))}>撤销</button></div><div className="qq-canvas"><canvas ref={canvas} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const p=pos(e);setDraft({...p,ex:p.x,ey:p.y,type:mode});}} onPointerMove={e=>{if(draft){const p=pos(e);setDraft({...draft,ex:p.x,ey:p.y});}}} onPointerUp={()=>{if(draft)setMarks(m=>[...m,draft]);setDraft(null);}} onPointerCancel={()=>setDraft(null)}/></div><footer><small>原照片保留，另存标注图片。</small><button className="qq-primary" disabled={!ready||!marks.length} onClick={()=>canvas.current?.toBlob(blob=>{if(blob)onDone(new File([blob],'标注-'+file.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'}));},'image/jpeg',.94)}>使用标注图</button></footer></section></div>;
}
