'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, MoreHorizontal, Plus, RefreshCw, Search, ShieldAlert, Zap } from 'lucide-react';
import Link from 'next/link';
import { AppWorkbenchHeader } from '@/components/layout/AppWorkbenchHeader';
import { WorkbenchCockpitCommand } from '@/components/layout/WorkbenchCockpitCommand';
import { QualityModuleTabs } from '@/components/QualityModuleTabs';
import { useModalLayer } from '@/components/useModalLayer';
import type { CurrentUserDTO } from '@/types';
import { quickStateText,quickActionText,type QuickQualityDTO } from '@/lib/quality-quick-shared';
import QuickQualityForm from './QuickQualityForm';
import { QuickPhotoViewer } from './QuickWarnings';
import './quick-quality.css';
type Command={action:string;record:QuickQualityDTO};
function ActionDialog({value,busy,onCancel,onSubmit}:{value:Command;busy:boolean;onCancel:()=>void;onSubmit:(reason:string)=>void}) {
  const [reason,setReason]=useState(value.action==='DELETE'?'重复录入':'已不适用'),[note,setNote]=useState(''),ref=useRef<HTMLDivElement>(null);
  useModalLayer({open:true,layerRef:ref,onClose:()=>{if(!busy)onCancel();}});
  const deleting=value.action==='DELETE';
  return <div className="qq-modal" ref={ref} tabIndex={-1}><section className="qq-confirm" role="dialog" aria-modal="true" aria-label={quickActionText[value.action]}><h2>{quickActionText[value.action]}</h2><p>{value.action==='RESTORE'?'恢复后保持不警示状态，需要时再主动发布。':value.action==='ESCALATE'?'带入工单、说明和照片，新建重大异常草稿。现有警示在新异常正式发布后交接。':deleting?'该记录将同步下线并移入回收站，管理员可以恢复。':'停止现场提醒，保留问题和图片记录。'}</p>{['DELETE','OFFLINE'].includes(value.action)&&<><label>原因<select value={reason} onChange={e=>setReason(e.target.value)}>{['已不适用','重复录入','关联错误','问题已消除','其他'].map(s=><option key={s}>{s}</option>)}</select></label><input aria-label="补充说明" placeholder="补充说明（可不填）" value={note} onChange={e=>setNote(e.target.value)} maxLength={300}/></>}<footer><button disabled={busy} onClick={onCancel}>取消</button><button disabled={busy} className={deleting?'qq-danger':'qq-primary'} onClick={()=>onSubmit([reason,note].filter(Boolean).join('：'))}>{busy?'处理中…':'确认'+(deleting?'删除':value.action==='OFFLINE'?'下线':value.action==='RESTORE'?'恢复':'转入')}</button></footer></section></div>;
}
export default function QuickQualityWorkbench({user,mobile=false,workOrderId,code,openNew=false}:{user:CurrentUserDTO;mobile?:boolean;workOrderId?:string;code?:string;openNew?:boolean}) {
  const manage=user.laborRole==='ADMIN'||user.access.capabilities.includes('QUALITY:UPDATE'),admin=user.laborRole==='ADMIN';
  const [rows,setRows]=useState<QuickQualityDTO[]>([]),[record,setRecord]=useState<QuickQualityDTO|null>(null),[q,setQ]=useState(''),[state,setState]=useState(''),[trash,setTrash]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const [page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
  const [form,setForm]=useState<{record?:QuickQualityDTO}|null>(openNew&&manage?{}:null),[command,setCommand]=useState<Command|null>(null),[busy,setBusy]=useState(false),[photos,setPhotos]=useState<{photos:QuickQualityDTO['photos'];index:number}|null>(null),[reload,setReload]=useState(0);
  const selected=useRef<string|null>(null);
  const choose=useCallback(async(id:string)=>{selected.current=id;try{const r=await fetch('/api/quality-quick/'+id,{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);if(selected.current===id)setRecord(b.record);}catch(e){setError(e instanceof Error?e.message:'详情加载失败');}},[]);
  useEffect(()=>{const a=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{const p=new URLSearchParams({q,state,trash:trash?'1':'0',from,to,page:String(page)}),r=await fetch('/api/quality-quick?'+p,{signal:a.signal,cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setRows(b.rows);setTotal(b.total);setPages(b.pages);setError('');if(page>b.pages)setPage(b.pages);if(selected.current&&!b.rows.some((v:QuickQualityDTO)=>v.id===selected.current)){selected.current=null;setRecord(null);}else if(selected.current){void choose(selected.current);}}catch(e){if(!a.signal.aborted)setError(e instanceof Error?e.message:'列表加载失败');}finally{if(!a.signal.aborted)setLoading(false);}},180);return()=>{clearTimeout(timer);a.abort();};},[q,state,trash,from,to,page,reload,choose]);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('id');if(id)void choose(id);},[choose]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(timer);},[toast]);
  function filter(action:()=>void){action();setPage(1);setRecord(null);selected.current=null;}
  async function run(reason:string){if(!command||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/quality-quick/'+command.record.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:command.action,reason,version:command.record.version,mutationKey:crypto.randomUUID()})}),b=await r.json();if(!r.ok)throw new Error(b.error);setToast(quickActionText[command.action]+'完成');setCommand(null);setRecord(null);selected.current=null;setReload(x=>x+1);window.dispatchEvent(new Event('quality-quick-changed'));}catch(e){setCommand(null);setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
  function saved(r:QuickQualityDTO){setForm(null);setToast(r.state==='ACTIVE'?'警示已发布':'记录已保存');setPage(1);setQ('');setState('');setTrash(false);setFrom('');setTo('');setReload(x=>x+1);void choose(r.id);}
  const title=trash?'快处回收站':'异常快处';
  return <main className={'qq-workbench '+(mobile?'qq-mobile':'hm-workbench-root hm-cockpit-root')}>
    {!mobile&&<AppWorkbenchHeader user={user} activeHref="/workspace/quality" subtitle="现场异常快速记录" menuItems={[]} hideHeader sidebarTriggerTargetId="qq-navigation"/>}
    <div className="qq-frame">{mobile?<header className="qq-mobile-header"><span className="qq-mark"><Zap/></span><div><small>品质现场记录</small><h1>{title}</h1></div>{manage&&<button className="qq-primary" onClick={()=>setForm({})}><Plus size={18}/>记录</button>}</header>:<><WorkbenchCockpitCommand navigationTargetId="qq-navigation" icon={<Zap size={21}/>} title={title} subtitle="记录问题 · 按需警示" actions={<><button onClick={()=>setReload(x=>x+1)} aria-label="刷新快处记录"><RefreshCw size={17} className={loading?'spin':''}/></button>{manage&&<button className="qq-primary" onClick={()=>setForm({})}><Plus size={17}/>快速记录</button>}</>}/><QualityModuleTabs active="quick" canViewData={user.access.capabilities.includes('QUALITY_DATA:READ')}/></>}
      <div className="qq-toolbar"><div className="qq-search"><Search size={18}/><input aria-label="搜索快处记录" value={q} placeholder="搜索工单、问题、记录人" onChange={e=>filter(()=>setQ(e.target.value))}/></div><details><summary><MoreHorizontal size={20}/>筛选 / 更多</summary><div className="qq-filter-more"><label>从<input type="date" value={from} onChange={e=>filter(()=>setFrom(e.target.value))}/></label><label>至<input type="date" value={to} onChange={e=>filter(()=>setTo(e.target.value))}/></label><button onClick={()=>filter(()=>{setFrom('');setTo('');setQ('');setState('');})}>清除筛选</button><button onClick={()=>filter(()=>setTrash(!trash))}>{trash?'返回记录':'回收站'}</button></div></details></div>
      <nav className="qq-state-tabs" aria-label="快处状态">{[['','全部'],['ACTIVE','警示中'],['SAVED','仅记录'],['OFFLINE','已下线']].map(([s,label])=><button key={s} aria-pressed={state===s} onClick={()=>filter(()=>setState(s))}>{label}</button>)}<span>{total} 条</span></nav>
      {error&&<div className="qq-error" role="alert">{error}<button onClick={()=>setReload(x=>x+1)}>刷新</button></div>}
      <div className="qq-columns"><section className="qq-record-list" aria-label="快处记录列表">{loading&&<small className="qq-loading">正在加载…</small>}{rows.map(r=><button className={'qq-record '+(record?.id===r.id?'selected':'')} key={r.id} onClick={()=>void choose(r.id)}>{r.photos[0]?<img src={r.photos[0].url} alt="现场图片"/>:<span className="qq-record-icon"><ShieldAlert/></span>}<div><header><b>{r.description.split('\n')[0]}</b><em className={'qq-state '+r.state}>{r.deletedAt?'已删除':r.scopeChanged?'待确认范围':r.effectiveUntil&&new Date(r.effectiveUntil)<new Date()?'已到期':quickStateText[r.state]}</em></header><p>{r.orders.map(o=>o.code).join('、')}</p><small>{r.author} · {new Date(r.occurredAt).toLocaleDateString('zh-CN')}{r.photos.length?' · '+r.photos.length+' 张图片':''}</small></div></button>)}{!rows.length&&!loading&&<div className="qq-empty"><Zap size={35}/><b>{trash?'回收站暂无记录':'当前没有匹配记录'}</b><p>{trash?'删除的记录会在这里保留。':'现场处理好的问题，可以随手留一条记录。'}</p>{manage&&!trash&&<button className="qq-primary" onClick={()=>setForm({})}>快速记录</button>}</div>}<footer className="qq-pagination"><button aria-label="上一页" disabled={page<=1||loading} onClick={()=>setPage(page-1)}><ChevronLeft/></button><span>{page} / {pages}</span><button aria-label="下一页" disabled={page>=pages||loading} onClick={()=>setPage(page+1)}><ChevronRight/></button></footer></section>
        <section className={'qq-detail '+(record?'open':'')} aria-label="快处详情">{record?<><header><button className="qq-back" onClick={()=>{selected.current=null;setRecord(null);}}><ChevronLeft size={18}/>返回列表</button><small>{record.number} · {record.deletedAt?'已删除':quickStateText[record.state]}</small><h2>{record.description.split('\n')[0]}</h2><p>{record.orders.map(o=>o.code+' · '+o.productName).join(' / ')}</p></header><div className="qq-detail-body"><div className="qq-detail-meta"><span>{record.scope==='PRODUCT'?'产品持续警示':'仅所选工单'}</span><span>{record.author}</span><span>{new Date(record.occurredAt).toLocaleDateString('zh-CN')}{record.processName?' · '+record.processName:''}</span></div>{record.scopeChanged&&<p className="qq-error">产品资料已变化，现场警示已停止展示。请编辑并重新确认适用范围。</p>}<p className="qq-description">{record.description}</p><div className="qq-detail-photos">{record.photos.map((p,i)=><button key={p.id} onClick={()=>setPhotos({photos:record.photos,index:i})}><img src={p.url} alt={p.name}/><span>{p.name}</span></button>)}</div>
        {record.escalatedReportId&&<p><Link href={'/workspace/quality/internal-risks?reportId='+record.escalatedReportId}>已转为重大异常，查看协同记录 →</Link></p>}<details className="qq-history"><summary>处理轨迹 · {record.activities?.length||0} 次操作</summary>{record.activities?.map(a=><div key={a.id}><b>{quickActionText[a.action]||a.action}</b><span>{a.actor} · {new Date(a.createdAt).toLocaleString('zh-CN')}</span>{a.reason&&<p>{a.reason}</p>}<details><summary>查看当时内容</summary><p>{String((a.snapshot as {description?:string})?.description||'')}</p><div className="qq-photo-strip">{((a.snapshot as {photos?:QuickQualityDTO['photos']})?.photos||[]).map((p,i,list)=><button key={p.id} onClick={()=>setPhotos({photos:list,index:i})}><img src={p.url} alt={p.name}/></button>)}</div></details></div>)}</details></div>
        {manage&&<footer className="qq-detail-actions">{record.deletedAt?admin&&<button className="qq-primary" onClick={()=>setCommand({action:'RESTORE',record})}>恢复记录</button>:<>{!record.escalatedReportId&&<button className="qq-primary" onClick={()=>setForm({record})}>{record.state==='ACTIVE'?'编辑警示':record.state==='OFFLINE'?'编辑 / 重新上线':'编辑 / 发布警示'}</button>}{record.state==='ACTIVE'&&<button onClick={()=>setCommand({action:'OFFLINE',record})}>下线警示</button>}<details><summary><MoreHorizontal size={19}/>更多</summary><div>{!record.escalatedReportId&&<button onClick={()=>setCommand({action:'ESCALATE',record})}>转为重大异常</button>}<button className="qq-danger-text" onClick={()=>setCommand({action:'DELETE',record})}>删除记录</button></div></details></>}</footer>}</>:<div className="qq-empty"><ShieldAlert size={40}/><b>选择一条快处记录</b><p>查看现场图片与处理说明</p></div>}</section>
      </div>
    </div>{toast&&<div className="qq-toast" role="status">{toast}</div>}{form&&<QuickQualityForm record={form.record} workOrderId={workOrderId} code={code} onClose={()=>setForm(null)} onSaved={saved}/>}
    {command&&<ActionDialog value={command} busy={busy} onCancel={()=>setCommand(null)} onSubmit={reason=>void run(reason)}/>}
    {photos&&<QuickPhotoViewer {...photos} onClose={()=>setPhotos(null)}/>}
  </main>;
}
