ALTER TABLE "QfPackage" DROP CONSTRAINT "QfPackage_status";
ALTER TABLE "QfPackage" ADD CONSTRAINT "QfPackage_status"
  CHECK ("status" IN ('DRAFT','REVIEWING','SUPERVISOR','QUALITY','APPROVED','RETURNED','REVOKED','SUPERSEDED','STALE'));
