import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { prisma } from '../lib/prisma';
import { mutateWarehouseException, mutateMaterialFollowUp, classifyMaterialFollowUps } from '../lib/material-exception-service';
import { serializeWarehouseMaterialTask } from '../lib/warehouse-material';
import { loadFinishedGoods, mutateFinishedGoods } from '../lib/finished-goods-service';
const skip = process.env.RUN_DB_INTEGRATION !== '1';

test('purchased and customer shortages remain independent through partial arrivals, conflicts and individual closure', {skip}, async()=>{
  const key='source-it-'+randomUUID().slice(0,8);
  const actor=await prisma.user.create({data:{username:key,passwordHash:'test-only',displayName:key,laborRole:'ADMIN'}});
  const owner=await prisma.user.create({data:{username:key+'-owner',passwordHash:'test-only',displayName:'原负责人'}});
  const work=await prisma.workOrder.create({data:{code:key,productName:'混合缺料',specification:key,customerName:'测试',planType:'managed_plan',planActive:true,stage:'not_issued'}});
  const task=await prisma.warehouseMaterialTask.create({data:{workOrderId:work.id}});
  const read=()=>prisma.warehouseMaterialTask.findUniqueOrThrow({where:{id:task.id}});
  const warehouse=async(action:string,body:Record<string,unknown>={},canConfirm=true)=>mutateWarehouseException(task.id,{version:(await read()).version,action,...body},actor.id,canConfirm);
  try {
    const first=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'端子缺 10 个',materialModel:'端子-A',supplySource:'PURCHASED',shortageQuantity:10,ownerId:owner.id},false);
    const a=first.exceptionCases.find(e=>e.status==='OPEN')!;
    const second=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'客供壳体缺 4 个',materialModel:'壳体-B',supplySource:'CUSTOMER',shortageQuantity:4},false);
    const b=second.exceptionCases.find(e=>e.id!==a.id)!;
    assert.equal(serializeWarehouseMaterialTask(second).activeExceptions?.length,2);
    await assert.rejects(warehouse('resolve',{note:'不能模糊关闭',resolution:'completed'}),/选择具体/);
    await assert.rejects(warehouse('resolve',{exceptionId:a.id,note:'协同不能代仓库确认',resolution:'completed'},false),/仓库/);
    const readFollow=()=>prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:a.id}});
    const follow=await readFollow();
    const future=new Date(Date.now()+5*86400000).toISOString().slice(0,10);
    const update=async(body:Record<string,unknown>)=>{const f=await readFollow();return mutateMaterialFollowUp(f.id,{action:'update',version:f.version,ownerId:owner.id,status:'WAITING_ARRIVAL',expectedAt:future,note:'分批补料',...body},actor.id);};
    await update({receivedQuantity:3});
    assert.equal((await prisma.warehouseMaterialExceptionCase.findUniqueOrThrow({where:{id:a.id}})).receivedQuantity,3);
    assert.equal((await readFollow()).ownerId,owner.id,'collaboration must preserve selected owner');
    await assert.rejects(update({status:'WAITING_WAREHOUSE',receivedQuantity:3}),/部分到料/);
    await assert.rejects(update({receivedQuantity:11}),/超过/);
    await assert.rejects(mutateMaterialFollowUp(follow.id,{action:'claim',version:follow.version},actor.id),/已更新/);
    await update({status:'WAITING_WAREHOUSE',receivedQuantity:10});
    assert.equal((await read()).status,'exception','reported arrival does not close warehouse');
    const resolved=await warehouse('resolve',{exceptionId:a.id,note:'10 个已核对',resolution:'completed'});
    assert.equal(resolved.status,'exception');
    assert.equal(resolved.completedAt,null);
    assert.equal(resolved.exceptionCases.find(e=>e.id===b.id)!.status,'OPEN');
    assert.equal((await readFollow()).status,'RESOLVED');
    assert.ok((await prisma.workOrder.findUniqueOrThrow({where:{id:work.id}})).materialStatus?.includes('客供'));
    const done=await warehouse('resolve',{exceptionId:b.id,note:'客供齐料',resolution:'completed'});
    assert.equal(done.status,'completed');assert.ok(done.completedAt);
    assert.equal(await prisma.materialFollowUpTask.count({where:{warehouseTaskId:task.id,status:'RESOLVED'}}),2);
    const reopened=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'新的独立事项'});
    const unknown=reopened.exceptionCases.find(e=>e.status==='OPEN')!;
    assert.equal(unknown.supplySource,'UNKNOWN');
    const uf=await prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:unknown.id}});
    await classifyMaterialFollowUps([{id:uf.id,version:uf.version}],'CUSTOMER',actor.id);
    const after=await prisma.materialFollowUpTask.findUniqueOrThrow({where:{id:uf.id},include:{warehouseException:true}});
    assert.equal(after.status,uf.status);assert.equal(after.ownerId,uf.ownerId);assert.deepEqual(after.expectedAt,uf.expectedAt);assert.equal(after.warehouseException.supplySource,'CUSTOMER');
    await assert.rejects(classifyMaterialFollowUps([{id:uf.id,version:uf.version}],'PURCHASED',actor.id),/已更新/);
    const cas=(await read()).version;
    const concurrent=await Promise.allSettled([1,2].map(n=>mutateWarehouseException(task.id,{action:'report_exception',version:cas,exceptionType:'shortage',exceptionNote:'并发 '+n,supplySource:'PURCHASED'},actor.id,true)));
    assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);
    assert.ok((await prisma.materialFollowUpActivity.findMany({where:{taskId:follow.id}})).some(x=>x.content?.includes('累计到料：3 → 10')));
    assert.equal(await prisma.productionPlanBatchHold.count({where:{workOrderId:work.id,status:'ACTIVE',holdType:'MATERIAL'}}),0,'shortage remains a risk prompt, not a new production hold');
  } finally {
    await prisma.workOrder.delete({where:{id:work.id}});
    await prisma.user.deleteMany({where:{id:{in:[actor.id,owner.id]}}});
  }
});

test('finished goods captures each completion, keeps dates after receipts, and filters business dates independently of receipt dates', {skip}, async()=>{
  process.env.FINISHED_GOODS_QA_ALLOW='disposable-finished-goods-runtime';
  const {createFixture}=require('../scripts/seed-finished-goods-smoke.cjs');
  const fixture=await createFixture(prisma,1);
  const first=await prisma.fgLot.findUniqueOrThrow({where:{id:fixture.lots[0].id}});
  const completion=await prisma.processCompletion.findUniqueOrThrow({where:{id:fixture.lots[0].completionId}});
  assert.deepEqual(first.productionWorkDate,completion.workDate);assert.deepEqual(first.productionCompletedAt,completion.completedAt);
  assert.ok(first.transferredAt);assert.equal(first.receivedAt,null);
  const earlier=new Date(Date.now()-86400000*3).toISOString().slice(0,10);
  const secondCompletion=await prisma.processCompletion.create({data:{workOrderId:completion.workOrderId,routeId:completion.routeId,stepId:completion.stepId,workDate:new Date(earlier+'T00:00:00Z'),completedAt:new Date(earlier+'T06:30:00Z'),processedQty:5,goodQty:5,defectQty:0,reportedUnitQty:5,reportedGoodUnitQty:5,reportedDefectUnitQty:0,coveredQty:5,coveredGoodQty:5,routeVersion:0,standardSource:'legacy',idempotencyKey:randomUUID(),createdById:fixture.actor.id}});
  const movement=await prisma.processQuantityMovement.create({data:{completionId:secondCompletion.id,workOrderId:completion.workOrderId,sourceStepId:completion.stepId,type:'FINISHED_GOOD',quantity:5,sourceSequenceGroup:1,idempotencyKey:randomUUID()}});
  const second=await prisma.fgLot.findUniqueOrThrow({where:{movementId:movement.id}});
  assert.deepEqual(second.productionCompletedAt,secondCompletion.completedAt);
  assert.notDeepEqual(second.productionWorkDate,first.productionWorkDate,'same order, separate physical completion lots');
  const pending=await loadFinishedGoods({q:first.workOrderCode,date:earlier,dateBasis:'production',scope:'range',filter:'pending'});
  assert.deepEqual(pending.rows.map(r=>r.lotId),[second.id],'pending items can be queried by actual production date');
  await mutateFinishedGoods({action:'RECEIVE',lotId:second.id,version:second.version,quantity:5,checked:true},fixture.actor,randomUUID());
  const received=await prisma.fgLot.findUniqueOrThrow({where:{id:second.id}});
  assert.deepEqual(received.productionWorkDate,second.productionWorkDate);assert.deepEqual(received.productionCompletedAt,second.productionCompletedAt);assert.deepEqual(received.transferredAt,second.transferredAt);assert.ok(received.receivedAt);
  const byProduction=await loadFinishedGoods({q:first.workOrderCode,view:'receipts',date:earlier,dateBasis:'production',scope:'range'});
  assert.deepEqual(byProduction.rows.map(r=>r.lotId),[second.id],'production date query cannot intersect with recent receipt date');
  const byReceipt=await loadFinishedGoods({q:first.workOrderCode,view:'receipts',date:earlier,scope:'range'});
  assert.equal(byReceipt.rows.length,0);
  const sorted=await loadFinishedGoods({q:first.workOrderCode,scope:'all',sort:'completed_asc'});
  assert.equal(sorted.rows[0].lotId,second.id);
  const opening=await prisma.fgLot.create({data:{sourceKey:randomUUID(),sourceKind:'OPENING',workOrderCode:first.workOrderCode+'-opening',productKey:'test',productName:'旧库存',specification:first.workOrderCode,sourceQuantity:2,available:2}});
  assert.equal(opening.productionCompletedAt,null);assert.equal(opening.transferredAt,null);
  // Exercise the exact source-backed backfill against a prior-version-shaped lot.
  await prisma.fgLot.update({where:{id:first.id},data:{productionCompletedAt:null,productionWorkDate:null,transferredAt:null}});
  const migration=readFileSync('prisma/migrations/202609210002_material_sources_completion_dates/migration.sql','utf8');
  const sql=migration.match(/UPDATE fg_lots l SET[\s\S]*?;/)![0];
  await prisma.$executeRawUnsafe(sql);
  const backfilled=await prisma.fgLot.findUniqueOrThrow({where:{id:first.id}});
  assert.deepEqual(backfilled.productionCompletedAt,completion.completedAt);
  assert.equal((await prisma.fgLot.findUniqueOrThrow({where:{id:opening.id}})).productionCompletedAt,null);
});
