import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { prisma } from '../lib/prisma';
import { mutateWarehouseException, mutateMaterialFollowUp, classifyMaterialFollowUps } from '../lib/material-exception-service';
import { serializeWarehouseMaterialTask } from '../lib/warehouse-material';
const skip = process.env.RUN_DB_INTEGRATION !== '1';

test('purchased and customer shortages remain independent through partial arrivals, conflicts and individual closure', {skip}, async()=>{
  const key='source-it-'+randomUUID().slice(0,8);
  const actor=await prisma.user.create({data:{username:key,passwordHash:'test-only',displayName:key,laborRole:'ADMIN'}});
  const owner=await prisma.user.create({data:{username:key+'-owner',passwordHash:'test-only',displayName:'原负责人'}});
  const work=await prisma.workOrder.create({data:{code:key,productName:'混合缺料',specification:key,customerName:'测试',planType:'managed_plan',planActive:true,stage:'not_issued'}});
  const task=await prisma.warehouseMaterialTask.create({data:{workOrderId:work.id}});
  const read=()=>prisma.warehouseMaterialTask.findUniqueOrThrow({where:{id:task.id}});
  const warehouse=async(action:string,body:Record<string,unknown>={},canConfirm=true)=>mutateWarehouseException(task.id,{version:(await read()).version,action,...body},actor.id,canConfirm);
  try {
    const first=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'端子缺 10 个',materialModel:'端子-A',supplySource:'PURCHASED',shortageQuantity:10,ownerId:owner.id},false);
    const a=first.exceptionCases.find(e=>e.status==='OPEN')!;
    const second=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'客供壳体缺 4 个',materialModel:'壳体-B',supplySource:'CUSTOMER',shortageQuantity:4},false);
    const b=second.exceptionCases.find(e=>e.id!==a.id)!;
    assert.equal(serializeWarehouseMaterialTask(second).activeExceptions?.length,2);
    await assert.rejects(warehouse('resolve',{note:'不能模糊关闭',resolution:'completed'}),/选择具体/);
    await assert.rejects(warehouse('resolve',{exceptionId:a.id,note:'协同不能代仓库确认',resolution:'completed'},false),/仓库/);
    const readFollow=()=>prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:a.id}});
    const follow=await readFollow();
    const future=new Date(Date.now()+5*86400000).toISOString().slice(0,10);
    const update=async(body:Record<string,unknown>)=>{const f=await readFollow();return mutateMaterialFollowUp(f.id,{action:'update',version:f.version,ownerId:owner.id,status:'WAITING_ARRIVAL',expectedAt:future,note:'分批补料',...body},actor.id);};
    await update({receivedQuantity:3});
    assert.equal((await prisma.warehouseMaterialExceptionCase.findUniqueOrThrow({where:{id:a.id}})).receivedQuantity,3);
    assert.equal((await readFollow()).ownerId,owner.id,'collaboration must preserve selected owner');
    await assert.rejects(update({status:'WAITING_WAREHOUSE',receivedQuantity:3}),/部分到料/);
    await assert.rejects(update({receivedQuantity:11}),/超过/);
    await assert.rejects(mutateMaterialFollowUp(follow.id,{action:'claim',version:follow.version},actor.id),/已更新/);
    await update({status:'WAITING_WAREHOUSE',receivedQuantity:10});
    assert.equal((await read()).status,'exception','reported arrival does not close warehouse');
    const resolved=await warehouse('resolve',{exceptionId:a.id,note:'10 个已核对',resolution:'completed'});
    assert.equal(resolved.status,'exception');
    assert.equal(resolved.completedAt,null);
    assert.equal(resolved.exceptionCases.find(e=>e.id===b.id)!.status,'OPEN');
    assert.equal((await readFollow()).status,'RESOLVED');
    assert.ok((await prisma.workOrder.findUniqueOrThrow({where:{id:work.id}})).materialStatus?.includes('客供'));
    const done=await warehouse('resolve',{exceptionId:b.id,note:'客供齐料',resolution:'completed'});
    assert.equal(done.status,'completed');assert.ok(done.completedAt);
    assert.equal(await prisma.materialFollowUpTask.count({where:{warehouseTaskId:task.id,status:'RESOLVED'}}),2);
    const reopened=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'新的独立事项'});
    const unknown=reopened.exceptionCases.find(e=>e.status==='OPEN')!;
    assert.equal(unknown.supplySource,'UNKNOWN');
    const uf=await prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:unknown.id}});
    await classifyMaterialFollowUps([{id:uf.id,version:uf.version}],'CUSTOMER',actor.id);
    const after=await prisma.materialFollowUpTask.findUniqueOrThrow({where:{id:uf.id},include:{warehouseException:true}});
    assert.equal(after.status,uf.status);assert.equal(after.ownerId,uf.ownerId);assert.deepEqual(after.expectedAt,uf.expectedAt);assert.equal(after.warehouseException.supplySource,'CUSTOMER');
    await assert.rejects(classifyMaterialFollowUps([{id:uf.id,version:uf.version}],'PURCHASED',actor.id),/已更新/);
    const cas=(await read()).version;
    const concurrent=await Promise.allSettled([1,2].map(n=>mutateWarehouseException(task.id,{action:'report_exception',version:cas,exceptionType:'shortage',exceptionNote:'并发 '+n,supplySource:'PURCHASED'},actor.id,true)));
    assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);
    assert.ok((await prisma.materialFollowUpActivity.findMany({where:{taskId:follow.id}})).some(x=>x.content?.includes('累计到料：3 → 10')));
    assert.equal(await prisma.productionPlanBatchHold.count({where:{workOrderId:work.id,status:'ACTIVE',holdType:'MATERIAL'}}),0,'shortage remains a risk prompt, not a new production hold');
  } finally {
    await prisma.workOrder.delete({where:{id:work.id}});
    await prisma.user.deleteMany({where:{id:{in:[actor.id,owner.id]}}});
  }
});
