import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { prisma } from '../lib/prisma';
import { mutateWarehouseException, mutateMaterialFollowUp, classifyMaterialFollowUps } from '../lib/material-exception-service';
import { serializeWarehouseMaterialTask, warehouseMaterialTaskListInclude } from '../lib/warehouse-material';
const skip = process.env.RUN_DB_INTEGRATION !== '1';

test('assignment, personal acceptance and handover stay consistent with warehouse under concurrent edits', { skip }, async () => {
  const key = 'assignment-it-' + randomUUID().slice(0,8);
  const manager = await prisma.user.create({ data: { username: key, passwordHash: 'test-only', displayName: '协调员' } });
  const recipient = await prisma.user.create({ data: { username: key+'-recipient', passwordHash: 'test-only', displayName: '接收人' } });
  const work = await prisma.workOrder.create({ data: { code:key, productName:'接收协同验收', stage:'not_issued' } });
  const warehouse = await prisma.warehouseMaterialTask.create({ data: { workOrderId:work.id, status:'exception' } });
  const eta = new Date(Date.now()+5*86400000);
  const event = await prisma.warehouseMaterialExceptionCase.create({ data: { warehouseTaskId:warehouse.id, sequence:1, exceptionType:'shortage', exceptionNote:'端子尚缺', supplySource:'PURCHASED', shortageQuantity:5, receivedQuantity:2, expectedArrivalAt:eta } });
  let task = await prisma.materialFollowUpTask.create({ data: { warehouseTaskId:warehouse.id, warehouseExceptionId:event.id, expectedAt:eta } });
  const current = () => prisma.materialFollowUpTask.findUniqueOrThrow({where:{id:task.id}});
  try {
    const competing = await Promise.allSettled([recipient.id, manager.id].map(ownerId => mutateMaterialFollowUp(task.id, {action:'assign', version:task.version, ownerId}, manager.id)));
    assert.equal(competing.filter(item=>item.status==='fulfilled').length,1,'one assignment wins the same version');
    task = await current();
    if (task.ownerId !== recipient.id) task = await mutateMaterialFollowUp(task.id,{action:'assign',version:task.version,ownerId:recipient.id},manager.id);
    assert.equal(task.status,'PENDING');
    assert.ok(task.assignedAt);
    assert.equal(task.acceptedAt,null);
    await assert.rejects(mutateMaterialFollowUp(task.id,{action:'claim',version:task.version},manager.id),/本人接收/);
    await assert.rejects(mutateMaterialFollowUp(task.id,{action:'update',version:task.version,status:'IN_PROGRESS',ownerId:recipient.id,note:'代理接收'},manager.id),/先接收/);
    await assert.rejects(mutateMaterialFollowUp(task.id,{action:'claim',version:task.version,receivedQuantity:5},recipient.id),/不能同时修改/);
    const accepted = await mutateMaterialFollowUp(task.id,{action:'claim',version:task.version},recipient.id);
    assert.equal(accepted.status,'IN_PROGRESS');
    assert.ok(accepted.acceptedAt);
    assert.equal(accepted.warehouseException.receivedQuantity,2);
    assert.equal(accepted.expectedAt?.toISOString(),eta.toISOString());
    assert.ok(accepted.activities.some(item=>item.action==='claim'&&item.actorId===recipient.id));
    task = await mutateMaterialFollowUp(task.id,{action:'note',version:accepted.version,note:'协同人补充了进展'},manager.id);
    assert.deepEqual(task.acceptedAt,accepted.acceptedAt,'later notes do not erase acceptance');
    const transfer = await mutateMaterialFollowUp(task.id,{action:'assign',version:task.version,ownerId:manager.id,note:'后续由协调员接手'},manager.id);
    assert.equal(transfer.status,'PENDING');
    assert.equal(transfer.acceptedAt,null);
    assert.match(transfer.latestProgress||'',/接收人.*协调员/);
    assert.equal(transfer.warehouseException.receivedQuantity,2);
    assert.deepEqual(transfer.expectedAt,eta);
    const projected=serializeWarehouseMaterialTask(await prisma.warehouseMaterialTask.findUniqueOrThrow({where:{id:warehouse.id},include:warehouseMaterialTaskListInclude}));
    assert.equal(projected.activeExceptions?.[0].owner?.id,manager.id);
    assert.equal(projected.activeExceptions?.[0].followUpStatus,'PENDING');
    assert.equal(projected.activeExceptions?.[0].acceptedAt,null);
    assert.ok(projected.activeExceptions?.[0].assignedAt);
    const warehouseLogs=await prisma.warehouseMaterialActivity.findMany({where:{taskId:warehouse.id}});
    assert.ok(warehouseLogs.some(item=>item.action==='material_follow_up_claim'&&item.actorId===recipient.id));
    assert.ok(warehouseLogs.some(item=>item.content?.includes('后续由协调员接手')));
    assert.equal((await prisma.warehouseMaterialTask.findUniqueOrThrow({where:{id:warehouse.id}})).status,'exception','assignment never marks materials complete');
  } finally {
    await prisma.workOrder.delete({where:{id:work.id}});
    await prisma.user.deleteMany({where:{id:{in:[manager.id,recipient.id]}}});
  }
});

test('purchased and customer shortages remain independent through partial arrivals, conflicts and individual closure', {skip}, async()=>{
  const key='source-it-'+randomUUID().slice(0,8);
  const actor=await prisma.user.create({data:{username:key,passwordHash:'test-only',displayName:key,laborRole:'ADMIN'}});
  const owner=await prisma.user.create({data:{username:key+'-owner',passwordHash:'test-only',displayName:'原负责人'}});
  const work=await prisma.workOrder.create({data:{code:key,productName:'混合缺料',specification:key,customerName:'测试',planType:'managed_plan',planActive:true,stage:'not_issued'}});
  const task=await prisma.warehouseMaterialTask.create({data:{workOrderId:work.id}});
  const read=()=>prisma.warehouseMaterialTask.findUniqueOrThrow({where:{id:task.id}});
  const warehouse=async(action:string,body:Record<string,unknown>={},canConfirm=true)=>mutateWarehouseException(task.id,{version:(await read()).version,action,...body},actor.id,canConfirm);
  const future=new Date(Date.now()+5*86400000).toISOString().slice(0,10);
  let createdDefaultOwnerId:string|null=null;
  try {
    const matches=await prisma.user.findMany({where:{isActive:true,OR:[{displayName:'贾改真'},{username:'贾改真'}]},select:{id:true},take:2});
    if (!matches.length) {
      const fallback=await prisma.user.create({data:{username:key+'-default',passwordHash:'test-only',displayName:'贾改真'}});
      createdDefaultOwnerId=fallback.id;
    }
    const expectedDefaultOwnerId=matches.length>1?null:matches[0]?.id||createdDefaultOwnerId;
    const first=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'端子缺 10 个',materialModel:'端子-A',supplySource:'PURCHASED',shortageQuantity:10,ownerId:owner.id,expectedAt:future},false);
    const a=first.exceptionCases.find(e=>e.status==='OPEN')!;
    const second=await warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'客供壳体缺 4 个',materialModel:'壳体-B',supplySource:'CUSTOMER',shortageQuantity:4},false);
    const b=second.exceptionCases.find(e=>e.id!==a.id)!;
    assert.equal((await prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:b.id}})).ownerId,expectedDefaultOwnerId,'unique active 贾改真 is assigned when warehouse has no people list');
    assert.equal(serializeWarehouseMaterialTask(second).activeExceptions?.length,2);
    await assert.rejects(warehouse('resolve',{note:'不能模糊关闭',resolution:'completed'}),/选择具体/);
    await assert.rejects(warehouse('resolve',{exceptionId:a.id,note:'协同不能代仓库确认',resolution:'completed'},false),/仓库/);
    const readFollow=()=>prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:a.id}});
    const follow=await readFollow();
    await mutateMaterialFollowUp(follow.id,{action:'claim',version:follow.version},owner.id);
    assert.equal((await prisma.warehouseMaterialExceptionCase.findUniqueOrThrow({where:{id:a.id}})).expectedArrivalAt?.toISOString(),follow.expectedAt?.toISOString());
    const update=async(body:Record<string,unknown>)=>{const f=await readFollow();return mutateMaterialFollowUp(f.id,{action:'update',version:f.version,ownerId:owner.id,status:'WAITING_ARRIVAL',expectedAt:future,note:'分批补料',...body},actor.id);};
    await update({receivedQuantity:3});
    await warehouse('update_exception',{exceptionId:a.id,exceptionType:'shortage',exceptionNote:'预计时间待确认',expectedAt:''});
    assert.equal((await readFollow()).status,'IN_PROGRESS','cleared ETA must revoke waiting-arrival status');
    assert.equal((await readFollow()).expectedAt,null);
    await update({receivedQuantity:3});
    assert.equal((await prisma.warehouseMaterialExceptionCase.findUniqueOrThrow({where:{id:a.id}})).receivedQuantity,3);
    assert.equal((await readFollow()).ownerId,owner.id,'collaboration must preserve selected owner');
    await assert.rejects(warehouse('resolve',{exceptionId:a.id,note:'只到 3 个',resolution:'completed'}),/累计到料未达到/);
    await assert.rejects(update({status:'WAITING_WAREHOUSE',receivedQuantity:3}),/部分到料/);
    await assert.rejects(update({receivedQuantity:11}),/超过/);
    await assert.rejects(mutateMaterialFollowUp(follow.id,{action:'claim',version:follow.version},actor.id),/已更新/);
    const beforeNote=await readFollow();
    const savedNote=await mutateMaterialFollowUp(beforeNote.id,{action:'note',version:beforeNote.version,note:'供应商确认正在发货'},owner.id);
    assert.ok(savedNote.activities.some(activity=>activity.action==='note' && activity.actorId===owner.id),'response includes the newly appended actor/time event');
    const afterNote=await readFollow();
    assert.equal(afterNote.status,beforeNote.status);
    assert.equal(afterNote.ownerId,beforeNote.ownerId);
    assert.equal(afterNote.latestProgress,'供应商确认正在发货');
    const projected = serializeWarehouseMaterialTask(await prisma.warehouseMaterialTask.findUniqueOrThrow({ where: { id: task.id }, include: warehouseMaterialTaskListInclude }));
    const firstProjection = projected.activeExceptions?.find(item => item.id === a.id);
    const secondProjection = projected.activeExceptions?.find(item => item.id === b.id);
    assert.equal(firstProjection?.latestProgress, '供应商确认正在发货', 'warehouse shows the current progress for this specific shortage');
    assert.equal(firstProjection?.latestActor?.id, owner.id, 'progress author is distinct from task owner');
    assert.ok(firstProjection?.lastFollowedAt, 'warehouse carries a real progress timestamp');
    assert.notEqual(secondProjection?.latestProgress, firstProjection?.latestProgress, 'another shortage never inherits this progress');

    assert.equal((await prisma.warehouseMaterialExceptionCase.findUniqueOrThrow({where:{id:a.id}})).receivedQuantity,3);
    assert.ok(await prisma.materialFollowUpActivity.count({where:{taskId:beforeNote.id,action:'note',actorId:owner.id,content:'供应商确认正在发货'}}));
    await assert.rejects(mutateMaterialFollowUp(afterNote.id,{action:'note',version:afterNote.version,note:'夹带状态',status:'RESOLVED'},owner.id),/普通进展只能填写文字/);
    await update({status:'WAITING_WAREHOUSE',receivedQuantity:10});
    assert.equal((await read()).status,'exception','reported arrival does not close warehouse');
    await warehouse('update_exception',{exceptionId:a.id,exceptionType:'shortage',exceptionNote:'实际缺 12 个',shortageQuantity:12,supplySource:'CUSTOMER',materialModel:'端子-A-替代'});
    const corrected=await prisma.warehouseMaterialExceptionCase.findUniqueOrThrow({where:{id:a.id}});
    assert.equal(corrected.supplySource,'CUSTOMER');
    assert.equal(corrected.materialModel,'端子-A-替代');
    assert.equal((await readFollow()).status,'IN_PROGRESS','quantity correction must revoke warehouse confirmation');
    assert.equal((await prisma.warehouseMaterialExceptionCase.findUniqueOrThrow({where:{id:a.id}})).actualArrivalAt,null);
    await assert.rejects(warehouse('resolve',{exceptionId:a.id,note:'仍只到 10 个',resolution:'completed'}),/累计到料未达到/);
    await update({status:'WAITING_WAREHOUSE',receivedQuantity:12});
    const resolved=await warehouse('resolve',{exceptionId:a.id,note:'12 个已核对',resolution:'completed'});
    assert.equal(resolved.status,'exception');
    assert.equal(resolved.completedAt,null);
    assert.equal(resolved.exceptionCases.find(e=>e.id===b.id)!.status,'OPEN');
    assert.equal((await readFollow()).status,'RESOLVED');
    assert.ok((await prisma.workOrder.findUniqueOrThrow({where:{id:work.id}})).materialStatus?.includes('客供'));
    await assert.rejects(warehouse('resolve',{exceptionId:b.id,note:'客供尚未登记到料',resolution:'completed'}),/累计到料未达到/);
    let bFollow=await prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:b.id}});
    if (bFollow.ownerId !== actor.id) bFollow=await mutateMaterialFollowUp(bFollow.id,{action:'assign',version:bFollow.version,ownerId:actor.id},actor.id);
    bFollow=await mutateMaterialFollowUp(bFollow.id,{action:'claim',version:bFollow.version},actor.id);
    await mutateMaterialFollowUp(bFollow.id,{action:'update',version:bFollow.version,ownerId:actor.id,status:'WAITING_WAREHOUSE',expectedAt:future,note:'客供壳体 4 个已到',receivedQuantity:4},actor.id);
    const done=await warehouse('resolve',{exceptionId:b.id,note:'客供齐料',resolution:'completed'});
    assert.equal(done.status,'completed');assert.ok(done.completedAt);
    assert.equal(await prisma.materialFollowUpTask.count({where:{warehouseTaskId:task.id,status:'RESOLVED'}}),2);
    await assert.rejects(warehouse('report_exception',{exceptionType:'shortage',exceptionNote:'缺料来源未知'}),/请选择采购物料或客供物料/);
    const reopened=await warehouse('report_exception',{exceptionType:'other',exceptionNote:'新的独立事项'});
    const unknown=reopened.exceptionCases.find(e=>e.status==='OPEN')!;
    assert.equal(unknown.supplySource,'UNKNOWN');
    const uf=await prisma.materialFollowUpTask.findUniqueOrThrow({where:{warehouseExceptionId:unknown.id}});
    await classifyMaterialFollowUps([{id:uf.id,version:uf.version}],'CUSTOMER',actor.id);
    const after=await prisma.materialFollowUpTask.findUniqueOrThrow({where:{id:uf.id},include:{warehouseException:true}});
    assert.equal(after.status,uf.status);assert.equal(after.ownerId,uf.ownerId);assert.deepEqual(after.expectedAt,uf.expectedAt);assert.equal(after.warehouseException.supplySource,'CUSTOMER');
    await assert.rejects(classifyMaterialFollowUps([{id:uf.id,version:uf.version}],'PURCHASED',actor.id),/已更新/);
    const cas=(await read()).version;
    const concurrent=await Promise.allSettled([1,2].map(n=>mutateWarehouseException(task.id,{action:'report_exception',version:cas,exceptionType:'shortage',exceptionNote:'并发 '+n,supplySource:'PURCHASED',materialModel:'并发端子'},actor.id,true)));
    assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);
    assert.ok((await prisma.materialFollowUpActivity.findMany({where:{taskId:follow.id}})).some(x=>x.content?.includes('累计到料：3 → 10')));
    assert.equal(await prisma.productionPlanBatchHold.count({where:{workOrderId:work.id,status:'ACTIVE',holdType:'MATERIAL'}}),0,'shortage remains a risk prompt, not a new production hold');
  } finally {
    await prisma.workOrder.delete({where:{id:work.id}});
    if (createdDefaultOwnerId) await prisma.user.delete({where:{id:createdDefaultOwnerId}});
    await prisma.user.deleteMany({where:{id:{in:[actor.id,owner.id]}}});
  }
});
