import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { prisma } from '../lib/prisma';
import { mutateMaterialOrder, readMaterialOrder } from '../lib/material-order-service';
import { mutateWarehouseException } from '../lib/material-exception-service';
const skip = process.env.RUN_DB_INTEGRATION !== '1';
test('weekly order closes through partial receipt and verification with shared authors, retries, concurrency and plan changes', { skip, timeout: 60000 }, async () => {
  const marker = 'week-ledger-' + randomUUID();
  const actor = await prisma.user.create({ data: { username: marker, displayName: '仓库', passwordHash: 'test-only' } });
  const colleague = await prisma.user.create({ data: { username: marker + '-2', displayName: '协同', passwordHash: 'test-only' } });
  const work = await prisma.workOrder.create({ data: { code: marker, productName: marker, specification: 'SAME-SPEC', stage: 'not_issued', productionTargetQty: 10 } });
  const other = await prisma.workOrder.create({ data: { code: marker + '-other', productName: marker, specification: 'SAME-SPEC', stage: 'not_issued', productionTargetQty: 10 } });
  let order = await readMaterialOrder((await prisma.warehouseMaterialTask.create({ data: { workOrderId: work.id } })).id);
  const otherTask = await prisma.warehouseMaterialTask.create({ data: { workOrderId: other.id } });
  const change = async (action: string, values: { [key: string]: unknown } = {}, confirm = true, by = actor.id) => { order = await mutateMaterialOrder(order.id, { action, version: order.version, requestKey: randomUUID(), ...values }, by, confirm); return order; };
  try {
    assert.equal(order.state, 'UNCHECKED');
    await change('report_exception', { materialModel: 'TERM-A', supplySource: 'PURCHASED', shortageQuantity: 10, unit: '个', exceptionType: 'shortage' });
    const first = order.events[0].id;
    assert.equal((await prisma.materialFollowUpTask.findUniqueOrThrow({ where: { warehouseExceptionId: first } })).ownerId, null);
    await change('report_exception', { materialModel: 'TAIL-B', supplySource: 'CUSTOMER', shortageQuantity: 2, unit: '个', exceptionType: 'shortage' });
    const second = order.events[1].id;
    await assert.rejects(change('complete'), /异常|缺料/);
    const noteRequest = { action: 'note', version: order.version, requestKey: randomUUID(), note: '部门协同，无需接收' };
    await mutateMaterialOrder(order.id, noteRequest, colleague.id, false);
    await mutateMaterialOrder(order.id, noteRequest, colleague.id, false);
    assert.equal(await prisma.warehouseMaterialActivity.count({ where: { taskId: order.id, content: noteRequest.note } }), 1);
    order = await readMaterialOrder(order.id);
    const parallelVersion = order.version;
    const concurrent = await Promise.allSettled(['2026-09-29','2026-09-30'].map(expectedAt => mutateMaterialOrder(order.id, { action: 'eta', version: parallelVersion, requestKey: randomUUID(), exceptionId: first, expectedAt }, colleague.id, false)));
    assert.equal(concurrent.filter(r => r.status === 'fulfilled').length, 1);
    order = await readMaterialOrder(order.id);
    await change('record_shipment', { exceptionId: first, quantity: 4, trackingNumber: 'SHARED-PARCEL', logisticsMode: 'EXPRESS' }, false, colleague.id);
    await assert.rejects(change('update_exception', { exceptionId: first, materialModel: 'ANOTHER-MODEL', supplySource: 'PURCHASED', shortageQuantity: 10, unit: '个', exceptionType: 'shortage' }), /型号或单位/);
    await assert.rejects(change('update_exception', { exceptionId: first, materialModel: 'TERM-A', supplySource: 'PURCHASED', shortageQuantity: 10, unit: '米', exceptionType: 'shortage' }), /型号或单位/);
    await assert.rejects(mutateWarehouseException(order.id, { action: 'update_exception', version: order.version, exceptionId: first, materialModel: 'OTHER', supplySource: 'PURCHASED', shortageQuantity: 10, unit: '个', exceptionType: 'shortage', exceptionNote: '更换物料' }, actor.id, true), /型号或单位/);
    let arrival = order.events[0].arrivals[0];
    await change('report_arrival', { exceptionId: first, arrivalId: arrival.id }, false, colleague.id);
    assert.equal(order.events[0].pending, 4);
    assert.equal(order.events[0].usable, 0);
    await assert.rejects(change('verify_arrival', { exceptionId: first, arrivalId: arrival.id, acceptedQuantity: 4 }, false, colleague.id), /权限/);
    await assert.rejects(mutateWarehouseException(order.id, { action: 'resolve', resolution: 'pending', version: order.version, exceptionId: first, note: '不能跳过核验' }, actor.id, true), /逐批核验/);
    await change('verify_arrival', { exceptionId: first, arrivalId: arrival.id, acceptedQuantity: 3, note: '一件错料退补' });
    assert.equal(order.events[0].remaining, 7);
    assert.equal(order.openCount, 2);
    await change('report_arrival', { exceptionId: first, quantity: 7, logisticsMode: 'SELF_DELIVERY' }, false, colleague.id);
    arrival = order.events[0].arrivals.find(b => b.status === 'ARRIVED')!;
    await change('verify_arrival', { exceptionId: first, arrivalId: arrival.id, acceptedQuantity: 7 });
    assert.equal(order.openCount, 1, 'one item cannot resolve its sibling');
    await change('report_arrival', { exceptionId: second, quantity: 2, logisticsMode: 'PICKUP' }, false, colleague.id);
    await change('verify_arrival', { exceptionId: second, arrivalId: order.events[1].arrivals[0].id, acceptedQuantity: 2 });
    assert.equal(order.state, 'CONFIRM');
    assert.equal((await readMaterialOrder(otherTask.id)).state, 'UNCHECKED', 'same spec remains a separate weekly order');
    await change('complete', { note: '仓库核对整单' });
    assert.equal(order.state, 'READY');
    assert.equal((await prisma.workOrder.findUniqueOrThrow({ where: { id: work.id } })).materialStatus, '已配料');
    await prisma.workOrder.update({ where: { id: work.id }, data: { productionTargetQty: 12 } });
    order = await readMaterialOrder(order.id);
    assert.notEqual(order.state, 'READY', 'plan quantity change reopens physical verification');
    assert.equal(order.events[0].usable, 10, 'receipt facts survive the plan change');
    assert.ok(order.activities.some(a => a.action === 'plan_changed'));
    await change('report_exception', { materialModel: 'EXTRA-C', supplySource: 'CUSTOMER', shortageQuantity: 1, unit: '个', exceptionType: 'shortage' });
    await prisma.workOrder.update({ where: { id: work.id }, data: { deletedAt: new Date() } });
    order = await readMaterialOrder(order.id);
    assert.equal(order.cancelled, true);
    const cancelledProjection = await prisma.warehouseMaterialTask.findUniqueOrThrow({ where: { id: order.id } });
    assert.notEqual(cancelledProjection.status, 'exception', 'cancelled sources must not leave an active warehouse anomaly');
    assert.equal(cancelledProjection.expectedAt, null);
    assert.equal(order.events.find(e => e.model === 'EXTRA-C')?.status, 'CANCELLED');
    assert.equal(order.openCount, 0);
    await assert.rejects(change('note', { note: 'cancelled write' }), /已取消/);
    assert.equal(order.events[0].usable, 10);
  } finally {
    await prisma.workOrder.deleteMany({ where: { id: { in: [work.id, other.id] } } });
    await prisma.operationLog.deleteMany({ where: { userId: { in: [actor.id, colleague.id] } } });
    await prisma.user.deleteMany({ where: { id: { in: [actor.id, colleague.id] } } });
  }
});
