import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { prisma } from '../lib/prisma';
import { poolCommand, loadOrderPool, previewPoolRows } from '../lib/order-pool-service';
import { poolWarehouseQueue } from '../lib/order-pool-warehouse';
import { readMaterialOrder, mutateMaterialOrder } from '../lib/material-order-service';
import { distributePoolCoverage, lockOrderPool } from '../lib/order-pool-material';
import { chinaWeekRange, deleteProductionPlanBatches } from '../lib/production-planning';
const skip=process.env.RUN_DB_INTEGRATION!=='1';
test('order pool: preparation without a week, shared priority, material coverage, concurrency and duplicate import', {skip,timeout:120000},async()=>{
 const database=new URL(process.env.DATABASE_URL||'postgresql://invalid/invalid');
 assert.ok(['127.0.0.1','localhost'].includes(database.hostname)&&/(_ci|_test)$/.test(database.pathname),'disposable local database required');
 const marker='pool-test-'+randomUUID(), keys:string[]=[];
 const actor=await prisma.user.create({data:{username:marker,passwordHash:'disposable-only',displayName:'订单池验证'}});
 const ids:string[]=[],works:string[]=[];
 const run=async(input:Record<string,unknown>)=>{const requestKey=randomUUID();keys.push(requestKey);const body={...input,requestKey};const result=await poolCommand(body,actor.id) as Record<string,any>;return {body,result};};
 const queue=()=>loadOrderPool(new URLSearchParams({q:marker}));
 try{
  for(let i=1;i<=2;i++){const {result}=await run({action:'create',row:{customerName:marker,specification:'SHARED-SPEC',productName:'线束',sourceOrderNo:marker+i,sourceLineNo:1,orderQuantity:100,unitMinutes:2}});ids.push(result.ids[0]);}
  let q=await queue();assert.equal(q.orders.length,2);let one=q.orders.find(o=>o.id===ids[0])!;
  assert.equal(one.customerDueDate,'','unknown customer date is not replaced with a promised date');
  assert.equal(one.drawingLibraryItemId,q.orders[1].drawingLibraryItemId,'one canonical product across orders');
  assert.equal(await prisma.productionPlanBatch.count({where:{planOrderId:{in:ids}}}),0,'pool creation creates no production week or labor');
  assert.equal(one.unitMilliseconds,120000);assert.equal(one.warehouseTaskId!=null,true);
  const wk=await poolWarehouseQueue(new URLSearchParams({q:marker,status:'all'}));
  assert.deepEqual(wk.orders.map(o=>o.planOrderId),q.orders.map(o=>o.id),'warehouse receives plan priority order');
  const cmd=await run({action:'priority',ids:[ids[1]],versions:{[ids[1]]:q.orders[1].version},queueToken:q.queueToken,priority:'insert'});
  await poolCommand(cmd.body,actor.id);
  q=await queue();assert.equal(q.orders[0].id,ids[1]);assert.equal(q.orders[0].rank,1);
  const before=q.orders[1];
  const edits=await Promise.allSettled([10,20].map(preparationQuantity=>run({action:'edit',ids:[before.id],versions:{[before.id]:before.version},orderQuantity:100,preparationQuantity,customerDueDate:'',unitMinutes:2})));
  assert.equal(edits.filter(e=>e.status==='fulfilled').length,1,'concurrent stale edits cannot both succeed');
  q=await queue();one=q.orders.find(o=>o.id===ids[0])!;
  await run({action:'edit',ids:[one.id],versions:{[one.id]:one.version},orderQuantity:100,preparationQuantity:100,customerDueDate:'',unitMinutes:2});
  let material=await readMaterialOrder(one.warehouseTaskId!);
  const change=async(action:string,values:Record<string,unknown>={},confirm=true)=>{material=await mutateMaterialOrder(material.id,{action,version:material.version,requestKey:randomUUID(),...values},actor.id,confirm);return material;};
  await change('confirm_prepared',{preparedQuantity:40});
  assert.equal(material.preparedQuantity,40);assert.equal(material.state,'PARTIAL');
  await change('report_exception',{materialModel:'TERM-A',supplySource:'PURCHASED',shortageQuantity:1,unit:'个',exceptionType:'shortage'});
  assert.equal(material.preparedQuantity,0,'new shortage invalidates unallocated coverage');
  const event=material.events[0];
  assert.ok(event.followUpId);
  await assert.rejects(change('confirm_prepared',{preparedQuantity:100}),/缺料/);
  await assert.rejects(change('confirm_prepared',{preparedQuantity:40},false),/权限/);
  await change('confirm_prepared',{preparedQuantity:40});
  await change('eta',{exceptionId:event.id,expectedAt:'2026-10-02'},false);
  assert.equal(material.events[0].expectedAt?.slice(0,10),'2026-10-02');
  await change('confirm_arrival',{exceptionId:event.id,quantity:1,acceptedQuantity:1});
  assert.equal(material.openCount,0);
  const week=chinaWeekRange(new Date());
  const work=await prisma.workOrder.create({data:{code:marker+'-work',productName:'线束',specification:'SHARED-SPEC',stage:'not_issued',productionTargetQty:30,materialTask:{create:{status:'pending'}}}});works.push(work.id);
  const batch=await prisma.productionPlanBatch.create({data:{planOrderId:one.id,batchNo:1,quantity:30,weekStartDate:week.start,weekEndDate:week.end,plannedCompletionDate:week.end,workOrderId:work.id,poolPreparationLinked:true}});
  await prisma.$transaction(async tx=>{await lockOrderPool(tx);await distributePoolCoverage(tx,one.id,actor.id);});
  const child=await prisma.warehouseMaterialTask.findUniqueOrThrow({where:{workOrderId:work.id}});
  assert.equal(child.status,'completed');assert.equal(child.preparedQuantity,30);
  q=await queue();one=q.orders.find(o=>o.id===ids[0])!;assert.equal(one.remaining,70);assert.equal(one.readyRemaining,10);assert.equal(one.consumed,30);
  const second=q.orders.find(o=>o.id===ids[1])!;assert.equal(second.readyRemaining,0,'same product must not share physical stock across different orders');
  await assert.rejects(change('confirm_prepared',{preparedQuantity:20}),/已分配|分配到/);
  const oldKey=randomUUID(),version=material.version;
  const request={action:'confirm_prepared',preparedQuantity:50,version,requestKey:oldKey};
  material=await mutateMaterialOrder(material.id,request,actor.id,true);
  assert.equal(material.state,'PARTIAL','partly prepared pool orders cannot still say unchecked');
  await mutateMaterialOrder(material.id,request,actor.id,true);
  assert.equal((await queue()).orders.find(o=>o.id===ids[0])?.readyRemaining,20,'retry never duplicates confirmed units');
  await change('reopen',{note:'重新核对现场'});
  assert.equal((await prisma.warehouseMaterialTask.findUniqueOrThrow({where:{id:child.id}})).status,'pending','revoked parent credit cannot leave carried completion green');
  const ownConfirmation=await readMaterialOrder(child.id);
  await mutateMaterialOrder(child.id,{action:'complete',version:ownConfirmation.version,requestKey:randomUUID(),note:'周订单独立核对齐料'},actor.id,true);
  await change('confirm_prepared',{preparedQuantity:60});
  await change('reopen',{note:'再次核对订单池剩余材料'});
  assert.equal((await readMaterialOrder(child.id)).state,'READY','independent weekly physical confirmation survives parent recheck');
  await change('confirm_prepared',{preparedQuantity:60});
  const preview=await previewPoolRows([{customerName:marker,specification:'SHARED-SPEC',productName:'线束',sourceOrderNo:marker+1,sourceLineNo:1,orderQuantity:100,unitMinutes:2}],marker);
  assert.equal(preview[0].action,'skip');
  await run({action:'import',rows:preview});
  assert.equal(await prisma.productionPlanOrder.count({where:{customerName:marker}}),2);
  const duplicate=await previewPoolRows([{customerName:marker,specification:'SHARED-SPEC',orderQuantity:2,sourceOrderNo:'same',sourceLineNo:1},{customerName:marker,specification:'SHARED-SPEC',orderQuantity:2,sourceOrderNo:'same',sourceLineNo:1}],marker);
  assert.equal(duplicate[1].action,'error');
  // Deleting a draft subtracts its order quantity; it must also subtract carried coverage.
  await prisma.$transaction(tx=>deleteProductionPlanBatches(tx,{batchIds:[batch.id],actorId:actor.id}));
  const afterDelete=await prisma.productionPlanOrder.findUniqueOrThrow({where:{id:one.id},include:{poolMaterialTask:true}});
  assert.equal(afterDelete.orderQuantity,70);assert.equal(afterDelete.poolMaterialTask?.preparedQuantity,30);
  q=await queue();const two=q.orders.find(o=>o.id===ids[1])!;
  await run({action:'cancel',ids:[two.id],versions:{[two.id]:two.version},note:'客户撤单'});
  assert.equal((await queue()).orders.some(o=>o.id===two.id),false);
  assert.equal((await poolWarehouseQueue(new URLSearchParams({q:marker,status:'all'}))).orders.some(o=>o.planOrderId===two.id),false);
 }finally{
  await prisma.workOrder.deleteMany({where:{id:{in:works}}});
  await prisma.warehouseMaterialTask.deleteMany({where:{planOrderId:{in:ids}}});
  await prisma.productionPlanOrder.deleteMany({where:{id:{in:ids}}});
  await prisma.orderPoolCommand.deleteMany({where:{key:{in:keys}}});
  await prisma.operationLog.deleteMany({where:{userId:actor.id}});
  await prisma.drawingLibraryItem.deleteMany({where:{customerName:marker}});
  await prisma.user.delete({where:{id:actor.id}});
 }
});
