import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import ExcelJS from 'exceljs';
import { prisma } from '../lib/prisma';
import { emptyQualityForm, type QualityRecord } from '../lib/quality-data';
import { createQualityRecord, loadQualityRecord, mutateQualityRecord, qualityHistoricalRecord } from '../lib/quality-data-service';
import { paperArchiveList } from '../lib/quality-paper-archive-service';
import { paperWorkbook } from '../lib/quality-data-export';
import { deleteQualityFile } from '../lib/quality-data-files';

test('date paper archives accept mixed-product sheets, preserve upload facts and filter overlapping dates once', { skip: process.env.RUN_DB_INTEGRATION !== '1' }, async () => {
  const marker='paper-date-'+randomUUID(), ids:string[]=[];
  const actor={id:marker,name:'日期归档验收员',canManage:true,canReview:true};
  const params=(extra:Record<string,string>={})=>new URLSearchParams({type:'FIRST',period:'all',q:marker,...extra});
  const data=(end?:string)=>({...emptyQualityForm('FIRST',''),mode:'FILE',rows:[],paper:{result:null,area:'',dateEnd:end}});
  const create=async(extra:Record<string,unknown>={})=>{const r=await createQualityRecord(actor,{type:'FIRST',title:marker,inspectedAt:'2026-09-14T00:00',data:data(),idempotencyKey:randomUUID(),...extra});ids.push(r.id);return r;};
  const metadata=(r:QualityRecord)=>({title:r.title,inspectedAt:r.inspectedAt,data:r.data,version:r.version});
  const attach=async(r:QualityRecord,at:string,by=actor.id)=>{await prisma.qualityDataAttachment.create({data:{recordId:r.id,originalName:'跨产品纸表.png',objectKey:marker+'/'+randomUUID(),sha256:randomUUID().replaceAll('-','').repeat(2),size:1,mimeType:'image/png',createdAt:new Date(at),createdById:by}});return loadQualityRecord(r.id);};
  try {
    for(const type of ['FIRST','PATROL'])for(const link of [{workOrderId:'any'},{inspectionStepId:'any'},{sourceQrCode:'any'},{supersedesId:'any'}])await assert.rejects(create({type,...link}),/按日期归档/);
    await assert.rejects(create({data:emptyQualityForm('FIRST')}),/照片/);
    await assert.rejects(create({data:data('2026-09-13')}),/早于/);
    let report=await create({data:data('2026-09-16')});
    assert.equal(report.workOrderId,null);assert.equal(report.inspectionStepId,null);assert.equal(report.data.context.inspectedBy,'');
    await assert.rejects(mutateQualityRecord(report.id,actor,{...metadata(report),action:'SUBMIT'}),/附件/);
    report=await attach(report,'2026-09-18T01:00:00Z');
    report=await mutateQualityRecord(report.id,actor,{...metadata(report),action:'SUBMIT'});
    assert.equal(report.status,'SUBMITTED');assert.equal(report.result,'PENDING');
    const submittedVersion=report.version;
    for(const day of ['2026-09-14','2026-09-15','2026-09-16'])assert.equal((await paperArchiveList(params({period:'today',date:day}),actor.id)).total,1);
    assert.equal((await paperArchiveList(params({period:'today',date:'2026-09-17'}),actor.id)).total,0);
    assert.equal((await paperArchiveList(params({period:'custom',startDate:'2026-09-14',endDate:'2026-09-16'}),actor.id)).total,1);
    const timeline=(await paperArchiveList(params(),actor.id)).items[0];
    assert.equal(timeline.activity.firstUploadedAt,'2026-09-18T01:00:00.000Z');
    assert.equal((await paperArchiveList(params({period:'today',date:'2026-09-18',timeField:'upload'}),actor.id)).total,1);
    assert.equal((await paperArchiveList(params({period:'today',date:'2026-09-14',timeField:'upload'}),actor.id)).total,0);
    assert.equal((await paperArchiveList(params({mine:'1'}),'someone-else')).total,0);
    await assert.rejects(deleteQualityFile(report.attachments[0].id,actor,{version:report.version,reason:'删唯一原件'}),/附件/);
    report=await attach(report,'2026-09-19T02:00:00Z','supplementer');
    const uploaded=(await paperArchiveList(params({mine:'1'}),'supplementer')).items[0];
    assert.equal(uploaded.activity.lastUploadedAt,'2026-09-19T02:00:00.000Z');assert.equal(uploaded.activity.firstUploadedAt,timeline.activity.firstUploadedAt);
    report=await mutateQualityRecord(report.id,actor,{...metadata(report),action:'SAVE',reason:'补充说明',data:{...report.data,summary:'更改备注'}});
    assert.equal((await paperArchiveList(params(),actor.id)).items[0].activity.lastUploadedAt,uploaded.activity.lastUploadedAt);
    await assert.rejects(mutateQualityRecord(report.id,actor,{...metadata(report),action:'SAVE',reason:'非法改格式',data:emptyQualityForm('FIRST')}),/日期报表/);
    for(let i=0;i<22;i++)await create({title:marker+' 草稿 '+i});
    let list=await paperArchiveList(params({status:'SUBMITTED'}),actor.id);assert.deepEqual(list.counts,{all:23,submitted:1,draft:22});assert.equal(list.total,1);
    const p1=await paperArchiveList(params(),actor.id),p2=await paperArchiveList(params({page:'2'}),actor.id);assert.equal(p1.items.length,20);assert.equal(p2.items.length,3);assert.equal(new Set([...p1.items,...p2.items].map(r=>r.id)).size,23);
    let patrol=await create({type:'PATROL',title:marker+' 巡检'});patrol=await attach(patrol,'2026-09-18T01:00:00Z');
    patrol=await mutateQualityRecord(patrol.id,actor,{...metadata(patrol),action:'SUBMIT'});
    assert.equal((await paperArchiveList(params({type:'PATROL'}),actor.id)).total,1);
    const book=new ExcelJS.Workbook();await book.xlsx.load(await paperWorkbook(list.items,'测试') as unknown as Parameters<typeof book.xlsx.load>[0]);assert.equal(book.getWorksheet('日期报表')!.rowCount,3);assert.ok(JSON.stringify(book.getWorksheet('日期报表')!.getRow(3).values).includes('2026-09-16'));
    report=await mutateQualityRecord(report.id,actor,{action:'DELETE',version:report.version,reason:'测试回收站'});assert.equal((await paperArchiveList(params({deleted:'1'}),actor.id)).total,1);
    report=await mutateQualityRecord(report.id,actor,{action:'RESTORE',version:report.version,reason:'测试恢复'});assert.equal(report.attachments.length,2);
    assert.equal((await qualityHistoricalRecord(report.id,submittedVersion)).attachments.length,1);
    await assert.rejects(paperArchiveList(params({period:'custom',startDate:'bad',endDate:'bad'}),actor.id),/日期范围/);
  }finally{await prisma.qualityDataRevision.deleteMany({where:{recordId:{in:ids}}});await prisma.qualityDataAttachment.deleteMany({where:{recordId:{in:ids}}});await prisma.qualityDataRecord.deleteMany({where:{id:{in:ids}}});}
});
