import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { prisma } from '../lib/prisma';
import { mutateFinishedGoods } from '../lib/finished-goods-service';
import { saveShippingReport, shippingReportContext, shippingReportFile } from '../lib/shipping-report-service';
import { PDFDocument } from 'pdf-lib';
const { createFixture } = require('../scripts/seed-finished-goods-smoke.cjs');
const skip = process.env.RUN_DB_INTEGRATION !== '1';

test('shipping reports use actual receipt facts, are idempotent and leave warehouse stock and ledger unchanged', { skip }, async () => {
  process.env.FINISHED_GOODS_QA_ALLOW = 'disposable-finished-goods-runtime';
  const fixture = await createFixture(prisma, 3), source = { lotId: fixture.lots[0].id };
  const lot = () => prisma.fgLot.findUniqueOrThrow({ where: { id: source.lotId } });
  const beforeReceipt = await shippingReportContext(source); assert.equal(beforeReceipt.eligible, false);
  await mutateFinishedGoods({ action: 'RECEIVE', lotId: source.lotId, version: (await lot()).version, quantity: 12, checked: true }, fixture.user, randomUUID());
  const receipt = await prisma.fgLedger.findFirstOrThrow({ where: { lotId: source.lotId, kind: 'RECEIVE' } });
  const c = await shippingReportContext({ ...source, receiptId: receipt.id }); assert.equal(c.quantity, 12); assert.equal(c.maxQuantity, 12);
  const input = { ...c.source, template: 'general', version: c.version, quantity: 9, orderNo: 'QA-ORDER', reportDate: '2026-09-27', drawingId: '', customerName: '错误客户' };
  const stored = new Map<string, Buffer>(), cleaned: string[] = [];
  const storage = { put: async ({ key, body }: { key: string; body: Buffer }) => { stored.set(key, body); }, cleanup: async (keys: string[]) => { keys.forEach(k => { cleaned.push(k); stored.delete(k); }); } };
  const before = await lot(), ledgerBefore = await prisma.fgLedger.count({ where: { lotId: source.lotId } });
  const key = randomUUID();
  const [a, b] = await Promise.all([saveShippingReport(input, fixture.user, key, storage), saveShippingReport(input, fixture.user, key, storage)]);
  assert.equal(a.id, b.id); assert.equal((await saveShippingReport(input, fixture.user, key, storage)).id, a.id);
  assert.equal(await prisma.fgShippingReport.count({ where: { lotId: source.lotId } }), 1); assert.equal(stored.size, 1);
  assert.equal(a.snapshot.customerName, before.customerName); assert.equal(a.quantity, 9); assert.equal(a.snapshot.orderNo, 'QA-ORDER');
  const row = await shippingReportFile(a.id); const pdf = await PDFDocument.load(stored.get(row.objectKey)!);
  assert.ok(pdf.getTitle()?.startsWith(a.number)); assert.equal(row.size, stored.get(row.objectKey)!.length);
  assert.deepEqual(await lot(), before); assert.equal(await prisma.fgLedger.count({ where: { lotId: source.lotId } }), ledgerBefore);
  assert.equal((await shippingReportContext(source)).reports[0].id, a.id);
  await assert.rejects(saveShippingReport({ ...input, quantity: 10 }, fixture.user, key, storage), /请求标识/);
  const foreignReceipt = await prisma.fgLedger.findFirst({ where: { lotId: fixture.lots[1].id } });
  if (foreignReceipt) await assert.rejects(shippingReportContext({ ...source, receiptId: foreignReceipt.id }), /不属于/);
  await assert.rejects(saveShippingReport(input, fixture.user, randomUUID(), { ...storage, put: async () => { throw new Error('storage unavailable'); } }), /storage unavailable/);
  assert.equal(await prisma.fgShippingReport.count({ where: { lotId: source.lotId } }), 1);
  const beforeConflict = stored.size;
  await assert.rejects(saveShippingReport(input, fixture.user, randomUUID(), { ...storage, put: async args => { await storage.put(args); await prisma.fgLot.update({ where: { id: source.lotId }, data: { version: { increment: 1 } } }); } }), /更新/);
  assert.equal(stored.size, beforeConflict); assert.ok(cleaned.length >= 1);
  assert.equal(await prisma.fgShippingReport.count({ where: { lotId: source.lotId } }), 1);
  const immutable = await shippingReportFile(a.id); assert.equal(immutable.snapshot && (immutable.snapshot as Record<string, unknown>).customerName, before.customerName);
});
