'use client';
import { useEffect, useState } from 'react';
import { Check, ChevronRight, History, Layers3, MapPin, Plus, Search } from 'lucide-react';
import { TOOLING_STATES, moldPositionName, type ToolingMoldDTO } from '@/lib/tooling-worklog-domain';
import { ToolingDialog, stamp, type Submit } from './ToolingShared';
export const INVENTORY_EVENT_NAMES:Record<string,string>={MOLD_CREATE:'新增专模',MOLD_EDIT:'更新资料',MOLD_MOVE:'移动专模',MOLD_RETURN:'专模归还',MOLD_MAINTENANCE:'登记维修',MOLD_RETIRE:'停用专模',MOLD_RELEASE:'专模去向',REGISTER:'首次盘点',ADD:'补充库存',MOVE:'移盒',RETURN:'归还刀片',MAINTENANCE:'登记维修',RETIRE:'停用实物',ASSEMBLE:'散刀组套',DISASSEMBLE:'拆为散刀',START:'开始使用',BACKSTART:'补记开始',BACKFILL:'历史补录',FINISH:'完成作业',SWAP:'更换刀位',PAUSE:'暂停',RESUME:'继续',HOURS_SYNC:'工时同步',CORRECT:'修正工时',SAVE_RECIPE:'保存方案'};
export function InventoryHistory({moldId,bladeId}:{moldId?:string;bladeId?:string}){
  const [events,setEvents]=useState<Array<{id:string;action:string;actorName:string;createdAt:string;detail:{reason?:string;position?:number;box?:number}}>>([]),[status,setStatus]=useState('加载中…');
  useEffect(()=>{let active=true;setStatus('加载中…');void fetch('/api/terminal-tooling/inventory?'+new URLSearchParams(moldId?{moldId}:{bladeId:bladeId!})).then(r=>r.json()).then(body=>{if(!active)return;if(!body.ok)throw Error();setEvents(body.events);setStatus(body.events.length?'':'暂无记录');}).catch(()=>{if(active)setStatus('记录暂时无法加载，请关闭后重试');});return()=>{active=false;};},[moldId,bladeId]);
  return <details className="tl-inventory-history"><summary><History size={16}/>库存与使用记录</summary>{status&&<small role="status">{status}</small>}<ol className="tl-timeline">{events.map(e=><li key={e.id}><div><b>{INVENTORY_EVENT_NAMES[e.action]||'操作记录'}</b><time>{stamp(e.createdAt)}</time></div><small>{e.actorName}{e.detail.reason?' · '+e.detail.reason:''}{e.detail.position?' · '+moldPositionName(e.detail.position):''}{e.detail.box?' · 刀片盒 '+e.detail.box:''}</small></li>)}</ol></details>;
}
type Action='CREATE'|'EDIT'|'MOVE'|'RETURN'|'MAINTENANCE'|'RETIRE';
export default function ToolingMoldInventory({molds,submit,busy,canEdit}:{molds:ToolingMoldDTO[];submit:Submit;busy:boolean;canEdit:boolean}){
  const [search,setSearch]=useState(''),[state,setState]=useState('all'),[location,setLocation]=useState(''),[selected,setSelected]=useState(''),[action,setAction]=useState<Action|null>(null);
  const [model,setModel]=useState(''),[manufacturer,setManufacturer]=useState(''),[note,setNote]=useState(''),[position,setPosition]=useState(1),[reason,setReason]=useState(''),[restored,setRestored]=useState(false);
  const current=molds.find(m=>m.id===selected),list=molds.filter(m=>(state==='all'?m.state!=='RETIRED':m.state===state)&&(!location||(m.currentPosition??m.homePosition)===Number(location))&&[m.model,m.manufacturer,m.note].some(v=>v.toLowerCase().includes(search.toLowerCase())));
  function open(a:Action){setAction(a);setModel(current?.model||'');setManufacturer(current?.manufacturer||'');setNote(current?.note||'');setPosition(current?.homePosition||1);setReason('');setRestored(false);}
  async function save(){const result=await submit('inventory',{action:'MOLD_'+action,moldId:current?.id,version:current?.version,model,manufacturer,note,position,reason,restored});if(result){setAction(null);if(result.moldId)setSelected(String(result.moldId));}}
  const names:Record<Action,string>={CREATE:'新增专模',EDIT:'编辑专模资料',MOVE:'移动专模',RETURN:'确认归还与复原',MAINTENANCE:'登记维修',RETIRE:'停用专模'};
  return <div className="tl-mold-inventory"><div className="tl-inventory-tools"><label className="tl-search"><Search size={17}/><input placeholder="搜索专模型号 / 品牌" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="专模状态" value={state} onChange={e=>setState(e.target.value)}><option value="all">全部在用型号</option>{['AVAILABLE','IN_USE','RESTORE','MAINTENANCE','RETIRED'].map(v=><option key={v} value={v}>{TOOLING_STATES[v]}</option>)}</select><select aria-label="专模位置筛选" value={location} onChange={e=>setLocation(e.target.value)}><option value="">全部位置</option>{Array.from({length:20},(_,i)=><option key={i} value={i+1}>{moldPositionName(i+1)}</option>)}</select>{canEdit&&<button className="tl-primary" onClick={()=>{setSelected('');setModel('');setManufacturer('');setNote('');setPosition(1);setAction('CREATE');}}><Plus size={17}/>新增专模</button>}</div>
    <section className="tl-surface tl-inventory-list"><div className="tl-panel-title"><h3>专模库 <small>{list.length} 个型号</small></h3><span className="tl-muted">每型号 1 套 · 专模位 01–20</span></div><div className="tl-scroll"><table className="tl-table tl-mold-table"><thead><tr><th>专模型号</th><th>可用数量</th><th>位置</th><th>状态</th><th>当前使用</th><th>操作</th></tr></thead><tbody>{list.map(m=><tr key={m.id} tabIndex={0} onClick={()=>setSelected(m.id)} onKeyDown={e=>{if(e.key==='Enter')setSelected(m.id);}}><td><b>{m.model}</b>{m.manufacturer&&<small>{m.manufacturer}</small>}</td><td><strong>{m.state==='AVAILABLE'?1:0}</strong> 套</td><td><span className="tl-location"><MapPin size={14}/>{moldPositionName(m.currentPosition??m.homePosition)}{m.currentPosition==null?'（原位）':''}</span></td><td><span className={'tl-tag '+(m.state==='AVAILABLE'?'green':m.state==='IN_USE'?'blue':'amber')}>{TOOLING_STATES[m.state]}</span></td><td>{m.inUseJob?.actorName||'—'}</td><td><button className="tl-text" aria-label={'查看专模'+m.model}>查看<ChevronRight size={15}/></button></td></tr>)}</tbody></table>{!list.length&&<div className="tl-empty"><Layers3 size={32}/><b>{molds.length?'未找到匹配专模':'专模库尚未建档'}</b>{canEdit&&!molds.length&&<button className="tl-primary" onClick={()=>{setSelected('');setModel('');setAction('CREATE');}}>新增专模</button>}</div>}</div></section>
    {current&&!action&&<ToolingDialog title={current.model} className="tl-inventory-drawer" onClose={()=>setSelected('')} footer={canEdit&&current.state!=='RETIRED'?<><button disabled={busy||current.state!=='AVAILABLE'} onClick={()=>open('MOVE')}>移位</button><button disabled={busy||['RUNNING','PAUSED'].includes(current.inUseJob?.status||'')} onClick={()=>open('MAINTENANCE')}>维修</button><button disabled={busy||['RUNNING','PAUSED'].includes(current.inUseJob?.status||'')} onClick={()=>open('RETIRE')}>停用</button><button className="tl-primary" disabled={busy||current.state==='AVAILABLE'||['RUNNING','PAUSED'].includes(current.inUseJob?.status||'')} onClick={()=>open('RETURN')}><Check size={17}/>归还 / 恢复原配</button></>:undefined}>
      <div className="tl-pick-summary"><Layers3 size={27}/><div><b>{moldPositionName(current.currentPosition??current.homePosition)}</b><small>归属 {moldPositionName(current.homePosition)}</small></div><span className={'tl-tag '+(current.state==='AVAILABLE'?'green':'amber')}>{TOOLING_STATES[current.state]}</span></div><div className="tl-stock-metrics"><div><b>1</b><span>实物总量（套）</span></div><div><b>{current.state==='AVAILABLE'?1:0}</b><span>可用（套）</span></div><div><b>{current.state==='IN_USE'?1:0}</b><span>使用中（套）</span></div><div><b>{['RESTORE','MAINTENANCE'].includes(current.state)?1:0}</b><span>待处理（套）</span></div></div>{current.inUseJob&&<p className="tl-mold-note">{current.inUseJob.actorName} · {TOOLING_STATES[current.inUseJob.status]}</p>}{current.note&&<p className="tl-mold-note">{current.note}</p>}{canEdit&&<button className="tl-text" onClick={()=>open('EDIT')}>编辑品牌与备注</button>}<InventoryHistory moldId={current.id}/>
    </ToolingDialog>}
    {action&&<ToolingDialog title={names[action]} subtitle={action==='CREATE'?undefined:current?.model} onClose={()=>setAction(null)} busy={busy} footer={<><button disabled={busy} onClick={()=>setAction(null)}>取消</button><button className="tl-primary" disabled={busy||(action==='CREATE'&&!model.trim())||(['MAINTENANCE','RETIRE'].includes(action)&&!reason.trim())} onClick={()=>void save()}><Check size={17}/>{busy?'保存中…':'确认'+(action==='CREATE'?'新增':'保存')}</button></>}>
      {action==='CREATE'&&<label>专模型号<input autoComplete="off" aria-label="新专模型号" placeholder="例如：ZM-10023" value={model} onChange={e=>setModel(e.target.value)} maxLength={100}/></label>}
      {['CREATE','EDIT'].includes(action)&&<><label>制造商 / 品牌<input value={manufacturer} onChange={e=>setManufacturer(e.target.value)} maxLength={100}/></label><label>备注<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500}/></label></>}
      {['CREATE','MOVE','RETURN'].includes(action)&&<label>专模位置<select aria-label="专模位置" value={position} onChange={e=>setPosition(Number(e.target.value))}>{Array.from({length:20},(_,i)=><option key={i} value={i+1}>{moldPositionName(i+1)}</option>)}</select></label>}
      {action==='CREATE'&&<span className="tl-inline-note">实物数量 1 套 · 原配刀片随专模管理</span>}
      {action==='RETURN'&&<label className="tl-checkline"><input type="checkbox" checked={restored} onChange={e=>setRestored(e.target.checked)}/>专模已恢复原配，外借刀片已归还</label>}
      {['MAINTENANCE','RETIRE'].includes(action)&&<label>处理原因<textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></label>}
    </ToolingDialog>}
  </div>;
}
