'use client';
import { useMemo, useState } from 'react';
import { Archive, Box, Check, Layers3, MapPin, PackagePlus, Plus, Search, Wrench } from 'lucide-react';
import { TerminalBladeEditor, type TerminalBladeForm } from '@/components/TerminalBladeEditor';
import { TOOLING_POSITIONS, TOOLING_POSITION_NAMES, TOOLING_STATES, boxName } from '@/lib/tooling-worklog-domain';
import { ToolingDialog, type InventoryBlade, type Submit } from './ToolingShared';
type Action = 'REGISTER' | 'ADD' | 'MOVE' | 'RETURN' | 'MAINTENANCE' | 'RETIRE' | 'ASSEMBLE' | 'DISASSEMBLE';
const ACTION_NAMES: Record<Action,string> = {REGISTER:'登记实物库存',ADD:'补充库存',MOVE:'移动存放位置',RETURN:'归还刀片',MAINTENANCE:'登记待处理',RETIRE:'停用实物',ASSEMBLE:'散刀组套',DISASSEMBLE:'拆为散刀'};
export default function ToolingInventory({blades,submit,busy,canEdit,reload,mobile=false,initialBox}:{blades:InventoryBlade[];submit:Submit;busy:boolean;canEdit:boolean;reload:()=>Promise<void>;mobile?:boolean;initialBox?:number}){
  const [keyword,setKeyword]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(''),[selectedUnits,setSelectedUnits]=useState<string[]>([]),[boxFilter,setBoxFilter]=useState(initialBox?String(initialBox):'');
  const [action,setAction]=useState<Action|null>(null),[quantity,setQuantity]=useState(1),[box,setBox]=useState(1),[kind,setKind]=useState('KIT'),[position,setPosition]=useState<string>(TOOLING_POSITIONS[0]),[reason,setReason]=useState('');
  const [editing,setEditing]=useState<InventoryBlade|'new'|null>(null),[saveError,setSaveError]=useState(''),[saving,setSaving]=useState(false);
  const list=useMemo(()=>blades.filter(b=>[b.model,b.manufacturer,...b.positionSpecs.map(s=>s.specification)].some(v=>v?.toLowerCase().includes(keyword.toLowerCase())) && (filter==='all'||filter==='uncounted'&&!b.stock.registered||filter==='available'&&b.stock.available>0||filter==='inuse'&&b.stock.inUse>0||filter==='maintenance'&&b.stock.maintenance>0) && (!boxFilter||b.units.some(u=>u.currentBox===Number(boxFilter)))),[blades,keyword,filter,boxFilter]);
  const current=blades.find(b=>b.id===selected), units=current?.units.filter(u=>u.state!=='RETIRED')||[];
  const selection=units.filter(u=>selectedUnits.includes(u.id));
  function select(id:string){setSelected(id);setSelectedUnits([]);}
  function open(a:Action){setReason('');setAction(a);setBox(selection[0]?.homeBox || current?.stock.boxes[0] || 1);setQuantity(1);setKind('KIT');}
  async function apply(){if(!current||!action)return;const result=await submit('inventory',{action,bladeId:current.id,units:selection.map(u=>({id:u.id,version:u.version})),quantity,box,kind,position,reason});if(result){setAction(null);setSelectedUnits([]);}}
  async function saveBlade(form:TerminalBladeForm){setSaving(true);setSaveError('');try{const res=await fetch('/api/terminal-tooling/blades'+(form.id?'/'+form.id:''),{method:form.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,compatiblePositions:form.positionSpecs.filter(s=>s.specification.trim()).map(s=>s.position), supplierLinks:[]})});const body=await res.json();if(!res.ok||!body.ok)throw new Error(body.error||'保存失败');setEditing(null);await reload();if(body.blade?.id)select(body.blade.id);}catch(e){setSaveError(e instanceof Error?e.message:'保存失败');}finally{setSaving(false);}}
  return <div className={'tl-inventory'+(mobile?' mobile':'')}>
    <div className="tl-inventory-tools"><label className="tl-search"><Search size={17}/><input value={keyword} placeholder="搜索刀片型号 / 规格" onChange={e=>setKeyword(e.target.value)}/></label><select aria-label="库存状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部库存</option><option value="uncounted">待盘点</option><option value="available">有可用刀片</option><option value="inuse">使用中</option><option value="maintenance">待处理</option></select><select aria-label="按盒子筛选" value={boxFilter} onChange={e=>setBoxFilter(e.target.value)}><option value="">全部盒子</option>{Array.from({length:100},(_,n)=><option key={n} value={n+1}>{boxName(n+1)}</option>)}</select>{canEdit&&<button className="tl-primary" onClick={()=>setEditing('new')}><Plus size={17}/>新增型号</button>}</div>
    <div className="tl-inventory-content"><section className="tl-surface tl-inventory-list"><div className="tl-panel-title"><h3>刀片库 <small>{list.length} 个型号</small></h3><Layers3 size={18}/></div><div className="tl-scroll"><table className="tl-table"><thead><tr><th>刀片型号</th><th>可用整套</th><th>散刀 / 使用中</th><th>位置</th></tr></thead><tbody>{list.map(b=><tr key={b.id} className={b.id===selected?'selected':''} onClick={()=>select(b.id)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')select(b.id);}}><td><b>{b.model}</b><small>{b.manufacturer||'—'}{b.isDraft?' · 资料待完善':''}</small></td><td>{b.stock.registered?<strong>{b.stock.completeKits}<small> 套</small></strong>:<span className="tl-tag amber">待盘点</span>}</td><td>{b.stock.registered?<>{b.stock.loose} 把 / <span className={b.stock.inUse?'tl-blue':''}>{b.stock.inUse} 把</span>{b.stock.incompleteKits>0&&<small className="tl-red">缺件 {b.stock.incompleteKits} 套</small>}</>:'—'}</td><td>{b.stock.boxes.length?b.stock.boxes.map(n=>String(n).padStart(3,'0')).join(' · '):'—'}</td></tr>)}</tbody></table>{!list.length&&<div className="tl-empty"><Search size={30}/><b>未找到刀片</b><span>换个关键词，或清除盒号与状态筛选</span></div>}</div></section>
      {!mobile&&<section className="tl-surface tl-inventory-detail">{current?detail():<div className="tl-empty"><Box size={38}/><b>选择刀片型号</b><span>查看数量、盒子位置和使用状态</span></div>}</section>}
    </div>
    {mobile&&current&&<ToolingDialog title={current.model} subtitle="数量与存放位置" onClose={()=>setSelected('')}>{detail()}</ToolingDialog>}
    {action&&current&&<ToolingDialog title={ACTION_NAMES[action]} subtitle={current.model} onClose={()=>setAction(null)} busy={busy} footer={<><button disabled={busy} onClick={()=>setAction(null)}>取消</button><button className="tl-primary" disabled={busy||(['RETIRE','MAINTENANCE'].includes(action)&&!reason.trim())} onClick={()=>void apply()}><Check size={17}/>{busy?'保存中…':'确认'+(action==='REGISTER'?'登记':'')}</button></>}>
      {['REGISTER','ADD'].includes(action)?<><div className="tl-segment"><button className={kind==='KIT'?'active':''} onClick={()=>setKind('KIT')}>整套刀片</button><button className={kind==='LOOSE'?'active':''} onClick={()=>setKind('LOOSE')}>散刀</button></div>{kind==='LOOSE'&&<label>刀位<select value={position} onChange={e=>setPosition(e.target.value)}>{TOOLING_POSITIONS.filter(p=>current.compatiblePositions.includes(p)).map(p=><option value={p} key={p}>{TOOLING_POSITION_NAMES[p]}</option>)}</select></label>}<div className="tl-grid2"><label>数量（{kind==='KIT'?'套':'把'}）<input type="number" min={action==='REGISTER'?0:1} max={100} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>存放盒号<input type="number" min={1} max={100} value={box} onChange={e=>setBox(Number(e.target.value))}/></label></div>{kind==='KIT'&&<div className="tl-inline-note"><Layers3 size={16}/>{quantity} 套，共 {quantity*4} 把；每套含四个刀位。</div>}</>:<><div className="tl-inline-note">已选 {selection.length} 把：{selection.map(u=>TOOLING_POSITION_NAMES[u.position]).join('、')}</div>{['MOVE','RETURN'].includes(action)&&<label>放入盒号<input type="number" min={1} max={100} value={box} onChange={e=>setBox(Number(e.target.value))}/></label>}{action==='ASSEMBLE'&&<small>确认这四把属于同一套，组合后仍按 4 把实物计数。</small>}{action==='DISASSEMBLE'&&<small>整套关联解除，数量与位置保持不变。</small>}</>}
      <label>{['RETIRE','MAINTENANCE'].includes(action)?'处理原因 *':'备注'}<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label>
    </ToolingDialog>}
    {editing&&<TerminalBladeEditor item={editing==='new'?undefined:editing} readOnly={!canEdit} saving={saving} error={saveError} onClose={()=>setEditing(null)} onSave={saveBlade}/>}
  </div>;
  function detail(){if(!current)return null;return <><div className="tl-detail-head"><div><span className="tl-eyebrow">刀片型号</span><h2>{current.model}</h2><p>{current.manufacturer||'制造商未填写'}</p></div>{canEdit&&<button onClick={()=>setEditing(current)}>编辑规格</button>}</div><div className="tl-stock-metrics"><div><b>{current.stock.registered?current.stock.completeKits:'—'}</b><span>可用整套</span></div><div><b>{current.stock.registered?current.stock.loose:'—'}</b><span>散刀（把）</span></div><div><b className="tl-blue">{current.stock.inUse}</b><span>使用中（把）</span></div><div><b className="tl-amber">{current.stock.maintenance}</b><span>待处理（把）</span></div></div>
    <div className="tl-detail-body tl-scroll"><div className="tl-blade-grid compact">{TOOLING_POSITIONS.map(p=><div key={p} className="tl-blade-position"><small>{TOOLING_POSITION_NAMES[p]}</small><b>{current.positionSpecs.find(s=>s.position===p)?.specification||'待完善'}</b></div>)}</div>
    <div className="tl-panel-title"><h3><MapPin size={17}/> 实物与位置 <small>{units.length} 把</small></h3>{canEdit&&<button className="tl-text" onClick={()=>open(current.stock.registered?'ADD':'REGISTER')}><PackagePlus size={17}/>{current.stock.registered?'补充库存':'首次盘点'}</button>}</div>
    {!current.stock.registered&&<div className="tl-empty"><Archive size={28}/><b>尚未盘点实物</b><span>数量未知；登记整套或散刀后显示盒号。</span>{canEdit&&<button className="tl-primary" onClick={()=>open('REGISTER')}>登记库存</button>}</div>}
    {units.map(u=><label className={'tl-stock-unit '+(selectedUnits.includes(u.id)?'selected':'')} key={u.id}><input type="checkbox" checked={selectedUnits.includes(u.id)} onChange={e=>setSelectedUnits(s=>e.target.checked?[...s,u.id]:s.filter(id=>id!==u.id))}/><div><b>{TOOLING_POSITION_NAMES[u.position]} <small>{u.kit?.code||'散刀'}</small></b><small>{u.state==='AVAILABLE'?boxName(u.currentBox):u.state==='IN_USE'?(u.inUseJob?.actorName||'')+' · '+(u.inUseJob?.contextSnapshot?.equipment||'设备上'):'待维修 / 处理'} · 归属 {boxName(u.homeBox)}</small></div><span className={'tl-tag '+(u.state==='AVAILABLE'?'green':u.state==='IN_USE'?'blue':'amber')}>{TOOLING_STATES[u.state]}</span></label>)}
    {units.length>0&&<button className="tl-text" onClick={()=>setSelectedUnits(s=>s.length===units.length?[]:units.map(u=>u.id))}>{selectedUnits.length===units.length?'取消全选':'选择全部实物'}</button>}
    </div>{canEdit&&<div className="tl-detail-footer tl-wrap"><span>已选 {selection.length} 把</span>{(['RETURN','MOVE','MAINTENANCE','RETIRE','ASSEMBLE','DISASSEMBLE'] as const).map(a=><button key={a} disabled={!selection.length||busy} onClick={()=>open(a)}>{({RETURN:'归还',MOVE:'移盒',MAINTENANCE:'待处理',RETIRE:'停用',ASSEMBLE:'组套',DISASSEMBLE:'拆套'})[a]}</button>)}</div>}</>}
}
