'use client';
import { useMemo, useState } from 'react';
import { Check, Clock3, Layers3, Plus } from 'lucide-react';
import type { ToolingJobDTO } from '@/lib/tooling-worklog-domain';
import { moldPositionName, TOOLING_POSITIONS, TOOLING_POSITION_NAMES, boxName, durationText } from '@/lib/tooling-worklog-domain';
import { ToolingDialog, type Submit, asLocal, asShanghai, jobTitle } from './ToolingShared';

export { NewToolingWork } from './ToolingStartDialog';

export function FinishToolingWork({job,submit,busy,onClose,onDone}:{job:ToolingJobDTO;submit:Submit;busy:boolean;onClose:()=>void;onDone:()=>void}) {
  const usages=job.usages.filter(u=>u.isCurrent).sort((a,b)=>TOOLING_POSITIONS.indexOf(a.position)-TOOLING_POSITIONS.indexOf(b.position)), [result,setResult]=useState('COMPLETED'),[note,setNote]=useState('');
  const [dispositions,setDispositions]=useState(usages.map(u=>({usageId:u.id,disposition:'HOME',box:u.snapshot.homeBox||1})));
  const [moldDisposition,setMoldDisposition]=useState('HOME'),[moldPosition,setMoldPosition]=useState(job.moldUsage?.snapshot.homePosition||1),[restored,setRestored]=useState(true);
  async function finish(){const res=await submit('worklog',{action:'FINISH',jobId:job.id,version:job.version,result,resultNote:note,dispositions,moldDisposition,moldPosition,moldRestored:restored});if(res)onDone();}
  return <ToolingDialog title={job.kind==='TUNING'?'完成调模':'完成协助'} subtitle={jobTitle(job)} onClose={onClose} busy={busy} footer={<><button disabled={busy} onClick={onClose}>继续作业</button><button className="tl-primary" disabled={busy || (result==='INCOMPLETE'&&!note.trim())} onClick={()=>void finish()}><Check size={18}/>{busy?'保存中…':job.kind==='TUNING'?(dispositions.every(d=>d.disposition==='HOME')&&(!job.moldUsage||(moldDisposition==='HOME'&&restored))?'完成并归还':'完成并记录去向'):'结束并记录工时'}</button></>}>
    <div className="tl-segment"><button className={result==='COMPLETED'?'active':''} onClick={()=>setResult('COMPLETED')}>已完成</button><button className={result==='INCOMPLETE'?'active':''} onClick={()=>setResult('INCOMPLETE')}>需继续处理</button></div>
    <label>结果备注{result==='INCOMPLETE'?' *':''}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={result==='INCOMPLETE'?'记录问题与下一步':'记录调整参数或注意事项'} maxLength={2000}/></label>
    {job.moldUsage&&<section className="tl-form-section"><h3><Layers3 size={18}/>专模归还</h3><div className="tl-return-row"><div><b>{job.moldUsage.snapshot.model}</b><small>{moldPositionName(job.moldUsage.snapshot.homePosition)}</small></div><select aria-label="专模去向" value={moldDisposition} onChange={e=>{setMoldDisposition(e.target.value);if(e.target.value==='DEVICE')setRestored(false);}}><option value="HOME">原位归还</option><option value="BOX">放入其他位置</option><option value="DEVICE">留在设备上</option><option value="MAINTENANCE">待维修</option></select>{moldDisposition==='BOX'&&<input aria-label="归还专模位置" type="number" min={1} max={20} value={moldPosition} onChange={e=>setMoldPosition(Number(e.target.value))}/>}</div>{job.toolingMode==='COMBINATION'&&<label className="tl-checkline"><input type="checkbox" checked={restored} disabled={moldDisposition==='DEVICE'} onChange={e=>setRestored(e.target.checked)}/>专模原配刀片已装回</label>}{job.toolingMode==='COMBINATION'&&!restored&&moldDisposition!=='DEVICE'&&<small className="tl-amber">归还后标记为待恢复原配，暂不可领用。</small>}</section>}
    {!!usages.length && <section className="tl-form-section"><h3><Layers3 size={18}/> 刀片去向</h3><button className="tl-text" onClick={()=>setDispositions(d=>d.map(v=>({...v,disposition:'HOME'})))}>全部原盒归位</button>{usages.map(u=>{const d=dispositions.find(v=>v.usageId===u.id)!;return <div key={u.id} className="tl-return-row"><div><b>{TOOLING_POSITION_NAMES[u.position]}</b><small>{u.snapshot.model} · {u.snapshot.homeBox?boxName(u.snapshot.homeBox):'库存未登记'}</small></div><select value={d.disposition} aria-label={TOOLING_POSITION_NAMES[u.position]+'去向'} onChange={e=>setDispositions(ds=>ds.map(v=>v.usageId===u.id?{...v,disposition:e.target.value}:v))}><option value="HOME">原盒归位</option><option value="BOX">放入其他盒</option><option value="DEVICE">仍在设备上</option><option value="MAINTENANCE">待处理 / 维修</option></select>{d.disposition==='BOX' && <input type="number" aria-label="归还盒号" min={1} max={100} value={d.box} onChange={e=>setDispositions(ds=>ds.map(v=>v.usageId===u.id?{...v,box:Number(e.target.value)}:v))}/>}</div>})}</section>}
  </ToolingDialog>;
}

export function CorrectToolingTime({job,submit,busy,onClose,onDone}:{job:ToolingJobDTO;submit:Submit;busy:boolean;onClose:()=>void;onDone:()=>void}){
  const [intervals,setIntervals]=useState(job.segments.filter(s=>s.kind==='WORK'&&s.endedAt).map(s=>({startedAt:asLocal(s.startedAt),endedAt:asLocal(s.endedAt!)}))),[reason,setReason]=useState('');
  const ms=useMemo(()=>intervals.reduce((n,s)=>n+Math.max(0,+new Date(s.endedAt)-+new Date(s.startedAt)),0),[intervals]);
  async function save(){if(intervals.some(s=>!s.startedAt||!s.endedAt))return;const res=await submit('worklog',{action:'CORRECT',jobId:job.id,version:job.version,reason,segments:intervals.map(s=>({startedAt:asShanghai(s.startedAt),endedAt:asShanghai(s.endedAt)}))});if(res)onDone();}
  return <ToolingDialog title="修正有效工时" subtitle={jobTitle(job)} onClose={onClose} busy={busy} footer={<><span><Clock3 size={15}/> {durationText(ms)}</span><button className="tl-primary" disabled={busy||!reason.trim()} onClick={()=>void save()}>保存修正</button></>}>
    {intervals.map((s,i)=><div className="tl-grid2" key={i}><label>开始时间<input type="datetime-local" value={s.startedAt} onChange={e=>setIntervals(v=>v.map((x,n)=>n===i?{...x,startedAt:e.target.value}:x))}/></label><label>结束时间<input type="datetime-local" value={s.endedAt} onChange={e=>setIntervals(v=>v.map((x,n)=>n===i?{...x,endedAt:e.target.value}:x))}/></label><button className="tl-text" disabled={intervals.length===1} onClick={()=>setIntervals(v=>v.filter((_,n)=>n!==i))}>移除此时段</button></div>)}
    <button onClick={()=>setIntervals(v=>[...v,{startedAt:asLocal(job.startedAt),endedAt:asLocal(job.endedAt!)}])}><Plus size={16}/>增加工作时段</button><label>修正原因<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label><small>原始时段保留在操作记录中，工时台账同步更正。</small>
  </ToolingDialog>;
}
