'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, Box, CalendarDays, Check, CheckCircle2, ChevronRight, Clock3, Download, History, Pause, Play, Plus, QrCode, RefreshCw, Search, Settings2, Smartphone, Timer, User, Users, Wrench, X } from 'lucide-react';
import QRCode from 'qrcode';
import type { CurrentUserDTO } from '@/types';
import { AppWorkbenchHeader } from '@/components/layout/AppWorkbenchHeader';
import { TerminalToolingWorkbench } from '@/components/TerminalToolingWorkbench';
import { hasCapability } from '@/lib/department-access';
import { TOOLING_POSITIONS, TOOLING_POSITION_NAMES, TOOLING_STATES, durationText, boxName, segmentTotals, shanghaiDay, type ToolingJobDTO, type ToolingPosition } from '@/lib/tooling-worklog-domain';
import { ToolingDialog, ToolingFeedback, type WorkData, type Catalog, type Submit, stamp, hours, jobTitle } from './ToolingShared';
import { NewToolingWork, FinishToolingWork, CorrectToolingTime } from './ToolingWorkDialogs';
import ToolingInventory from './ToolingInventory';

type Tab='work'|'inventory'|'catalog'|'stats'|'account';
type Pending={endpoint:'worklog'|'inventory';body:Record<string,unknown>};
const EMPTY_CATALOG:Catalog={blades:[],terminals:[],setups:[]};
const ACTION_NAMES:Record<string,string>={START:'开始计时',BACKFILL:'补报工时',PAUSE:'暂停',RESUME:'继续计时',FINISH:'结束作业',SWAP:'更换刀片',CORRECT:'修正时段',HOURS_SYNC:'工时已同步',SAVE_RECIPE:'保存为方案草稿'};
export default function ToolingOperations({user,mobile=false,initialBox}:{user:CurrentUserDTO;mobile?:boolean;initialBox?:number}){
  const [tab,setTab]=useState<Tab>(initialBox?'inventory':'work'),[data,setData]=useState<WorkData|null>(null),[catalog,setCatalog]=useState<Catalog>(EMPTY_CATALOG);
  const [period,setPeriod]=useState(mobile?'week':'day'),[date,setDate]=useState(shanghaiDay(Date.now())),[employeeFilter,setEmployeeFilter]=useState(''),[keyword,setKeyword]=useState(''),[statusFilter,setStatusFilter]=useState('all');
  const [selectedId,setSelectedId]=useState(''),[extraJob,setExtraJob]=useState<ToolingJobDTO|null>(null),[mobileDetail,setMobileDetail]=useState(false);
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState<Pending|null>(null);
  const [dialog,setDialog]=useState<'new'|'lookup'|'assist'|'finish'|'pause'|'swap'|'correct'|'qr'|null>(null),[qr,setQr]=useState(''),[pauseReason,setPauseReason]=useState('等料'),[swapPosition,setSwapPosition]=useState<ToolingPosition>('UPPER_OUTER'),[swapBlade,setSwapBlade]=useState(''),[swapStock,setSwapStock]=useState(''),[swapDisposition,setSwapDisposition]=useState('HOME');
  const busyRef=useRef(false),requestSeq=useRef(0),clockOffset=useRef(0),initialPending=useRef(false);
  const canCreate=hasCapability(user.access,'TERMINAL_TOOLING','CREATE'),canEdit=hasCapability(user.access,'TERMINAL_TOOLING','UPDATE');
  const pendingKey='hm-tooling-pending-v1:'+user.id;
  const query=new URLSearchParams({period,date,...(mobile?{mine:'1'}:employeeFilter?{employeeId:employeeFilter}:{})}).toString();
  const reload=useCallback(async()=>{
    const seq=++requestSeq.current;
    try{
      const [work,inventory,terminals,setups]=await Promise.all(['/worklog?'+query,'/inventory','/terminals','/setups'].map(async path=>{const res=await fetch('/api/terminal-tooling'+path,{cache:'no-store'});const body=await res.json();if(!res.ok||!body.ok)throw new Error(body.error||'资料暂时无法加载');return body;}));
      if(seq!==requestSeq.current)return; setData(work);clockOffset.current=+new Date(work.serverNow)-Date.now();setCatalog({blades:inventory.blades,terminals:terminals.terminals,setups:setups.setups});
    }catch(e){if(seq===requestSeq.current)setError(e instanceof Error?e.message:'加载失败');}finally{if(seq===requestSeq.current)setLoading(false);}
  },[query]);
  useEffect(()=>{void reload();},[reload]);
  useEffect(()=>{const visible=()=>{if(document.visibilityState==='visible')void reload();};window.addEventListener('online',visible);document.addEventListener('visibilitychange',visible);return()=>{window.removeEventListener('online',visible);document.removeEventListener('visibilitychange',visible);};},[reload]);
  useEffect(()=>{if(!data?.active?.id)return;const id=setInterval(()=>void reload(),30000);return()=>clearInterval(id);},[data?.active?.id,reload]);
  useEffect(()=>{if(initialPending.current)return;initialPending.current=true;try{const raw=localStorage.getItem(pendingKey);if(raw)setPending(JSON.parse(raw));}catch{/* storage may be disabled in private browsers */}},[pendingKey]);
  useEffect(()=>{if(!message)return;const id=setTimeout(()=>setMessage(''),4000);return()=>clearTimeout(id);},[message]);
  useEffect(()=>{if(!mobile)return;const back=(e:PopStateEvent)=>{setMobileDetail(!!e.state?.toolingJob);setSelectedId(e.state?.toolingJob||'');setDialog(null);if(e.state?.toolingTab)setTab(e.state.toolingTab);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[mobile]);
  const submit:Submit=async(endpoint,input)=>{
    if(busyRef.current)return null;
    if(pending && !input.key){setError('有一条操作尚未同步，请先重试或取消待同步操作');return null;}
    const body=input.key?input:{...input,key:crypto.randomUUID()};const operation:Pending={endpoint,body};
    busyRef.current=true;setBusy(true);setError('');setPending(operation);try{localStorage.setItem(pendingKey,JSON.stringify(operation));}catch{/* receipt still prevents duplicates while this page remains open */}
    try{const res=await fetch('/api/terminal-tooling/'+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await res.json();
      if(!res.ok||!result.ok){if(res.status>=400&&res.status<500&&res.status!==401){setPending(null);localStorage.removeItem(pendingKey);}throw new Error(result.error||'操作未完成，请重试');}
      setPending(null);try{localStorage.removeItem(pendingKey);}catch{};setMessage('已保存');await reload();return result;
    }catch(e){setError(e instanceof Error?e.message:'网络未连接，操作已暂存，请恢复网络后重试');return null;}finally{busyRef.current=false;setBusy(false);}
  };
  const selected=data?.jobs.find(j=>j.id===selectedId)|| (data?.active?.id===selectedId?data.active:null) || (extraJob?.id===selectedId?extraJob:null) || (!selectedId?data?.jobs[0]:null);
  const dialogJob=selected||data?.active;
  async function selectJob(id:string){setSelectedId(id);if(!data?.jobs.some(j=>j.id===id)&&data?.active?.id!==id){const res=await fetch('/api/terminal-tooling/worklog?id='+encodeURIComponent(id));const body=await res.json();if(body.ok)setExtraJob(body.job);}
    if(mobile){setMobileDetail(true);window.history.pushState({toolingJob:id,toolingTab:tab},'');}}
  async function started(id:string){setDialog(null);await selectJob(id);}
  function closeDetail(){if(mobile){if(window.history.state?.toolingJob)window.history.back();else setMobileDetail(false);}else setSelectedId('');}
  async function showQr(){setDialog('qr');setQr(await QRCode.toDataURL(window.location.origin+'/tooling-mobile',{width:600,margin:2,errorCorrectionLevel:'M',color:{dark:'#17324b',light:'#ffffffff'}}));}
  async function changeJob(action:string,other:Record<string,unknown>={}){if(!dialogJob)return;const res=await submit('worklog',{action,jobId:dialogJob.id,version:dialogJob.version,...other});if(res){setDialog(null);setExtraJob(null);}}
  const jobs=(data?.jobs||[]).filter(j=>(statusFilter==='all'||j.status===statusFilter)&&[jobTitle(j),j.actorName,j.description,j.employeeNo].some(v=>v?.toLowerCase().includes(keyword.toLowerCase())));
  function setMainTab(next:Tab){setTab(next);setMobileDetail(false);setDialog(null);if(next!==tab)void reload();if(mobile)window.history.replaceState({toolingTab:next},'');}
  const footerActions=(job:ToolingJobDTO)=>canCreate && (job.employeeId===user.employeeId||user.laborRole==='ADMIN')?<div className="tl-detail-footer tl-wrap">{['RUNNING','PAUSED'].includes(job.status)?<><button onClick={()=>{setSelectedId(job.id);setDialog('swap');}} disabled={busy||job.kind!=='TUNING'}><Wrench size={17}/>更换刀片</button><button onClick={()=>{setSelectedId(job.id);if(job.status==='PAUSED')void submit('worklog',{action:'RESUME',jobId:job.id,version:job.version});else setDialog('pause');}} disabled={busy}>{job.status==='PAUSED'?<Play size={17}/>:<Pause size={17}/>} {job.status==='PAUSED'?'继续计时':'暂停'}</button><button className="tl-primary" disabled={busy} onClick={()=>{setSelectedId(job.id);setDialog('finish');}}><Check size={18}/>完成作业</button></>:<><button onClick={()=>{setSelectedId(job.id);setDialog('correct');}}>修正时间</button>{job.kind==='TUNING'&&<button className="tl-primary" disabled={busy} onClick={async()=>{const res=await submit('worklog',{action:'SAVE_RECIPE',jobId:job.id,version:job.version});if(res)setMessage('已保存方案草稿，可在电脑端完善并发布');}}><BookOpen size={17}/>保存为方案草稿</button>}</>}</div>:null;
  function detail(job:ToolingJobDTO){return <><div className="tl-detail-head"><div><span className="tl-eyebrow">{job.kind==='TUNING'?'调模记录':job.category} · {job.employeeNo} {job.actorName}</span><h2>{jobTitle(job)}</h2><p>{job.kind==='TUNING'?[job.contextSnapshot.wireRange,job.contextSnapshot.equipment,job.contextSnapshot.mold].filter(Boolean).join(' · ')||'本次条件未填写':job.description}</p></div><span className={'tl-tag '+(job.status==='COMPLETED'?'green':job.status==='RUNNING'?'blue':'amber')}>{TOOLING_STATES[job.status]}</span></div>
    <div className="tl-detail-body tl-scroll"><div className="tl-time-card"><Elapsed job={job} offset={clockOffset.current}/><div><small>开始 {stamp(job.startedAt)}</small><small>{job.endedAt?'结束 '+stamp(job.endedAt):'计时保存在服务器'}</small></div></div>
    {job.kind==='TUNING'&&<><div className="tl-panel-title"><h3>本次四刀位</h3><small>实际使用组合</small></div><div className="tl-blade-grid">{TOOLING_POSITIONS.map(p=>{const u=job.usages.find(v=>v.position===p&&v.isCurrent);return <article className="tl-blade-position" key={p}><small>{TOOLING_POSITION_NAMES[p]}</small><b>{u?.snapshot.model||'未记录'}</b><span>{u?.snapshot.specification||'规格待完善'}</span>{u&&<small>{u.disposition==='DEVICE'?'仍在设备上':u.snapshot.homeBox?boxName(u.snapshot.homeBox):'位置待盘点'}{u.snapshot.kitCode?' · '+u.snapshot.kitCode:''}</small>}</article>})}</div></>}
    {job.resultNote&&<div className="tl-result"><CheckCircle2 size={18}/><p>{job.resultNote}</p></div>}
    <div className="tl-panel-title"><h3><History size={17}/>操作记录</h3><small>{job.ledger.some(l=>l.status!=='VOIDED')?'工时已同步':''}</small></div><ol className="tl-timeline">{job.events.map(e=><li key={e.id}><div><b>{ACTION_NAMES[e.action]||e.action}</b><time>{stamp(e.createdAt)}</time></div><small>{e.actorName}{e.detail.reason?' · '+String(e.detail.reason):''}{e.detail.resultNote?' · '+String(e.detail.resultNote):''}</small></li>)}</ol></div>{footerActions(job)}</>}
  return <ToolingFeedback.Provider value={error}><main className={'tl-app '+(mobile?'tl-mobile':'tl-desktop hm-workbench-root')}>
    {!mobile?<><AppWorkbenchHeader user={user} activeHref="/workspace/terminal-tooling" subtitle="调模记录 · 刀片实物 · 工时统计" menuItems={[{label:'刷新',onSelect:reload}]}/><div className="tl-topbar"><div className="tl-tabs">{([{id:'work',name:'作业台账',icon:Timer},{id:'inventory',name:'刀片库存',icon:Box},{id:'catalog',name:'端子与方案',icon:BookOpen},{id:'stats',name:'工时统计',icon:BarChart3}] as const).map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setMainTab(t.id)}><t.icon size={18}/>{t.name}</button>)}</div><div className="tl-actions"><button onClick={()=>void showQr()}><QrCode size={18}/>手机入口</button><button className="tl-icon" aria-label="刷新数据" onClick={()=>void reload()} disabled={loading}><RefreshCw size={18}/></button>{canCreate&&<button className="tl-primary" onClick={()=>setDialog('new')} disabled={busy||!!data?.active}><Plus size={18}/>开始调模</button>}</div></div></>:<header className="tl-mobile-head">{mobileDetail?<button aria-label="返回之前页面" className="tl-icon" onClick={closeDetail}><ArrowLeft/></button>:<span className="tl-logo">杭</span>}<div><h1>{mobileDetail?'作业详情':tab==='inventory'?'刀片查询':tab==='stats'?'我的记录':tab==='account'?'我的账号':'端子调模'}</h1><small>{user.employee?.name||user.displayName} · {user.employee?.employeeNo||user.username}</small></div><button className="tl-icon" aria-label="刷新数据" onClick={()=>void reload()}><RefreshCw size={20}/></button></header>}
    {message&&<div className="tl-toast" role="status"><CheckCircle2 size={18}/>{message}</div>}
    {error&&<div className="tl-error" role="alert"><span>{error}</span><button aria-label="关闭提示" className="tl-icon" onClick={()=>setError('')}><X size={16}/></button></div>}
    {pending&&<div className="tl-pending"><span>1 条操作待同步</span><button onClick={()=>void submit(pending.endpoint,pending.body)} disabled={busy}>重试同步</button><button onClick={()=>{setPending(null);try{localStorage.removeItem(pendingKey);}catch{}}} disabled={busy}>取消待同步</button><a href={'/login?next='+encodeURIComponent(mobile?'/tooling-mobile':'/workspace/terminal-tooling')}>重新登录</a></div>}
    {loading&&!data?<div className="tl-empty" role="status"><RefreshCw className="spin"/><b>正在加载作业与库存…</b></div>:<>
    {mobile&&mobileDetail?(selected?<section className="tl-surface tl-phone-detail">{detail(selected)}</section>:<div className="tl-empty">正在加载记录…</div>):<>
      {tab==='work'&&(mobile?<div className="tl-mobile-body tl-scroll"><section className="tl-greeting"><span className="tl-eyebrow">扫码即用 · 自动记录</span><h2>{data?.active?'继续今天的作业':'准备好开始了吗'}</h2><p>{date} · {user.employee?.name||user.displayName}</p></section>{data?.active?<section className="tl-active-card" onClick={()=>void selectJob(data.active!.id)}><div><span className="tl-tag blue">{TOOLING_STATES[data.active.status]}</span><h2>{jobTitle(data.active)}</h2></div><Elapsed job={data.active} offset={clockOffset.current}/><button className="tl-primary" onClick={e=>{e.stopPropagation();void selectJob(data.active!.id);}}>继续作业 <ArrowRight size={18}/></button></section>:<button className="tl-start-card" onClick={()=>setDialog(canCreate?'new':'lookup')}><div className="tl-start-icon"><Wrench size={30}/></div><h2>{canCreate?'开始调模':'查端子与刀片'}</h2><span>{canCreate?'查端子 · 选刀片 · 计时':'参考历史组合与存放位置'}</span><ArrowRight/></button>}<div className="tl-mobile-shortcuts"><button disabled={!canCreate||!!data?.active} onClick={()=>setDialog('assist')}><Clock3/><b>协助报工</b></button><button onClick={()=>setMainTab('inventory')}><Box/><b>查刀片位置</b></button></div><div className="tl-panel-title"><h3>{period==='day'?'当日':period==='week'?'本周':'本月'}工时</h3><button className="tl-text" onClick={()=>setMainTab('stats')}>查看记录<ChevronRight size={15}/></button></div><div className="tl-mobile-metrics"><div><b>{hours(data?.summary.tuningMs||0)}<small> h</small></b><span>调模</span></div><div><b>{hours(data?.summary.assistMs||0)}<small> h</small></b><span>协助</span></div><div><b>{data?.summary.count||0}<small> 次</small></b><span>调模结束</span></div></div><div className="tl-panel-title"><h3>最近记录</h3></div>{(data?.jobs||[]).slice(0,5).map(j=><button className="tl-mobile-record" key={j.id} onClick={()=>void selectJob(j.id)}><Timer size={21}/><div><b>{jobTitle(j)}</b><small>{stamp(j.startedAt)} · {TOOLING_STATES[j.status]}</small></div><strong>{durationText(j.workMs)}</strong><ChevronRight size={17}/></button>)}</div>:<>
        <div className="tl-kpis"><article><span>调模工时</span><b>{hours(data?.summary.tuningMs||0)}<small> h</small></b></article><article><span>协助工时</span><b>{hours(data?.summary.assistMs||0)}<small> h</small></b></article><article><span>结束调模</span><b>{data?.summary.count||0}<small> 次</small></b></article><article><span>进行中 / 暂停</span><b>{data?.summary.ongoing||0}<small> 项</small></b></article></div>{filters()}
        <div className="tl-work-layout"><section className="tl-surface tl-record-list"><div className="tl-panel-title"><h3>作业记录 <small>{jobs.length} 项</small></h3>{canCreate&&<button className="tl-text" disabled={!!data?.active} onClick={()=>setDialog('assist')}><Plus size={16}/>协助报工</button>}</div><div className="tl-scroll"><table className="tl-table"><thead><tr><th>端子 / 工作内容</th><th>员工</th><th>有效工时</th><th>状态</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id} className={j.id===selected?.id?'selected':''} tabIndex={0} onClick={()=>void selectJob(j.id)} onKeyDown={e=>{if(e.key==='Enter')void selectJob(j.id);}}><td><b>{jobTitle(j)}</b><small>{stamp(j.startedAt)} · {j.kind==='TUNING'?'调模':j.description}</small></td><td>{j.actorName}<small>{j.employeeNo}</small></td><td><b>{durationText(j.period.workMs)}</b></td><td><span className={'tl-tag '+(j.status==='COMPLETED'?'green':j.status==='RUNNING'?'blue':'amber')}>{TOOLING_STATES[j.status]}</span></td></tr>)}</tbody></table>{!jobs.length&&<div className="tl-empty"><Timer size={32}/><b>当前条件没有作业记录</b><span>调整日期，或开始第一项调模</span></div>}</div></section><section className="tl-surface tl-record-detail">{selected?detail(selected):<div className="tl-empty"><Wrench size={34}/><b>选择一条作业</b><span>查看实际刀位、时间与记录</span></div>}</section></div></>)}
      {tab==='inventory'&&<ToolingInventory blades={catalog.blades} submit={submit} busy={busy} canEdit={canEdit} reload={reload} mobile={mobile} initialBox={initialBox}/>}
      {tab==='catalog'&&!mobile&&<div className="tl-catalog"><TerminalToolingWorkbench user={user} embedded/></div>}
      {tab==='stats'&&<>{filters()}<section className="tl-stats-content tl-scroll"><div className="tl-kpis"><article><span>有效工时</span><b>{hours((data?.summary.tuningMs||0)+(data?.summary.assistMs||0))}<small> h</small></b></article><article><span>调模工时</span><b>{hours(data?.summary.tuningMs||0)}<small> h</small></b></article><article><span>协助工时</span><b>{hours(data?.summary.assistMs||0)}<small> h</small></b></article><article><span>暂停时长</span><b>{hours(data?.summary.waitMs||0)}<small> h</small></b></article></div><section className="tl-surface tl-chart"><div className="tl-panel-title"><h3>工时分布</h3><span className="tl-legend"><i/>调模 <i/>协助</span></div>{data?.daily.map(d=><div className="tl-chart-row" key={d.date}><span>{d.date.slice(5)}</span><div><i style={{width:100*d.tuningMs/Math.max(3600000,...data.daily.map(v=>v.workMs))+'%'}}/><i style={{width:100*d.assistMs/Math.max(3600000,...data.daily.map(v=>v.workMs))+'%'}}/></div><b>{hours(d.workMs)} h</b></div>)}{!data?.daily.length&&<div className="tl-empty">当前周期暂无工时</div>}</section><section className="tl-surface"><div className="tl-panel-title"><h3>{mobile?'本期记录':'员工工时明细'}</h3><a className="tl-button" href={'/api/terminal-tooling/worklog/export?'+query}><Download size={16}/>导出 CSV</a></div>{mobile?jobs.map(j=><button className="tl-mobile-record" key={j.id} onClick={()=>void selectJob(j.id)}><div><b>{jobTitle(j)}</b><small>{stamp(j.startedAt)} · {TOOLING_STATES[j.status]}</small></div><strong>{durationText(j.period.workMs)}</strong><ChevronRight size={16}/></button>):<table className="tl-table"><thead><tr><th>员工</th><th>结束调模</th><th>调模工时</th><th>协助工时</th><th>暂停时长</th><th>有效工时</th></tr></thead><tbody>{data?.employees.map(p=><tr key={p.employeeId} onClick={()=>{setEmployeeFilter(p.employeeId);setMainTab('work');}}><td><b>{p.name}</b><small>{p.employeeNo}</small></td><td>{p.count} 次</td><td>{hours(p.tuningMs)} h</td><td>{hours(p.assistMs)} h</td><td>{hours(p.waitMs)} h</td><td><b>{hours(p.tuningMs+p.assistMs)} h</b><ChevronRight size={14}/></td></tr>)}</tbody></table>}</section></section></>}
      {tab==='account'&&mobile&&<section className="tl-mobile-body tl-scroll"><div className="tl-surface tl-account"><User size={40}/><h2>{user.employee?.name||user.displayName}</h2><p>{user.employee?.employeeNo||user.username} · {user.employee?.department||'部门未填写'}</p><span className="tl-tag blue">{canCreate?'调模协同':'资料只读'}</span></div><button className="tl-mobile-record" onClick={()=>setMainTab('stats')}><History/><b>我的作业与工时</b><ChevronRight/></button><button className="tl-mobile-record" onClick={()=>void showQr()}><QrCode/><b>手机调模入口</b><ChevronRight/></button><a className="tl-mobile-record" href="/change-password?next=%2Ftooling-mobile"><Settings2/><b>修改密码</b><ChevronRight/></a><button className="tl-mobile-record" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.href='/login?next=%2Ftooling-mobile';}}>退出登录</button></section>}
    </>}
    </>}
    {mobile&&!mobileDetail&&<nav className="tl-mobile-nav">{([{id:'work',name:'作业',icon:Wrench},{id:'inventory',name:'找刀',icon:Box},{id:'stats',name:'记录',icon:History},{id:'account',name:'我的',icon:User}] as const).map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setMainTab(t.id)}><t.icon size={21}/><span>{t.name}</span></button>)}</nav>}
    {(dialog==='new'||dialog==='lookup'||dialog==='assist')&&<NewToolingWork catalog={catalog} employeeId={user.employeeId} assist={dialog==='assist'} readOnly={dialog==='lookup'||!canCreate} submit={submit} busy={busy} onClose={()=>setDialog(null)} onStarted={id=>void started(id)}/>}
    {dialog==='finish'&&dialogJob&&<FinishToolingWork job={dialogJob} submit={submit} busy={busy} onClose={()=>setDialog(null)} onDone={()=>{setDialog(null);setExtraJob(null);}}/>}
    {dialog==='correct'&&selected&&<CorrectToolingTime job={selected} submit={submit} busy={busy} onClose={()=>setDialog(null)} onDone={()=>{setDialog(null);void selectJob(selected.id);}}/>}
    {dialog==='pause'&&dialogJob&&<ToolingDialog title="暂停计时" subtitle={jobTitle(dialogJob)} busy={busy} onClose={()=>setDialog(null)} footer={<button className="tl-primary" disabled={busy} onClick={()=>void changeJob('PAUSE',{reason:pauseReason})}><Pause size={17}/>确认暂停</button>}><label>暂停原因<select value={pauseReason} onChange={e=>setPauseReason(e.target.value)}>{['等料','找刀 / 等刀','设备异常','临时协助','休息','其他'].map(r=><option key={r}>{r}</option>)}</select></label></ToolingDialog>}
    {dialog==='swap'&&dialogJob&&<ToolingDialog title="更换单个刀位" subtitle={jobTitle(dialogJob)} busy={busy} onClose={()=>setDialog(null)} footer={<button className="tl-primary" disabled={busy||!swapBlade} onClick={()=>void changeJob('SWAP',{position:swapPosition,bladeId:swapBlade,stockId:swapStock,disposition:swapDisposition})}><Check size={17}/>确认更换</button>}><label>刀位<select value={swapPosition} onChange={e=>{setSwapPosition(e.target.value as ToolingPosition);setSwapBlade('');setSwapStock('');}}>{TOOLING_POSITIONS.map(p=><option value={p} key={p}>{TOOLING_POSITION_NAMES[p]}</option>)}</select></label><label>原刀片去向<select value={swapDisposition} onChange={e=>setSwapDisposition(e.target.value)}><option value="HOME">原盒归位</option><option value="MAINTENANCE">待维修 / 处理</option></select></label><label>新刀片型号<select value={swapBlade} onChange={e=>{setSwapBlade(e.target.value);setSwapStock('');}}><option value="">请选择</option>{catalog.blades.filter(b=>b.isActive&&b.compatiblePositions.includes(swapPosition)).map(b=><option key={b.id} value={b.id}>{b.model}</option>)}</select></label><label>实物位置<select value={swapStock} onChange={e=>setSwapStock(e.target.value)}><option value="">{catalog.blades.find(b=>b.id===swapBlade)?.stock.registered?'选择可用刀片':'库存待盘点'}</option>{catalog.blades.find(b=>b.id===swapBlade)?.units.filter(u=>u.position===swapPosition&&u.state==='AVAILABLE').map(u=><option key={u.id} value={u.id}>{boxName(u.currentBox)} · {u.kit?.code||'散刀'}</option>)}</select></label></ToolingDialog>}
    {dialog==='qr'&&<ToolingDialog title="手机扫码调模" subtitle="登录自己的员工账号，查刀片、记录作业" onClose={()=>setDialog(null)} footer={qr?<a className="tl-button tl-primary" download="手机调模入口.png" href={qr}><Download size={18}/>下载二维码</a>:null}><div className="tl-qr">{qr&&<img src={qr} alt="手机调模入口二维码" width={260} height={260}/>}<b>端子调模 · 杭连</b><span>保存二维码，张贴在调模工位</span><a href="/tooling-mobile" target="_blank" rel="noreferrer"><Smartphone size={17}/>打开手机版</a></div></ToolingDialog>}
  </main></ToolingFeedback.Provider>;
  function filters(){return <div className="tl-filters"><div className="tl-segment">{(['day','week','month'] as const).map((p,i)=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{['日','周','月'][i]}</button>)}</div><label className="tl-date"><CalendarDays size={17}/><input aria-label="统计日期" type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label>{!mobile&&<><label className="tl-search"><Search size={17}/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索端子型号、员工或工作内容"/></label><select aria-label="筛选作业状态" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">全部状态</option>{['RUNNING','PAUSED','COMPLETED','INCOMPLETE'].map(s=><option key={s} value={s}>{TOOLING_STATES[s]}</option>)}</select>{employeeFilter&&<button onClick={()=>setEmployeeFilter('')}><X size={15}/>清除员工筛选</button>}</>}</div>}
}
function Elapsed({job,offset}:{job:ToolingJobDTO;offset:number}){const [now,setNow]=useState(Date.now());useEffect(()=>{if(job.endedAt)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[job.endedAt]);const total=segmentTotals(job.segments,new Date(job.endedAt||now+offset));return <div className="tl-elapsed"><span>{job.kind==='TUNING'?'有效调模':'有效协助'}</span><strong>{durationText(total.workMs)}</strong><small>暂停 {durationText(total.waitMs)}</small></div>;}
