'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, GitCompareArrows, RefreshCw, Search } from 'lucide-react';
import { SampleDialog, sampleRequest, sampleStamp } from './sample/SampleBranchControls';
import '@/app/sample-branches.css';
import '@/app/sample-planning-warehouse.css';
import '@/app/sample-unified-workbench.css';
import '@/app/connector-conflicts.css';
type Values = { model?:string|null; outerPeelMm?:string|null; innerPeelMm?:string|null; insertionLengthMm?:string|null; remark?:string|null };
type Conflict = { id:string; taskId:string; model:string; positionLabel:string|null; product:{specification:string;customerName:string;taskCode:string}; candidate:Values; original:Array<{id:string;version:number;values:Values}>; current:Array<{id:string;version:number;values:Values}>; currentSignature:string; version:number; status:string; resolution:string|null; resolvedByName:string|null; resolvedAt:string|null; createdAt:string; sampleStatus:string };
const fields: Array<[keyof Values,string]> = [['model','连接器型号'],['outerPeelMm','外剥皮 / mm'],['innerPeelMm','内剥皮 / mm'],['insertionLengthMm','入长 / mm'],['remark','备注']];
const actions = { DISCARD:'删除本次重复，保留原参数', REPLACE:'采用本次参数，覆盖当前版本', KEEP_SEPARATE:'保留两份，登记为不同位置' };
export default function ConnectorConflictPanel({onCountChanged}:{onCountChanged:(count:number)=>void}) {
  const [items,setItems]=useState<Conflict[]>([]),[selected,setSelected]=useState<Conflict|null>(null),[status,setStatus]=useState('PENDING'),[keyword,setKeyword]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[pages,setPages]=useState(1),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[action,setAction]=useState(''),[position,setPosition]=useState(''),[result,setResult]=useState('');
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(keyword.trim());setPage(1);},250);return()=>clearTimeout(timer);},[keyword]);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');sampleRequest(`/api/connector-parameters/conflicts?${new URLSearchParams({status,keyword:query,page:String(page)})}`,{signal:controller.signal}).then(body=>{if(controller.signal.aborted)return;setItems(body.items);setTotal(body.total);setPages(body.totalPages);if(body.page && body.page!==page)setPage(body.page);onCountChanged(body.pending);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[status,query,page,refresh,onCountChanged]);
  async function save(){if(!selected||!action)return;setSaving(true);setError('');try{await sampleRequest(`/api/connector-parameters/conflicts/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,expectedVersion:selected.version,currentSignature:selected.currentSignature,positionLabel:position})});setResult(action==='DISCARD'?'本次重复已移出待处理，样品原始记录保留':'参数已处理，原版本保留在历史记录');setSelected(null);setRefresh(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'处理失败');}finally{setSaving(false);}}
  return <section className="cc-workbench">
    <header><div><small>样品资料整理</small><h2>参数待处理 <span>{total}</span></h2><p>样品正常完成后，在这里对比差异并处理重复参数。</p></div><button onClick={()=>{setRefresh(v=>v+1);setResult('');}} disabled={loading}><RefreshCw size={16}/>刷新</button></header>
    <div className="cc-filters"><nav>{[['PENDING','待处理'],['RESOLVED','处理记录']].map(([value,label])=><button key={value} className={status===value?'active':''} onClick={()=>{setStatus(value);setPage(1);}}>{label}</button>)}</nav><label><Search size={16}/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索连接器或产品型号" aria-label="搜索参数差异"/></label><small>{loading?'正在读取…':`共 ${total} 项`}</small></div>
    {error&&!selected&&<div className="cc-error" role="alert">{error}<button onClick={()=>setRefresh(v=>v+1)}>重试</button></div>}{result&&<div className="cc-success" role="status"><CheckCircle2 size={16}/>{result}</div>}
    <div className="cc-list" tabIndex={0}><table><thead><tr><th>连接器 / 位置</th><th>产品 / 来源样品</th><th>本次参数</th><th>状态</th><th>记录时间</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.model}</strong><small>{item.positionLabel||'未标明位置'}</small></td><td><strong>{item.product.specification}</strong><small>{item.product.customerName} · {item.product.taskCode}</small></td><td><span>外剥 {item.candidate.outerPeelMm||'—'} · 内剥 {item.candidate.innerPeelMm||'—'} · 入长 {item.candidate.insertionLengthMm||'—'}</span></td><td><span className={`cc-state ${item.status==='RESOLVED'?'resolved':''}`}>{item.status==='RESOLVED'?'已处理':'参数差异'}</span><small>{item.status==='RESOLVED'?actions[item.resolution as keyof typeof actions]:item.sampleStatus==='COMPLETED'?'样品已完成':'不影响样品完成'}</small></td><td>{sampleStamp(item.resolvedAt||item.createdAt)}<small>{item.resolvedByName||'整包审核同步'}</small></td><td><button onClick={()=>{setSelected(item);setAction('');setPosition('');setError('');}}><GitCompareArrows size={15}/>{item.status==='RESOLVED'?'查看记录':'对比处理'}</button></td></tr>)}</tbody></table>{!loading&&!error&&!items.length&&<div className="cc-empty"><CheckCircle2 size={34}/><strong>{status==='PENDING'?'当前没有待处理参数':'还没有处理记录'}</strong><p>样品中的参数差异会自动集中到这里。</p></div>}</div>
    <footer><span>样品快照与历史版本完整保留</span><div><button disabled={page<=1||loading} onClick={()=>setPage(v=>v-1)}>上一页</button><b>{page} / {pages}</b><button disabled={page>=pages||loading} onClick={()=>setPage(v=>v+1)}>下一页</button></div></footer>
    {selected&&<SampleDialog wide title={selected.status==='RESOLVED'?'参数处理记录':'对比连接器参数'} busy={saving} onClose={()=>{setSelected(null);setError('');}}><section className="cc-comparison"><header><div><small>{selected.product.customerName} · {selected.positionLabel||'未标明位置'}</small><h2>{selected.product.specification}</h2><p>{selected.product.taskCode} · 样品原始资料已保留</p></div><Link href={`/weekly-plan-center?branch=samples&taskId=${selected.taskId}`}>查看样品<ArrowRight size={15}/></Link></header><div className="cc-compare-scroll"><table><thead><tr><th>参数字段</th><th>{selected.status==='RESOLVED'?'发现重复时的原参数':'当前正式参数'}</th><th>本次样品参数</th></tr></thead><tbody>{fields.map(([key,label])=>{const current=(selected.status==='RESOLVED'?selected.original:selected.current).map(c=>c.values[key]||'—').join(' / ')||'无当前参数';const candidate=selected.candidate[key]||'—';return <tr key={key} className={current!==candidate?'different':''}><th>{label}</th><td>{current}</td><td>{candidate}</td></tr>;})}</tbody></table></div>{selected.status==='PENDING'?<fieldset className="cc-decisions"><legend>选择处理方式</legend>{Object.entries(actions).map(([value,label])=><label key={value} className={action===value?'active':''}><input type="radio" name="parameter-resolution" checked={action===value} disabled={saving} onChange={()=>setAction(value)}/><span><strong>{label}</strong><small>{value==='DISCARD'?'移除本次待处理项，保留样品采集快照与现有参数。':value==='REPLACE'?'仅更新此产品、此位置的参数关联，原版本进入历史。':'同一型号可用于不同位置，填写位置后分别保留。'}</small></span></label>)}{action==='KEEP_SEPARATE'&&<label>新的位置<input type="text" aria-label="新的参数位置" value={position} maxLength={160} onChange={e=>setPosition(e.target.value)} placeholder="例如 B 端"/></label>}</fieldset>:<div className="cc-resolved"><CheckCircle2 size={20}/><span><strong>{actions[selected.resolution as keyof typeof actions]}</strong><small>{selected.resolvedByName} · {sampleStamp(selected.resolvedAt)}</small></span></div>}{error&&<div className="cc-error" role="alert">{error}<button disabled={saving} onClick={()=>{setSelected(null);setRefresh(v=>v+1);}}>刷新对比</button></div>}</section><footer><span>本次操作不会改变样品完成状态或再次转仓。</span><button disabled={saving} onClick={()=>setSelected(null)}>关闭</button>{selected.status==='PENDING'&&<button className="sb-primary" disabled={saving||!action||(action==='KEEP_SEPARATE'&&!position.trim())} onClick={()=>void save()}>{saving?'处理中…':'确认处理'}</button>}</footer></SampleDialog>}
  </section>;
}
