"use client";
import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { ArrowRight, Check, ClipboardCheck, FileCheck2, FileSpreadsheet, Layers3, PackageCheck, Plus, RefreshCw, Search, Settings2, ShieldCheck, Upload, X } from "lucide-react";
import { AppWorkbenchHeader } from "@/components/layout/AppWorkbenchHeader";
import { PurchaseToast } from "@/components/purchasing/PurchaseFeedback";
import type { CurrentUserDTO } from "@/types";
import type { QfWorkbench } from "@/lib/quality-fixture-queries";
import { QF_STATUS, inferBomMapping, type BomMapping, type BomRow, type BomSheet, type DrawingEvidence } from "@/lib/quality-fixture-domain";
import { pcCents, pcMoney } from "@/lib/purchasing-domain";

const views = [{ id: "overview", label: "质量准备总览" }, { id: "plans", label: "计划 · 资料准备" }, { id: "review", label: "两级审核" }, { id: "library", label: "图纸资料档案" }, { id: "fixtures", label: "治具库" }, { id: "stock", label: "库存与领还" }, { id: "production", label: "生产提示" }];
type Draft = { id?: string; version?: number; libraryItemId: string; revision: string; needFixture: boolean | null; parallelCount: number; spareCount: number; drawingFileIds: string[]; bomFileId: string | null; bomMapping: BomMapping | null; bomRows: BomRow[]; bomConfirmed: boolean };
type Modal = { kind: string; fixtureId?: string; stockId?: string; connector?: { model: string; manufacturer: string }; group?: QfWorkbench["readiness"]["groups"][number] };
const time = (s?: string | null) => s ? new Date(s).toLocaleString("zh-CN", { hour12: false }) : "—";
const eventLabel = (type: string, action: string) => type === "STOCK" ? ({ OPENING: "期初登记", RESERVE: "预留", RELEASE: "释放预留", ISSUE: "领用", RETURN: "归还", HOLD: "转待验证", VERIFY: "验证通过", REPAIR: "送修", REPAIRED: "维修返回", SCRAP: "报废", ADJUST: "盘点调整", RECEIVE: "采购验收入库" } as Record<string,string>)[action] || action : ({ SAVE: "保存资料", SUBMIT: "提交主管初审", APPROVE: "审核通过", RETURN: "退回完善", REVOKE: "撤销批准", CONTINUE_OLD_VERSION: "设置旧版沿用范围", BIND_WORK_ORDERS: "指定计划资料版本", CONFIRM_SPECIFICATION: "确认对插关系", CREATE_PURCHASE: "提交治具申购", SAVE_SETTINGS: "更新审核负责人", UPLOAD_DRAWING: "上传图纸" } as Record<string,string>)[action] || action;
const statusClass = (s: string) => ["APPROVED"].includes(s) ? "good" : ["REVOKED", "RETURNED"].includes(s) ? "bad" : "warn";
function Badge({ status }: { status: string }) { return <span className={"qf-badge " + statusClass(status)}>{QF_STATUS[status] || "资料待完善"}</span>; }
function Empty({ children }: { children: ReactNode }) { return <div className="qf-empty"><Layers3 size={30} /><p>{children}</p></div>; }
async function response<T>(r: Response): Promise<T> { const b = await r.json(); if (!r.ok || !b.ok) throw new Error(b.error || "操作失败，请重试"); return b.data as T; }

export default function QualityFixtureWorkbench({ user, initialData, initialView }: { user: CurrentUserDTO; initialData: QfWorkbench; initialView: string }) {
  const [data, setData] = useState(initialData), [view, setView] = useState(initialView), [productId, setProductId] = useState(initialData.product?.id || ""), [packageId, setPackageId] = useState("");
  const [search, setSearch] = useState(""), [page, setPage] = useState(1), [busy, setBusy] = useState(false), [loading, setLoading] = useState(false);
  const [error, setError] = useState(""), [message, setMessage] = useState(""), [tab, setTab] = useState("docs");
  const [draft, setDraft] = useState<Draft | null>(null), [sheets, setSheets] = useState<BomSheet[]>([]), [modal, setModal] = useState<Modal | null>(null), [form, setForm] = useState<Record<string, string>>({});
  const [supervisors, setSupervisors] = useState<string[]>([]), [qualities, setQualities] = useState<string[]>([]), [selectedOrders, setSelectedOrders] = useState<string[]>([]), [checked, setChecked] = useState(false);
  const busyRef = useRef(false), requestRef = useRef<{ body: string; key: string } | null>(null), modalRef = useRef<HTMLElement>(null), priorFocus = useRef<HTMLElement | null>(null);
  const closeMessage = useCallback(() => setMessage(""), []);
  const query = useCallback(() => new URLSearchParams({ view, product: productId, package: packageId, q: search, page: String(page) }), [view, productId, packageId, search, page]);
  const refresh = useCallback(async () => { const d = await fetch("/api/quality-fixtures?" + query(), { cache: "no-store" }).then(response<QfWorkbench>); setData(d); return d; }, [query]);
  useEffect(() => {
    const abort = new AbortController(); const t = setTimeout(() => {
      setLoading(true); fetch("/api/quality-fixtures?" + query(), { signal: abort.signal }).then(response<QfWorkbench>).then(d => { setData(d); setChecked(false); })
        .catch(e => { if (e.name !== "AbortError") setError(e.message); }).finally(() => { if (!abort.signal.aborted) setLoading(false); });
    }, 150); return () => { clearTimeout(t); abort.abort(); };
  }, [query]);
  const overlayOpen = !!draft || !!modal;
  useEffect(() => {
    if (!overlayOpen) return;
    priorFocus.current = document.activeElement as HTMLElement;
    modalRef.current?.querySelector<HTMLElement>("button,input,select")?.focus();
    const before = document.body.style.overflow; document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = before; priorFocus.current?.focus(); };
  }, [overlayOpen]);
  async function mutate<T = unknown>(body: Record<string, unknown>, notice: string, reload = true): Promise<T> {
    const text = JSON.stringify(body);
    if (requestRef.current?.body !== text) requestRef.current = { body: text, key: crypto.randomUUID() };
    const result = await fetch("/api/quality-fixtures", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": requestRef.current.key }, body: text }).then(response<T>);
    requestRef.current = null; if (notice) setMessage(notice); if (reload) await refresh(); return result;
  }
  async function act(fn: () => Promise<unknown>) {
    if (busyRef.current) return;
    busyRef.current = true; setBusy(true); setError("");
    try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : "操作失败，请重试"); }
    finally { busyRef.current = false; setBusy(false); }
  }
  function selectProduct(id: string) { setProductId(id); setPackageId(""); setTab(view === "production" ? "orders" : "docs"); setSelectedOrders([]); }
  function open(kind: string, extra: Partial<Modal> = {}, initial: Record<string, string> = {}) {
    setError(""); setChecked(false); setForm(initial); setModal({ kind, ...extra });
    if (kind === "settings") { setSupervisors(data.settings?.supervisorIds || []); setQualities(data.settings?.qualityIds || []); }
  }
  function edit() {
    if (!data.product) return;
    const p = data.chosen;
    setSheets((data.bom?.sheets || []) as unknown as BomSheet[]);
    setDraft({ id: p?.id, version: p?.version, libraryItemId: data.product.id, revision: p?.revision || "A",
      needFixture: p?.needFixture ?? null, parallelCount: p?.parallelCount || 1, spareCount: p?.spareCount || 0,
      drawingFileIds: p ? (p.drawingFiles as unknown as DrawingEvidence[]).map(f => f.id) : data.product.files.slice(0, 1).map(f => f.id),
      bomFileId: p?.bomFileId || null, bomMapping: (p?.bomMapping || null) as unknown as BomMapping | null,
      bomRows: (p?.bomRows || []) as unknown as BomRow[], bomConfirmed: p?.bomConfirmed || false }); setError("");
  }
  async function saveDraft(d: Draft) {
    const saved = await mutate<{ id: string; version: number }>({ action: "SAVE_PACKAGE", ...d }, "资料草稿已保存", false);
    const next = { ...d, id: saved.id, version: saved.version };
    setDraft(next); await refresh(); return next;
  }
  async function upload(file: File, kind: "drawing" | "bom") {
    if (!draft) return;
    await act(async () => {
      let d = draft;
      if (kind === "bom") d = await saveDraft(d);
      const body = new FormData(); body.set("file", file); body.set("kind", kind); body.set("product", d.libraryItemId); body.set("package", d.id || "");
      const r = await fetch("/api/quality-fixtures/files", { method: "POST", body }).then(response<{ id: string; sheets?: BomSheet[]; mapping?: BomMapping }>);
      if (kind === "bom") { setSheets(r.sheets!); setDraft({ ...d, bomFileId: r.id, bomMapping: r.mapping!, bomRows: [], bomConfirmed: false }); }
      else setDraft({ ...d, drawingFileIds: [r.id] });
      await refresh(); setMessage(kind === "bom" ? "BOM 已上传，请核对表头并识别连接器" : "图纸已上传，请保存受审资料");
    });
  }
  function field(label: string, key: string, type = "text", placeholder = "") {
    return <label className="qf-field">{label}<input type={type} value={form[key] || ""} placeholder={placeholder} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>;
  }
  const chosen = data.chosen, product = data.product, fixture = data.fixtures.find(f => f.id === modal?.fixtureId), stock = fixture?.item.balances.find(b => b.id === modal?.stockId);
  const reviewCounts = data.statusCounts.reduce((n, r) => n + (["SUPERVISOR", "QUALITY"].includes(r.status) ? r._count : 0), 0);
  const docs = (chosen?.drawingFiles || []) as unknown as DrawingEvidence[];
  const rows = (chosen?.bomRows || []) as unknown as BomRow[];
  async function submitModal() {
    if (!modal) return;
    await act(async () => {
      if (modal.kind === "settings") await mutate({ action: "SAVE_SETTINGS", version: data.settings?.version, supervisorIds: supervisors, qualityIds: qualities }, "两级审核负责人已保存");
      if (modal.kind === "mapping") await mutate({ action: "SAVE_MAPPING", ...form, fixtureId: form.fixtureId || undefined, assemblyRequired: form.assemblyRequired === "1" }, "连接器与对插件关系已确认");
      if (modal.kind === "purchase") await mutate({ action: "CREATE_FIXTURE_PURCHASE", packageId: modal.group ? chosen?.id : undefined, version: modal.group ? chosen?.version : undefined, fixtureId: modal.group?.fixtureId || modal.fixtureId, reason: form.reason,
        quantity: Number(form.quantity), estimateCents: pcCents(form.estimate), needDate: form.needDate, urgency: form.urgency || "NORMAL" }, "治具申购已进入杭连采购审批");
      if (["RETURN", "REVOKE", "CONTINUE_OLD_VERSION"].includes(modal.kind)) await mutate({ action: modal.kind, id: chosen?.id, version: chosen?.version, reason: form.reason, workOrderIds: selectedOrders }, "资料版本状态已更新");
      if (modal.kind === "stock") await mutate({ action: "STOCK", ...form, id: stock?.id, version: stock?.version, fixtureId: fixture?.id,
        quantity: Number(form.quantity), fitConfirmed: form.fitConfirmed === "1", continuityConfirmed: form.continuityConfirmed === "1" }, "治具库存与履历已更新");
      if (modal.kind === "template") { await mutate({ action: "SAVE_TEMPLATE", name: form.name, mapping: draft?.bomMapping }, "BOM 表头模板已保存"); }
      setModal(null);
    });
  }
  function closeOverlay() { if (busy) return; if (modal) setModal(null); else if (draft && window.confirm("关闭将丢弃尚未保存的编辑，已保存的资料草稿会保留。确定关闭？")) setDraft(null); }
  const modalTitle = modal?.kind === "settings" ? "主管初审 / 质量复审设置" : modal?.kind === "mapping" ? "确认连接器与对插件" : modal?.kind === "purchase" ? "治具专用申购" : modal?.kind === "stock" ? "治具库存操作" : modal?.kind === "template" ? "保存表头模板" : modal?.kind === "RETURN" ? "退回资料" : modal?.kind === "REVOKE" ? "撤销资料批准" : "指定旧版本沿用范围";
  return <div className="hm-workbench-root pc-shell qf-shell">
    <AppWorkbenchHeader user={user} activeHref="/workspace/quality-fixtures" subtitle="质量准备 · 导通治具" hideHeader menuItems={[]} />
    <header className="qf-page-header"><div><span className="qf-eyebrow">杭连 · 生产质量准备</span><h1><ShieldCheck size={26} />资料与治具工作台</h1><p>把正确的资料、合适的对插件，交到生产现场。</p></div>
      <div className="qf-actions"><button disabled={loading || busy} onClick={() => act(refresh)} aria-label="刷新"><RefreshCw size={16} /></button><button onClick={() => open("settings")}><Settings2 size={16} />审核设置</button><Link className="qf-button qf-primary" href="/workspace/purchases?source=FIXTURE"><PackageCheck size={16} />治具采购<ArrowRight size={15} /></Link></div></header>
    <nav className="qf-tabs" aria-label="质量准备导航">{views.map(v => <button key={v.id} aria-current={view === v.id ? "page" : undefined} onClick={() => { setView(v.id); setTab(v.id === "production" ? "orders" : "docs"); setPage(1); setSearch(""); }}>{v.label}{v.id === "review" && reviewCounts > 0 && <b>{reviewCounts}</b>}</button>)}</nav>
    <PurchaseToast message={message} close={closeMessage} />
    {error && !draft && !modal && <div className="qf-error" role="alert">{error}<button onClick={() => setError("")} aria-label="关闭错误"><X size={16} /></button></div>}
    {view === "overview" ? <main className="qf-overview">
      <section className="qf-hero"><div><span className="qf-eyebrow">开工前，把资料核对清楚</span><h2>资料审核守住质量，<br />治具准备并行推进。</h2><p>主管初审、质量复审通过后即可打印工单。治具短缺持续提示，补齐过程自动跟踪。</p><button className="qf-primary" onClick={() => setView("plans")}>开始准备资料 <ArrowRight size={16} /></button></div><div className="qf-hero-steps">{[["01", "计划上传", "图纸 · Excel BOM"], ["02", "主管初审", "完整性与生产需求"], ["03", "质量复审", "版本与连接器清单"], ["04", "工单打印", "缺具提示持续保留"]].map(s => <div key={s[0]}><i>{s[0]}</i><span><strong>{s[1]}</strong><small>{s[2]}</small></span><Check size={18} /></div>)}</div></section>
      <section className="qf-metrics">{[["待两级审核", reviewCounts, "review"], ["已批准资料版本", data.statusCounts.find(s => s.status === "APPROVED")?._count || 0, "library"], ["对插件型号", data.fixtureTotal, "fixtures"], ["产品图纸档案", data.total, "plans"]].map(([label, count, target]) => <button key={label} onClick={() => setView(String(target))}><span>{label}</span><strong>{count}</strong><ArrowRight size={18} /></button>)}</section>
      <section className="qf-card"><div className="qf-section-title"><h2>最近动态</h2><span>变更、审核和库存操作均保留履历</span></div>{data.eventRows.length ? data.eventRows.map(e => <div className="qf-event" key={e.id}><span className="qf-dot" /><div><strong>{eventLabel(e.entityType, e.action)}</strong><p>{e.actorName}{e.reason && " · " + e.reason}</p></div><time>{time(e.createdAt)}</time></div>) : <Empty>还没有准备记录。从计划资料准备开始，选择产品并上传图纸。</Empty>}</section>
    </main> : ["fixtures", "stock"].includes(view) ? <main>
      <div className="qf-toolbar"><label className="qf-search"><Search size={17} /><input aria-label="搜索治具" placeholder="搜索连接器、对插件型号或名称" value={search} onChange={e => setSearch(e.target.value)} /></label><span>{data.fixtures.length} / {data.fixtureTotal} 种对插件</span><button className="qf-primary" onClick={() => open("mapping", {}, { unit: "个" })}><Plus size={16} />新增连接器 / 对插件</button></div>
      {data.fixtures.length ? <div className="qf-fixture-grid">{data.fixtures.map(f => <section className="qf-card qf-fixture" key={f.id}><div className="qf-section-title"><div><small>{f.number}</small><h2>{f.model}</h2><p>{f.name} · {f.manufacturer || "未录入制造商"}</p></div><span className="qf-badge good">可用 {f.available} {f.unit}</span></div><div className="qf-counts"><div><b>{f.onHand}</b><small>实物在库</small></div><div><b>{f.reserved}</b><small>已预留</small></div><div><b>{f.issued}</b><small>在借</small></div><div><b>{f.held}</b><small>待验证</small></div></div>
        <div className="qf-mappings">{f.mappings.map(m => <div key={m.id}><span>{m.connector.model}</span><ArrowRight size={14} /><strong>{f.model}</strong><small>{m.preferred ? "当前对插" : "历史关系"} · {m.confirmedByName}确认</small><p>{m.evidence}</p></div>)}</div>
        {f.item.balances.map(b => <div className="qf-stock-row" key={b.id}><div><strong>{b.warehouse} / {b.location}</strong><small>可用 {b.onHand - b.held - b.repair - b.reserved} · 维修 {b.repair} · 待验证 {b.held}</small>{b.holdings.filter(h => h.issued || h.reserved).map(h => <small key={h.id}>{h.person}：预留 {h.reserved} / 借用 {h.issued}</small>)}</div><button onClick={() => open("stock", { fixtureId: f.id, stockId: b.id }, { kind: "RESERVE", quantity: "1", libraryItemId: product?.id || "", person: user.displayName || user.username, returnCondition: "GOOD" })}>库存操作</button></div>)}
        <div className="qf-actions"><button onClick={() => open("purchase", { fixtureId: f.id }, { quantity: "1", needDate: new Date().toLocaleDateString("sv-SE"), urgency: "NORMAL" })}>申购补充</button><button onClick={() => open("mapping", { fixtureId: f.id }, { fixtureId: f.id })}>补充连接器关系</button><button onClick={() => open("stock", { fixtureId: f.id }, { kind: "OPENING", quantity: "1", warehouse: "治具库", location: "", reason: "" })}>期初库存登记</button></div>
        {view === "stock" && <details><summary>查看库存流水</summary>{f.item.balances.flatMap(b => b.movements).sort((a,b) => b.createdAt.localeCompare(a.createdAt)).map(m => <div className="qf-event" key={m.id}><div><strong>{eventLabel("STOCK", m.kind.replace("FIXTURE_", ""))} · {m.quantity > 0 ? "+" : ""}{m.quantity} · 结余 {m.balance}</strong><p>{m.actorName} / {m.person} · {m.reason}</p></div><time>{time(m.createdAt)}</time></div>)}</details>}
      </section>)}</div> : <Empty>暂无治具。新增完整连接器型号，再由人工确认对应对插件。</Empty>}
      {data.fixtureTotal > 500 && <p className="qf-hint">当前最多展示 500 种，请用型号搜索缩小范围。</p>}
    </main> : <main className="qf-workspace">
      <aside className="qf-product-list"><div className="qf-search"><Search size={16} /><input aria-label="搜索产品" placeholder="产品型号 / 客户" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div><div className="qf-list-label">{view === "review" ? "待处理资料" : "产品图纸档案"}<span>{data.total}</span></div>
        {data.products.map(p => <button key={p.id} className={"qf-product " + (product?.id === p.id ? "active" : "")} onClick={() => selectProduct(p.id)}><strong>{p.specification}</strong><small>{p.customerName} · {p.productName || "产品资料"}</small><Badge status={p.fixturePackages[0]?.status || "UNSET"} /></button>)}
        {!data.products.length && <Empty>没有符合条件的产品。可先在计划中心关联或建立产品图纸档案。</Empty>}<div className="qf-pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>上一页</button><span>{page} / {Math.max(1, Math.ceil(data.total / 30))}</span><button disabled={page * 30 >= data.total} onClick={() => setPage(page + 1)}>下一页</button></div>
        <Link className="qf-text-link" href="/weekly-plan-center">进入计划中心 →</Link>
      </aside>
      <section className="qf-main">{!product ? <Empty>选择产品，开始资料准备与治具匹配。</Empty> : <>
        <div className="qf-product-head"><div><span className="qf-eyebrow">{product.customerName} / 产品级资料</span><h2>{product.specification}</h2><p>{product.productName || product.libraryKey}</p></div><button className="qf-primary" disabled={busy} onClick={edit}><Upload size={16} />{chosen ? "编辑 / 修订资料" : "准备生产资料"}</button></div>
        <div className="qf-status-strip"><div><FileCheck2 size={21} /><span><small>资料审核</small><Badge status={chosen?.status || "UNSET"} /></span></div><div><Layers3 size={21} /><span><small>治具准备</small><strong>{data.readiness.label}</strong></span></div><div><ClipboardCheck size={21} /><span><small>工单打印</small><strong>{data.approved ? "已批准版本可打印" : "待两级审核通过"}</strong></span></div></div>
        <div className="qf-version-bar"><label>当前查看版本 <select aria-label="资料版本" value={chosen?.id || ""} onChange={e => setPackageId(e.target.value)}>{product.fixturePackages.map(p => <option key={p.id} value={p.id}>{p.revision} · 第{p.sequence}次 · {QF_STATUS[p.status]}</option>)}{!chosen && <option>尚未建立</option>}</select></label><span>{chosen?.needFixture === false ? "无需治具 · 不上传 BOM" : chosen?.needFixture === true ? "需要治具 · " + chosen.parallelCount + " 台同时测试 / 每种备用 " + chosen.spareCount : "请选择是否需要治具"}</span></div>
        {chosen?.reason && <p className="qf-error">处理意见：{chosen.reason}</p>}
        <div className="qf-tabs compact">{[["docs", "受审资料"], ["bom", "BOM 连接器"], ["readiness", "治具匹配与申购"], ["history", "审核与版本履历"], ["orders", "生产工单"]].map(([k,l]) => <button key={k} aria-current={tab === k ? "page" : undefined} onClick={() => setTab(k)}>{l}</button>)}</div>
        {tab === "docs" && <div className="qf-detail-body"><div className="qf-two-cols"><section><h3>图纸文件</h3>{docs.length ? docs.map(f => <a className="qf-file" key={f.id} href={"/api/quality-fixtures/files?kind=drawing&id=" + f.id} target="_blank" rel="noreferrer"><FileCheck2 /><div><strong>{f.name}</strong><small>{f.version} · 已固定至本资料版本</small></div><ArrowRight size={16} /></a>) : <Empty>尚未选定受审图纸</Empty>}<h3>BOM 文件</h3>{chosen?.needFixture === false ? <p className="qf-hint">本产品无需治具，不需要上传 BOM。</p> : data.bom ? <a className="qf-file" href={"/api/quality-fixtures/files?id=" + data.bom.id}><FileSpreadsheet /><strong>{data.bom.name}</strong><span>下载原件</span></a> : <p className="qf-hint">尚未上传</p>}</section><section className="qf-review-track"><h3>两级资料审核</h3>{[["资料提交", chosen?.submittedByName, chosen?.submittedAt], ["主管初审", chosen?.supervisorName, chosen?.supervisorAt], ["质量复审", chosen?.qualityName, chosen?.qualityAt]].map(([l,n,t]) => <div key={l}><span className={"qf-step " + (t ? "done" : "")}>{t ? <Check size={16} /> : "·"}</span><span><strong>{l}</strong><small>{n || "待处理"} · {time(t)}</small></span></div>)}<p>治具短缺不阻止资料审核和工单打印。图纸、BOM 或治具需求变更需提交新版本。</p></section></div>
          {chosen?.status === "DRAFT" && <button className="qf-primary" disabled={busy} onClick={() => act(() => mutate({ action: "SUBMIT", id: chosen.id, version: chosen.version }, "已提交主管初审"))}>提交主管初审</button>}
          {data.canReview && <div className="qf-review-actions"><label><input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} />已核对图纸版本、资料完整性与连接器清单</label><div className="qf-actions"><button onClick={() => open("RETURN")}>退回完善</button><button disabled={!checked || busy} className="qf-primary" onClick={() => act(() => mutate({ action: "APPROVE", id: chosen?.id, version: chosen?.version, confirmed: true }, chosen?.status === "SUPERVISOR" ? "主管初审通过，已送质量复审" : "质量复审通过，可以打印工单"))}>{chosen?.status === "SUPERVISOR" ? "初审通过 · 送质量复审" : "质量复审通过"}</button></div></div>}
        </div>}
        {tab === "bom" && <div className="qf-detail-body"><h3>连接器清单 <small>{rows.filter(r => r.include).length} 行已纳入</small></h3><div className="qf-table-scroll"><table><thead><tr><th>来源行</th><th>连接器型号 / 名称</th><th>单台数量</th><th>位号</th><th>处理依据</th></tr></thead><tbody>{rows.map(r => <tr key={r.sourceRow} className={!r.include ? "muted" : ""}><td>{r.sheet} · {r.sourceRow}</td><td><strong>{r.model || "—"}</strong><small>{r.name}</small></td><td>{r.quantity} {r.unit}</td><td>{r.position || "—"}</td><td>{r.include ? "纳入治具" : "已排除"}<small>{r.reason || (r.autoExcluded ? "非连接器 / 汇总行" : "按原始数据")}</small></td></tr>)}</tbody></table></div>{!rows.length && <Empty>{chosen?.needFixture === false ? "无需治具，无 BOM 要求" : "请上传 BOM 并确认连接器"}</Empty>}</div>}
        {tab === "readiness" && <div className="qf-detail-body"><div className="qf-rule"><ShieldCheck size={18} /><span>治具数量按同时测试产品数计算。当前空闲库存满足后仍可预留；未预留库存可能被其他产品领用。</span></div>{data.readiness.unmatchedRows.map(r => <div className="qf-demand" key={r.key}><div><strong>{r.model}</strong><small>单台 {r.perUnit} {r.unit} · 对插件尚未确认</small></div><span className="qf-badge warn">待匹配</span><button onClick={() => open("mapping", { connector: r }, { connectorModel: r.model, connectorManufacturer: r.manufacturer, unit: r.unit })}>人工匹配对插件</button></div>)}{data.readiness.groups.map(g => <div className="qf-demand" key={g.fixtureId}><div><strong>{g.model}</strong><small>{g.connectorModels.join(" + ")} → 共用一个对插件型号</small></div><div className="qf-demand-numbers"><span>需求 <b>{g.required}</b></span><span>可用 <b>{g.available}</b></span><span>已分配 <b>{g.assigned}</b></span><span>在途 <b>{g.incoming}</b></span><span className={g.shortage ? "qf-orange" : ""}>缺口 <b>{g.shortage}</b></span></div><button disabled={busy || g.shortage <= g.incoming} onClick={() => open("purchase", { group: g }, { quantity: String(Math.max(0, g.shortage - g.incoming)), estimate: "", needDate: new Date().toLocaleDateString("sv-SE"), urgency: "NORMAL" })}>申购缺口</button></div>)}
          {!data.readiness.groups.length && !data.readiness.unmatchedRows.length && <Empty>{data.readiness.label}</Empty>}<div className="qf-actions"><button onClick={() => setView("stock")}>预留 / 领用 / 归还</button><Link className="qf-button" href="/workspace/purchases?source=FIXTURE">查看专用采购进度 →</Link></div></div>}
        {tab === "history" && <div className="qf-detail-body"><VersionChanges chosen={chosen} packages={product.fixturePackages} />{data.packageEvents.map(e => <div className="qf-event" key={e.id}><span className="qf-dot" /><div><strong>{eventLabel(e.entityType, e.action)} · {e.actorName}</strong><p>{e.reason || "操作与当时资料快照已保留"}</p><small>资料版本 {chosen?.revision} · 第 {chosen?.sequence} 次受审记录</small></div><time>{time(e.createdAt)}</time></div>)}{data.canQuality && ["APPROVED", "SUPERSEDED"].includes(chosen?.status || "") && <div className="qf-actions"><button onClick={() => open("REVOKE")}>撤销批准</button><button onClick={() => { setSelectedOrders(chosen?.continuedWorkOrderIds || []); open("CONTINUE_OLD_VERSION"); }}>指定旧版沿用工单</button></div>}</div>}
        {tab === "orders" && <div className="qf-detail-body"><div className="qf-rule">治具要求由产品资料版本统一管理，工单只引用适用版本。缺具允许打印，并持续展示准备状态。</div>{data.workOrders.map(w => <label className="qf-order" key={w.id}><input type="checkbox" checked={selectedOrders.includes(w.id)} onChange={e => setSelectedOrders(e.target.checked ? [...selectedOrders, w.id] : selectedOrders.filter(id => id !== w.id))} /><strong>{w.code}</strong><span>{w.fixtureBinding ? product.fixturePackages.find(p => p.id === w.fixtureBinding?.packageId)?.revision || "指定资料版本" : "跟随当前批准版本"}</span></label>)}{!data.workOrders.length && <Empty>此产品暂无关联工单</Empty>}<div className="qf-actions"><button disabled={!selectedOrders.length || !chosen || busy} onClick={() => act(() => mutate({ action: "BIND_WORK_ORDERS", packageId: chosen?.id, workOrderIds: selectedOrders }, "已为所选计划指定资料版本"))}>指定为当前查看版本</button><Link className="qf-button qf-primary" href="/production">进入生产执行 / 打印工单 →</Link></div></div>}
      </>}</section>
    </main>}
    {(draft || modal) && <div className="qf-overlay" onKeyDown={e => {
      if (e.key === "Escape") { e.preventDefault(); closeOverlay(); }
      if (e.key === "Tab") { const nodes = Array.from(modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea,a[href]') || []).filter(n => n.offsetParent !== null);
        if (e.shiftKey && document.activeElement === nodes[0]) { e.preventDefault(); nodes.at(-1)?.focus(); } else if (!e.shiftKey && document.activeElement === nodes.at(-1)) { e.preventDefault(); nodes[0]?.focus(); } }
    }}><section className={"qf-dialog " + (draft && !modal ? "wide" : "")} role="dialog" aria-modal="true" aria-labelledby="qf-dialog-title" ref={modalRef}><header><div><span className="qf-eyebrow">{product?.specification || "导通治具"}</span><h2 id="qf-dialog-title">{modal ? modalTitle : "生产资料准备"}</h2></div><button aria-label="关闭窗口" disabled={busy} onClick={closeOverlay}><X size={20} /></button></header>
      <div className="qf-dialog-body">{error && <p role="alert" className="qf-error">{error}</p>}
        {draft && !modal && <>
          <div className="qf-form-grid"><label className="qf-field">图纸版本<input value={draft.revision} onChange={e => setDraft({ ...draft, revision: e.target.value })} /></label><div className="qf-field">是否需要导通治具<div className="qf-choice">{[true, false].map(v => <button key={String(v)} aria-pressed={draft.needFixture === v} onClick={() => setDraft({ ...draft, needFixture: v, ...(v ? {} : { bomFileId: null, bomRows: [], bomMapping: null, bomConfirmed: false }) })}>{v ? "需要治具" : "无需治具"}</button>)}</div></div></div>
          <h3>01 · 选择受审图纸</h3><div className="qf-file-options">{data.product?.files.map(f => <label key={f.id}><input type="radio" name="drawingFile" checked={draft.drawingFileIds.includes(f.id)} onChange={() => setDraft({ ...draft, drawingFileIds: [f.id] })} /><span>{f.displayName || f.originalName}<small>{f.version} · {time(f.createdAt)}</small></span><a target="_blank" rel="noreferrer" href={"/api/quality-fixtures/files?kind=drawing&id=" + f.id}>预览</a></label>)}</div><label className="qf-upload"><Upload size={18} /><span>上传新图纸 <small>PDF / JPG / PNG / WebP · 最大 50 MB</small></span><input aria-label="上传图纸" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" disabled={busy} onChange={e => { const f = e.target.files?.[0]; e.target.value = ""; if (f) void upload(f, "drawing"); }} /></label>
          {draft.needFixture === true && <>
            <h3>02 · 导入 Excel BOM</h3><label className="qf-upload"><FileSpreadsheet size={22} /><span>{draft.bomFileId ? "替换 BOM 文件" : "上传 BOM 文件"}<small>.xlsx / .xls · 最大 10 MB · 保留源文件与行号</small></span><input aria-label="上传BOM" type="file" accept=".xlsx,.xls" disabled={busy} onChange={e => { const f = e.target.files?.[0]; e.target.value = ""; if (f) void upload(f, "bom"); }} /></label>
            {product?.fixtureBomFiles.length ? <label className="qf-field">或选择已上传 BOM<select value={draft.bomFileId || ""} onChange={e => { const id = e.target.value; if (id) void act(async () => { const b = await fetch("/api/quality-fixtures/files?id=" + id + "&parse=1").then(response<{ sheets: BomSheet[]; mapping: BomMapping }>); setSheets(b.sheets); setDraft({ ...draft, bomFileId: id, bomMapping: b.mapping, bomRows: [], bomConfirmed: false }); }); }}><option value="">选择文件</option>{product.fixtureBomFiles.map(b => <option key={b.id} value={b.id}>{b.name} · {time(b.createdAt)}</option>)}</select></label> : null}
            {draft.bomMapping && sheets.length > 0 && <>
              <div className="qf-form-grid"><label className="qf-field">工作表<select value={draft.bomMapping.sheet} onChange={e => setDraft({ ...draft, bomMapping: inferBomMapping(sheets.filter(s => s.name === e.target.value)), bomRows: [], bomConfirmed: false })}>{sheets.map(s => <option key={s.name}>{s.name}</option>)}</select></label><label className="qf-field">表头所在行<input type="number" min="1" max="100" value={draft.bomMapping.headerRow + 1} onChange={e => setDraft({ ...draft, bomMapping: { ...draft.bomMapping!, headerRow: Number(e.target.value) - 1 }, bomRows: [], bomConfirmed: false })} /></label><label className="qf-field">表头模板<select value="" onChange={e => { const t = data.templates.find(t => t.id === e.target.value); if (t) setDraft({ ...draft, bomMapping: { ...t.mapping as unknown as BomMapping, sheet: draft.bomMapping!.sheet }, bomRows: [], bomConfirmed: false }); }}><option value="">选择保存的映射</option>{data.templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>
              <div className="qf-form-grid">{[["model", "连接器型号 *"], ["quantity", "数量 *"], ["name", "物料名称"], ["manufacturer", "制造商"], ["position", "位号"], ["unit", "单位"]].map(([key,label]) => <label className="qf-field" key={key}>{label}<select value={Number(draft.bomMapping![key as keyof BomMapping])} onChange={e => setDraft({ ...draft, bomMapping: { ...draft.bomMapping!, [key]: Number(e.target.value) }, bomRows: [], bomConfirmed: false })}><option value={-1}>未选择</option>{sheets.find(s => s.name === draft.bomMapping!.sheet)?.rows[draft.bomMapping!.headerRow]?.map((c,i) => <option key={i} value={i}>{i + 1} 列 · {c.text || "空表头"}</option>)}</select></label>)}</div>
              <div className="qf-form-grid"><label className="qf-field">数量口径<select value={draft.bomMapping.quantityBasis} onChange={e => setDraft({ ...draft, bomMapping: { ...draft.bomMapping!, quantityBasis: e.target.value as BomMapping["quantityBasis"] }, bomRows: [], bomConfirmed: false })}><option value="PER_UNIT">单台产品用量</option><option value="ORDER_TOTAL">整单用量（除以产品数量）</option></select></label>{draft.bomMapping.quantityBasis === "ORDER_TOTAL" && <label className="qf-field">BOM 对应产品数量<input type="number" min="1" value={draft.bomMapping.productQuantity} onChange={e => setDraft({ ...draft, bomMapping: { ...draft.bomMapping!, productQuantity: Number(e.target.value) }, bomRows: [], bomConfirmed: false })} /></label>}<label className="qf-field">无单位列时使用<select value={draft.bomMapping.defaultUnit} onChange={e => setDraft({ ...draft, bomMapping: { ...draft.bomMapping!, defaultUnit: e.target.value }, bomRows: [], bomConfirmed: false })}><option>个</option><option>套</option><option>件</option></select></label></div>
              <label className="qf-checkbox"><input type="checkbox" checked={draft.bomMapping.flattenedConfirmed} onChange={e => setDraft({ ...draft, bomMapping: { ...draft.bomMapping!, flattenedConfirmed: e.target.checked }, bomConfirmed: false })} />若含多层 BOM，已核对数量是展开后的单台实际用量</label>
              <div className="qf-actions"><button disabled={busy} className="qf-primary" onClick={() => act(async () => { const found = await mutate<BomRow[]>({ action: "SCAN_BOM", id: draft.bomFileId, mapping: draft.bomMapping }, "", false); setDraft({ ...draft, bomRows: found, bomConfirmed: false }); })}>按表头识别连接器</button><button onClick={() => open("template")}>保存表头模板</button></div>
            </>}
            {draft.bomRows.length > 0 && <><h3>03 · 核对连接器与数量</h3><p className="qf-hint">识别结果需人工确认。修改型号、数量、位号或排除候选项时填写依据；“待确认”行不能提交审核。</p><div className="qf-table-scroll qf-edit-table"><table><thead><tr><th>来源 / 原始型号</th><th>处理</th><th>确认型号</th><th>数量 / 单位</th><th>位号</th><th>修改或排除依据</th></tr></thead><tbody>{draft.bomRows.map((r,i) => {
              const update = (values: Partial<BomRow>) => setDraft({ ...draft, bomRows: draft.bomRows.map((v,j) => j === i ? { ...v, ...values } : v), bomConfirmed: false });
              return <tr key={r.sourceRow}><td>{r.sourceRow} · {r.name}<small>{r.original.model}</small>{r.flags.map(f => <small className="qf-orange" key={f}>{f}</small>)}</td><td><select aria-label={"第" + r.sourceRow + "行处理"} value={r.include === null ? "" : r.include ? "1" : "0"} onChange={e => update({ include: e.target.value === "" ? null : e.target.value === "1" })}><option value="">待确认</option><option value="1">纳入治具</option><option value="0">排除</option></select></td><td><input aria-label={"第" + r.sourceRow + "行型号"} value={r.model} onChange={e => update({ model: e.target.value })} /></td><td><input aria-label={"第" + r.sourceRow + "行数量"} type="number" min="1" value={r.quantity ?? ""} onChange={e => update({ quantity: e.target.value === "" ? null : Number(e.target.value) })} /><select aria-label={"第" + r.sourceRow + "行单位"} value={r.unit} onChange={e => update({ unit: e.target.value })}>{[...new Set([r.unit, "个", "套", "件"])].map(u => <option key={u}>{u}</option>)}</select></td><td><input aria-label={"第" + r.sourceRow + "行位号"} value={r.position} onChange={e => update({ position: e.target.value })} /></td><td><input aria-label={"第" + r.sourceRow + "行依据"} value={r.reason} onChange={e => update({ reason: e.target.value })} /></td></tr>; })}</tbody></table></div><label className="qf-checkbox"><input type="checkbox" checked={draft.bomConfirmed} onChange={e => setDraft({ ...draft, bomConfirmed: e.target.checked })} />已核对所有连接器型号、单台数量和排除项</label></>}
            <div className="qf-form-grid"><label className="qf-field">同时测试产品数<input type="number" min="1" value={draft.parallelCount} onChange={e => setDraft({ ...draft, parallelCount: Number(e.target.value) })} /></label><label className="qf-field">每种对插件备用数量<input type="number" min="0" value={draft.spareCount} onChange={e => setDraft({ ...draft, spareCount: Number(e.target.value) })} /></label><p className="qf-rule">需求 = 单台连接器用量 × 同时测试产品数 + 每种备用数量。相同对插件共用库存，不按生产批量累计。</p></div>
          </>}
          {draft.needFixture === false && <div className="qf-rule good"><Check size={18} />无需治具，直接提交图纸审核即可。</div>}
        </>}
        {modal?.kind === "settings" && <><p className="qf-hint">主管先审、质量复审，两级须由不同人员完成，提交人不能审核自己的资料。</p><div className="qf-two-cols">{[["主管初审", supervisors, setSupervisors], ["质量复审", qualities, setQualities]].map(([label, ids, set]) => <fieldset key={String(label)}><legend>{String(label)}</legend>{data.users.map(u => <label className="qf-checkbox" key={u.id}><input type="checkbox" checked={(ids as string[]).includes(u.id)} disabled={!data.canConfigure} onChange={e => (set as (ids: string[]) => void)(e.target.checked ? [...ids as string[], u.id] : (ids as string[]).filter(id => id !== u.id))} />{u.displayName || u.username}</label>)}</fieldset>)}</div>{!data.canConfigure && <p>请由流程维护人更改审核人员。</p>}</>}
        {modal?.kind === "mapping" && <><div className="qf-form-grid">{field("产品连接器完整型号 *", "connectorModel")}{field("连接器制造商", "connectorManufacturer")}{field("连接器名称", "connectorName")}</div><label className="qf-field">对插件型号<select value={form.fixtureId || ""} onChange={e => setForm({ ...form, fixtureId: e.target.value })}><option value="">新建对插件型号</option>{data.fixtures.map(f => <option key={f.id} value={f.id}>{f.model} · {f.manufacturer}</option>)}</select></label>{!form.fixtureId && <div className="qf-form-grid">{field("对插件完整型号 *", "model")}{field("对插件制造商", "manufacturer")}{field("对插件名称 *", "name")}<label className="qf-field">单位<select value={form.unit || "个"} onChange={e => setForm({ ...form, unit: e.target.value })}><option>个</option><option>件</option><option>套</option></select></label><label className="qf-checkbox"><input type="checkbox" checked={form.assemblyRequired === "1"} onChange={e => setForm({ ...form, assemblyRequired: e.target.checked ? "1" : "0" })} />需组装并验证后使用</label></div>}{field("对插确认依据 *", "evidence", "text", "如厂家配对资料、针位核对或实物试插记录")}<p className="qf-rule">型号新建后库存为零。相同对插件复用同一库存，历史配对关系会保留。</p></>}
        {modal?.kind === "purchase" && <><div className="qf-rule">{modal.group ? modal.group.model + " · 当前缺口 " + modal.group.shortage + "，本需求在途 " + modal.group.incoming + "，本次最多新增 " + Math.max(0, modal.group.shortage - modal.group.incoming) + " " + modal.group.unit : fixture?.model + " · 治具库补充申购 · 当前可用 " + fixture?.available}</div><div className="qf-form-grid">{!modal.group && field("补充申购用途 *", "reason")}{field("申购数量 *", "quantity", "number")}{field("预算合计（元）*", "estimate", "number")}{field("需求日期 *", "needDate", "date")}<label className="qf-field">紧急程度<select value={form.urgency || "NORMAL"} onChange={e => setForm({ ...form, urgency: e.target.value })}><option value="NORMAL">正常</option><option value="URGENT">紧急</option><option value="CRITICAL">特急</option></select></label></div><p className="qf-hint">来源自动标记为“治具申购”，保留图纸版本、连接器与对插依据；采购验收后直接更新治具库存。</p></>}
        {modal?.kind === "stock" && <><h3>{fixture?.model} · {stock ? stock.warehouse + " / " + stock.location : "登记已有实物"}</h3><div className="qf-form-grid"><label className="qf-field">操作<select value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value })}>{(stock ? [["RESERVE","预留"],["RELEASE","释放预留"],["ISSUE","领用"],["RETURN","归还"],["HOLD","转待验证"],["VERIFY","验证通过"],["REPAIR","送修"],["REPAIRED","维修返回"],["SCRAP","报废"],["ADJUST","盘点调整"]] : [["OPENING","期初库存"]]).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>{field("数量 *", "quantity", "number")}
          {!stock && <>{field("仓库 *", "warehouse")}{field("库位 *", "location")}</>}
          {["RESERVE","RELEASE","ISSUE","RETURN"].includes(form.kind) && <><label className="qf-field">产品 *<select value={form.libraryItemId || ""} onChange={e => setForm({ ...form, libraryItemId: e.target.value })}><option value="">选择产品</option>{[...new Map([...data.products, ...(product ? [product] : [])].map(p => [p.id, p])).values()].map(p => <option key={p.id} value={p.id}>{p.specification}</option>)}</select></label>{field("领用 / 归还人 *", "person")}<label className="qf-field">关联工单（可选）<select value={form.workOrderId || ""} onChange={e => setForm({ ...form, workOrderId: e.target.value })}><option value="">按产品预留 / 领用</option>{form.libraryItemId === product?.id && data.workOrders.map(w => <option key={w.id} value={w.id}>{w.code}</option>)}</select></label></>}
          {form.kind === "RETURN" && <label className="qf-field">归还状态<select value={form.returnCondition || "GOOD"} onChange={e => setForm({ ...form, returnCondition: e.target.value })}><option value="GOOD">完好可用</option><option value="CHECK">待验证 / 异常</option></select></label>}
          {["REPAIR","SCRAP"].includes(form.kind) && <label className="qf-field">来源状态<select value={form.from || "HELD"} onChange={e => setForm({ ...form, from: e.target.value })}><option value="HELD">待验证</option><option value="AVAILABLE">可用</option>{form.kind === "SCRAP" && <option value="REPAIR">维修中</option>}</select></label>}
          {form.kind === "ADJUST" && <label className="qf-field">盘点方向<select value={form.direction || ""} onChange={e => setForm({ ...form, direction: e.target.value })}><option value="">选择</option><option value="IN">盘盈（入待验证）</option><option value="OUT">盘亏（减少可用）</option></select></label>}
        </div>{form.kind === "VERIFY" && <div className="qf-actions">{[["fitConfirmed", "对插适配通过"], ["continuityConfirmed", "导通验证通过"]].map(([k,l]) => <label className="qf-checkbox" key={k}><input type="checkbox" checked={form[k] === "1"} onChange={e => setForm({ ...form, [k]: e.target.checked ? "1" : "0" })} />{l}</label>)}</div>}{field("操作 / 验证说明", "reason")}<p className="qf-rule">期初入库、盘盈与维修返回先进入待验证；实物数量只记录一次。</p></>}
        {modal?.kind === "template" && field("模板名称 *", "name")}
        {modal && ["RETURN","REVOKE","CONTINUE_OLD_VERSION"].includes(modal.kind) && <>{field("处理原因 *", "reason")}{modal.kind === "REVOKE" && <p className="qf-error">撤销后该版本不再允许生成、下载或确认正式打印任务，原有记录保留。</p>}{modal.kind === "CONTINUE_OLD_VERSION" && <><p>仅以下选中的在制工单允许使用旧版本，其余工单需采用当前批准资料。</p>{data.workOrders.map(w => <label className="qf-checkbox" key={w.id}><input type="checkbox" checked={selectedOrders.includes(w.id)} onChange={e => setSelectedOrders(e.target.checked ? [...selectedOrders, w.id] : selectedOrders.filter(id => id !== w.id))} />{w.code}</label>)}</>}</>}
      </div>
      <footer><span className="qf-hint">{busy ? "正在保存，请稍候…" : draft && !modal ? "保存后提交主管初审，再由质量复审" : "操作将记录在业务履历中"}</span><div className="qf-actions"><button disabled={busy} onClick={closeOverlay}>取消</button>{draft && !modal ? <><button disabled={busy} onClick={() => act(() => saveDraft(draft))}>保存草稿</button><button disabled={busy} className="qf-primary" onClick={() => act(async () => { const d = await saveDraft(draft); await mutate({ action: "SUBMIT", id: d.id, version: d.version }, "已提交主管初审"); setDraft(null); })}>保存并提交审核</button></> : <button disabled={busy || (modal?.kind === "settings" && !data.canConfigure)} className="qf-primary" onClick={submitModal}>{modal?.kind === "purchase" ? "提交治具申购" : "确认保存"}</button>}</div></footer>
    </section></div>}
  </div>;
}

function VersionChanges({chosen, packages}: {chosen: QfWorkbench["chosen"]; packages: NonNullable<QfWorkbench["product"]>["fixturePackages"]}) {
  if (!chosen) return null;
  const previous = packages.find(p => p.sequence < chosen.sequence);
  if (!previous) return <p className="qf-hint">首次提交资料。原始图纸、BOM 和审核签名均保留在本版本。</p>;
  const fields: [string, unknown, unknown][] = [
    ["图纸版本号",previous.revision,chosen.revision], ["治具需求", previous.needFixture === null ? "未确认" : previous.needFixture ? "需要治具" : "无需治具",chosen.needFixture === null ? "未确认" : chosen.needFixture ? "需要治具" : "无需治具"],
    ["受审图纸",(previous.drawingFiles as unknown as DrawingEvidence[]).map(f=>f.name+" "+f.version).join("、"),(chosen.drawingFiles as unknown as DrawingEvidence[]).map(f=>f.name+" "+f.version).join("、")],
    ["BOM 原件",previous.bomFileId === chosen.bomFileId ? "未更换" : previous.bomFileId ? "上一版原件" : "无",previous.bomFileId === chosen.bomFileId ? "未更换" : chosen.bomFileId ? "已更换原件" : "无"],
    ["同时测试台数",previous.parallelCount,chosen.parallelCount], ["每种备用",previous.spareCount,chosen.spareCount]
  ];
  const changes = fields.filter(([,a,b])=>a!==b);
  const bomChanged = JSON.stringify(previous.bomRows)!==JSON.stringify(chosen.bomRows);
  return <section className="qf-card"><h3>与上一版 {previous.revision} 对比</h3>{changes.length ? <div className="qf-table-wrap"><table><thead><tr><th>变更项</th><th>上一版</th><th>当前版</th></tr></thead><tbody>{changes.map(([name,a,b])=><tr key={name}><td>{name}</td><td>{String(a)||"—"}</td><td>{String(b)||"—"}</td></tr>)}</tbody></table></div> : <p>基础资料未变化</p>}<p className="qf-hint">{bomChanged ? "连接器清单已变化，请在 BOM 连接器页核对明细；上方版本选择可回看原记录。" : "连接器清单未变化。"}</p></section>;
}
