'use client';
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, BookOpen, Check, ChevronDown, ChevronRight, Clock3, Filter, ImageIcon, Loader2, QrCode, Search, ShieldCheck, X } from 'lucide-react';
import { acceptedStatuses, displayPayload, historicalOnly, kindLabels, normalizedSampleSearch, photoLabels, safeLibraryReturn, statusLabels, type LibraryDetail, type LibraryEntry, type LibraryProduct, type LibrarySource } from '@/lib/sample-library';
import SampleLibraryPhoto from './SampleLibraryPhoto';
import { SampleLibraryQrDialog } from './SampleLibraryQr';
import { useModalLayer } from '@/components/useModalLayer';
type Listing={items:LibraryProduct[];total:number;page:number;pageSize:number;customers:{name:string;count:number}[]};
type Recent={id:string;specification:string;customerName:string};
const date=(value:string)=>new Date(value).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'});
async function read<T>(url:string, signal?:AbortSignal):Promise<T>{const response=await fetch(url,{cache:'no-store',signal});const body=await response.json();if(!response.ok||!body.ok)throw new Error(response.status===401||response.status===403?'登录已失效或没有查看权限，请重新登录':body.error||'加载失败，请重试');return body;}
function Highlight({text,query}:{text:string;query:string}) { const normalized=normalizedSampleSearch(text),needle=normalizedSampleSearch(query);if(!needle)return <>{text}</>;const start=normalized.indexOf(needle);if(start<0)return <>{text}</>;let compact='',a=-1,b=text.length;for(let i=0;i<text.length;i++){if(compact.length===start&&a<0)a=i;compact+=normalizedSampleSearch(text[i]);if(compact.length>=start+needle.length){b=i+1;break;}}return <>{text.slice(0,Math.max(0,a))}<mark>{text.slice(Math.max(0,a),b)}</mark>{text.slice(b)}</>; }
function Entries({entries}:{entries:LibraryEntry[]}) {return <div className="sl-entries">{entries.map((entry,index)=><article key={entry.id} className="sl-data-card"><header><span>{String(index+1).padStart(2,'0')}</span><div><small>{kindLabels[entry.kind]||entry.kind}</small><h3>{entry.label||String(entry.payload.model||entry.payload.processName||kindLabels[entry.kind]||'样品记录')}</h3></div></header>{entry.conflict&&<p className="sl-conflict">参数存在重复待处理 · 此处保留本次原始记录</p>}<dl>{displayPayload(entry.payload).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{!displayPayload(entry.payload).length&&<p className="sl-muted">尚未记录可显示参数</p>}</article>)}</div>;}

export default function SampleLibraryMobile({userId,displayName}:{userId:string;displayName:string}) {
  const [params,setParams]=useState<URLSearchParams|null>(null),[query,setQuery]=useState(''),[list,setList]=useState<Listing|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [detail,setDetail]=useState<LibraryDetail|null>(null),[source,setSource]=useState<LibrarySource|null>(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState(''),[sourceLoading,setSourceLoading]=useState(false);
  const [recent,setRecent]=useState<Recent[]>([]),[customerQuery,setCustomerQuery]=useState(''),[photoCategory,setPhotoCategory]=useState(''),[showHistory,setShowHistory]=useState(false);
  const listRef=useRef<HTMLDivElement>(null),detailRef=useRef<HTMLDivElement>(null),sheetRef=useRef<HTMLElement>(null),loadedKey=useRef(''),restoreScroll=useRef<number|null>(null),ready=useRef(false);
  const key=`sample-library:${userId}`, productId=params?.get('product')||'',tab=params?.get('tab')||'photos', sourceKey=params?.get('source')||'',sheet=params?.get('sheet')||'',pages=Math.min(100,Math.max(1,Number(params?.get('pages'))||1));
  const sync=useCallback(()=>{const next=new URLSearchParams(window.location.search);setParams(next);setQuery(next.get('q')||'');},[]);
  useEffect(()=>{let next=new URLSearchParams(window.location.search);try{const saved=JSON.parse(sessionStorage.getItem(key+':list')||'null');if(!next.toString()&&saved?.url){next=new URLSearchParams(saved.url);window.history.replaceState({...window.history.state},'',`/sample-library?${next}`);restoreScroll.current=saved.scroll||0;}setRecent(JSON.parse(localStorage.getItem(key+':recent')||'[]'));}catch{}setParams(next);setQuery(next.get('q')||'');ready.current=true;const pop=()=>sync();window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[key,sync]);
  const nav=useCallback((changes:Record<string,string|null>,replace=false)=>{const next=new URLSearchParams(window.location.search);for(const [name,value] of Object.entries(changes)){if(value===null||value==='')next.delete(name);else next.set(name,value);}window.history[replace?'replaceState':'pushState']({...window.history.state,slNav:replace?window.history.state?.slNav:true},'',`/sample-library${next.size?'?'+next:''}`);setParams(next);},[]);
  const closeLayer=()=>{if(window.history.state?.slNav)window.history.back();else nav(sheet?{sheet:null}:params?.has('photo')?{photo:null}:{product:null,source:null,tab:null},true);};
  useModalLayer({open:sheet==='customers'||sheet==='help',layerRef:sheetRef,onClose:closeLayer});
  const returnTo=safeLibraryReturn(params?.get('returnTo'));
  const saveList=()=>{if(!params)return;const saved=new URLSearchParams(params);for(const name of ['product','source','photo','tab','sheet'])saved.delete(name);try{sessionStorage.setItem(key+':list',JSON.stringify({url:saved.toString(),scroll:listRef.current?.scrollTop||0}));}catch{}};
  useEffect(()=>{if(!ready.current||query===(params?.get('q')||''))return;const timer=setTimeout(()=>nav({q:query.trim(),pages:null},true),300);return()=>clearTimeout(timer);},[query,params,nav]);
  const listKey=JSON.stringify([params?.get('q')||'',params?.get('customer')||'',params?.get('filter')||'',params?.get('recent')||'']);
  useEffect(()=>{if(!params)return;const controller=new AbortController();let active=true;const previousKey=loadedKey.current;setLoading(true);setError('');
    const base=new URLSearchParams({q:params.get('q')||'',customer:params.get('customer')||'',filter:params.get('filter')||''});if(params.get('recent'))base.set('ids',recent.map(row=>row.id).join(','));
    const start=previousKey===listKey&&list?list.page+1:1;if(start>pages){setLoading(false);return;}
    if(start===1)setList(null);
    void (async()=>{let result:Listing|null=null;let combined:LibraryProduct[]=[];for(let page=start;page<=pages;page++){base.set('page',String(page));const data=await read<Listing>('/api/sample-library?'+base,controller.signal);combined=[...combined,...data.items];result={...data,items:combined};if(page*data.pageSize>=data.total)break;}if(!active||!result)return;const final=result;setList(previous=>({...final,items:start>1?[...(previous?.items||[]),...final.items]:final.items}));loadedKey.current=listKey;if(restoreScroll.current!==null)requestAnimationFrame(()=>{if(listRef.current)listRef.current.scrollTop=restoreScroll.current||0;restoreScroll.current=null;});})().catch(caught=>{if(active)setError(caught.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};
    // list is intentionally preserved while opening a product; only filters/pages refresh it.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[listKey,pages,retry,Boolean(params)]);
  useEffect(()=>{if(!productId){setDetail(null);setSource(null);setDetailError('');return;}const controller=new AbortController();setDetailLoading(true);setDetail(null);setSource(null);setDetailError('');setPhotoCategory('');setShowHistory(false);
    void read<LibraryDetail>('/api/sample-library/'+encodeURIComponent(productId),controller.signal).then(data=>{setDetail(data);const p=data.product;setRecent(previous=>{const next=[{id:p.id,specification:p.specification,customerName:p.customerName},...previous.filter(row=>row.id!==p.id)].slice(0,20);try{localStorage.setItem(key+':recent',JSON.stringify(next));}catch{}return next;});}).catch(caught=>{if(!controller.signal.aborted)setDetailError(caught.message);}).finally(()=>{if(!controller.signal.aborted)setDetailLoading(false);});return()=>controller.abort();
  },[productId,key,retry]);
  const effectiveSource=sourceKey||detail?.defaultKey||'';
  useEffect(()=>{if(!productId||!effectiveSource)return;const controller=new AbortController();setSourceLoading(true);setSource(null);setDetailError('');void read<LibrarySource>(`/api/sample-library/${encodeURIComponent(productId)}?source=${encodeURIComponent(effectiveSource)}`,controller.signal).then(setSource).catch(caught=>{if(!controller.signal.aborted)setDetailError(caught.message);}).finally(()=>{if(!controller.signal.aborted)setSourceLoading(false);});return()=>controller.abort();},[productId,effectiveSource,retry]);
  const photos=source?.photos.filter(photo=>!photoCategory||photo.category===photoCategory)||[],photoIndex=photos.findIndex(photo=>photo.id===params?.get('photo'));
  const openProduct=(id:string)=>{saveList();nav({product:id,source:null,tab:null,photo:null});};
  const changeFilter=(changes:Record<string,string|null>)=>{if(listRef.current)listRef.current.scrollTop=0;nav({...changes,pages:null},true);};
  const backProduct=()=>{nav({product:null,source:null,tab:null,photo:null},true);};
  const history=detail?.histories||[],validHistory=history.filter(row=>!historicalOnly(row));
  const empty=(title:string,description:string)=><div className="sl-empty"><BookOpen size={30}/><h2>{title}</h2><p>{description}</p></div>;
  return <main className="sl-app">
    <header className="sl-header"><button aria-label={productId?'返回样品列表':'返回入口'} onClick={()=>productId?backProduct():params?.get('embedded')==='1'&&window.parent!==window?window.parent.postMessage({type:'sample-library-close'},window.location.origin):window.location.assign(returnTo||'/account')}><ArrowLeft size={21}/></button><div><strong>{productId?'样品参考资料':'手机样品库'}</strong><small>{productId?detail?.product.customerName||'正在读取资料':`${displayName} · 只读查看`}</small></div><button aria-label="查看样品库二维码" onClick={()=>nav({sheet:'qr'})}><QrCode size={21}/></button><button aria-label="使用帮助" className="sl-help-button" onClick={()=>nav({sheet:'help'})}>?</button></header>
    <div className="sl-list-page" hidden={Boolean(productId)}>
      <section className="sl-search-area"><div className="sl-eyebrow"><span/><span>把做过的经验，带到手边</span></div><h1>查型号，看样品</h1><label className="sl-search"><Search size={21}/><input aria-label="搜索样品型号" type="search" inputMode="search" enterKeyHint="search" placeholder="输入部分型号、产品名" value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){nav({q:query.trim(),pages:null},true);event.currentTarget.blur();}}}/>{query&&<button aria-label="清除型号搜索" onClick={()=>{setQuery('');changeFilter({q:null});}}><X size={17}/></button>}</label><div className="sl-filters"><button className={params?.get('customer')?'selected':''} onClick={()=>{setCustomerQuery('');nav({sheet:'customers'});}}><Filter size={15}/><span>{params?.get('customer')||'全部客户'}</span><ChevronDown size={14}/></button>{[['','全部资料'],['photos','有照片'],['parameters','有参数']].map(([value,label])=><button key={value} className={(params?.get('filter')||'')===value?'selected':''} aria-pressed={(params?.get('filter')||'')===value} onClick={()=>changeFilter({filter:value})}>{label}</button>)}</div></section>
      <div className="sl-list-scroll" ref={listRef} onScroll={saveList}>
        {recent.length>0&&!query&&!params?.get('customer')&&!params?.get('recent')&&<section className="sl-recent"><header><Clock3 size={15}/><strong>最近查看</strong><button onClick={()=>changeFilter({recent:'1'})}>全部 <ChevronRight size={14}/></button></header><div>{recent.slice(0,5).map(row=><button key={row.id} onClick={()=>openProduct(row.id)}>{row.specification}</button>)}</div></section>}
        <div className="sl-result-heading"><strong>{params?.get('recent')?'最近查看的样品':'产品资料'} <span>{list?.total??'—'}</span></strong>{(query||params?.get('customer')||params?.get('filter')||params?.get('recent'))&&<button onClick={()=>{setQuery('');changeFilter({q:null,customer:null,filter:null,recent:null});}}>清除筛选</button>}</div>
        {error&&<div className="sl-error" role="alert"><p>{error}</p><button onClick={()=>{loadedKey.current='';setRetry(n=>n+1);}}>重新加载</button><a href={`/login?next=${encodeURIComponent('/sample-library?'+(params?.toString()||''))}`}>重新登录</a></div>}
        {!list&&loading&&<div className="sl-skeleton" aria-label="正在加载样品">{[1,2,3].map(n=><div key={n}/>)}</div>}
        <div className="sl-product-list">{list?.items.map(product=><button key={product.id} className="sl-product-card" onClick={()=>openProduct(product.id)}><div className="sl-product-thumb">{product.thumbnailId?<img loading="lazy" decoding="async" src={`/api/sample-library/photos/${product.thumbnailId}?size=thumb`} alt={`${product.specification}样品缩略图`} onError={event=>{event.currentTarget.style.visibility='hidden';}}/>:<BookOpen size={30}/>}</div><div className="sl-product-info"><small>{product.customerName}</small><h2><Highlight text={product.specification} query={query}/></h2>{product.productName&&<p>{product.productName}</p>}<div className="sl-card-counts"><span><ImageIcon size={13}/>{product.photos} 照片</span><span>{product.parameters} 数据</span><span>{product.tasks} 次样品</span></div><footer>更新 {date(product.updatedAt)}<ArrowUpRight size={16}/></footer></div></button>)}</div>
        {list&&!list.items.length&&!loading&&!error&&<>{empty('没有找到匹配样品',params?.get('recent')?'最近查看的资料可能已移除。可清除筛选查看全部。':'试试缩短型号，或清除客户筛选。资料库只展示已有照片或数据的正式样品任务。')}<button className="sl-empty-clear" onClick={()=>{setQuery('');changeFilter({q:null,customer:null,filter:null,recent:null});}}>查看全部样品</button></>}
        {list&&list.items.length<list.total&&<button className="sl-load-more" disabled={loading} onClick={()=>nav({pages:String(pages+1)},true)}>{loading?<Loader2 size={16} className="sl-spin"/>:'加载更多'}<span>{list.items.length} / {list.total}</span></button>}
        {!!list?.items.length&&list.items.length>=list.total&&<p className="sl-list-end">已显示 {list.total} 个产品 · 含历次已完成样品</p>}
      </div>
    </div>
    {productId&&<div className="sl-detail-scroll" ref={detailRef}>
      {detailLoading&&<div className="sl-loading"><Loader2 className="sl-spin"/>正在读取历次样品…</div>}
      {detailError&&<div className="sl-error" role="alert"><p>{detailError}</p><button onClick={()=>setRetry(n=>n+1)}>重试</button><button onClick={backProduct}>返回样品库</button></div>}
      {detail&&<><section className="sl-product-hero"><div className="sl-eyebrow"><BookOpen size={15}/> 产品参考档案</div><h1>{detail.product.specification}</h1><p>{detail.product.productName||'样品参考资料'}</p><div><span>{history.length} 份历史版本</span><button onClick={()=>nav({sheet:'qr'})}><QrCode size={14}/>产品二维码</button></div></section>
        <button className="sl-version" onClick={()=>nav({tab:'history'},true)}><span className={source&&acceptedStatuses.includes(source.history.status)?'sl-verified':'sl-unverified'}><ShieldCheck size={18}/></span><span><strong>{source?statusLabels[source.history.status]||source.history.status:'选择资料版本'}</strong><small>{source?`${source.history.code} · ${source.history.revision===null?'未提交记录':'R'+source.history.revision} · ${date(source.history.date)}`:'同一次样品的照片与参数一起展示'}</small></span><ChevronRight size={18}/></button>
        <nav className="sl-tabs" aria-label="样品资料分类">{[['photos','照片'],['parameters','参数'],['process','工序工时'],['history','历次记录']].map(([value,label])=><button key={value} aria-selected={tab===value} role="tab" onClick={()=>nav({tab:value},true)}>{label}{value==='photos'&&source&&<small>{source.photos.length}</small>}</button>)}</nav>
        {tab==='history'?<section className="sl-history"><p className="sl-muted">切换后只显示所选版本的照片与数据。</p>{[...validHistory,...(showHistory?history.filter(historicalOnly):[])].map(row=><button key={row.key} className={`sl-history-card ${effectiveSource===row.key?'selected':''}`} onClick={()=>{setPhotoCategory('');nav({source:row.key,tab:'photos'},true);detailRef.current?.scrollTo({top:0});}}><div><span className={acceptedStatuses.includes(row.status)?'sl-status green':'sl-status'}>{row.cancelled?'已取消 · 历史':statusLabels[row.status]||row.status}</span><small>{date(row.date)}</small></div><strong>{row.code} · {row.revision===null?'未提交':'R'+row.revision}</strong><footer>{row.photos} 张照片 · {row.parameters} 条数据{effectiveSource===row.key?<Check size={18}/>:<ChevronRight size={18}/>}</footer></button>)}{history.some(historicalOnly)&&<button className="sl-history-expand" onClick={()=>setShowHistory(!showHistory)}>{showHistory?'收起':'查看'}退回 / 撤回 / 作废历史（{history.filter(historicalOnly).length}）</button>}{!history.length&&empty('这个产品尚无样品资料','已有计划不等于已有参考数据。上传照片或保存样品数据后会出现在这里。')}</section>:<>
          {sourceLoading&&<div className="sl-loading"><Loader2 className="sl-spin"/>正在读取所选版本…</div>}
          {!effectiveSource&&!sourceLoading&&empty('暂无可默认参考的版本','可到“历次记录”查看退回或撤回历史。')}
          {source&&<><div className={`sl-source-note ${historicalOnly(source.history)?'warning':''}`}>{historicalOnly(source.history)?'此版本已退回、撤回或作废，仅作历史追溯。':acceptedStatuses.includes(source.history.status)?'已审核的样品参考记录；生产操作仍以当前受控图纸和 SOP 为准。':'未审核参考：这里是现场已上传的原始记录，使用前请核对。'}{source.comment&&<p>审核说明：{source.comment}</p>}</div>
            {tab==='photos'&&<><div className="sl-photo-filters"><button className={!photoCategory?'selected':''} onClick={()=>setPhotoCategory('')}>全部 {source.photos.length}</button>{Array.from(new Set(source.photos.map(photo=>photo.category))).map(category=><button key={category} className={photoCategory===category?'selected':''} onClick={()=>setPhotoCategory(category)}>{photoLabels[category]||category}</button>)}</div><div className="sl-photo-grid">{photos.map(photo=><button key={photo.id} onClick={()=>nav({photo:photo.id})}><div><img loading="lazy" decoding="async" src={`/api/sample-library/photos/${photo.id}?size=thumb`} alt={photo.caption||photo.name}/><span><ImageIcon size={13}/>{photoLabels[photo.category]||photo.category}</span></div><strong>{photo.caption||photo.name}</strong><small>{date(photo.date)}</small></button>)}</div>{!photos.length&&empty('此版本尚无照片','可以切换历次样品记录，查看之前上传的照片。')}</>}
            {tab==='parameters'&&<>{!source.entries.filter(entry=>entry.kind!=='PROCESS_TIME').length?empty('此版本尚无参数','照片上的手写数据仍可通过放大照片查看。'):<Entries entries={source.entries.filter(entry=>entry.kind!=='PROCESS_TIME')}/>}</>}
            {tab==='process'&&<><div className="sl-time-note"><Clock3 size={19}/><div><strong>本次计划单套工时</strong><span>{source.history.unitPlannedMilliseconds===null?'未记录':`${source.history.unitPlannedMilliseconds/60000} 分钟 / 套`}</span><small>下方为历次采集的参考或实测工时，不替代正式工时标准。</small></div></div>{!source.entries.filter(entry=>entry.kind==='PROCESS_TIME').length?empty('此版本尚无工序工时','未记录的工时不会按零显示。'):<Entries entries={source.entries.filter(entry=>entry.kind==='PROCESS_TIME')}/>}</>}
          </>}
        </>}
      </>}
    </div>}
    {photoIndex>=0&&<SampleLibraryPhoto photos={photos} index={photoIndex} onIndex={index=>nav({photo:photos[index].id},true)} onClose={closeLayer}/>}
    {sheet==='qr'&&<SampleLibraryQrDialog productId={productId||undefined} title={detail?.product.specification} onClose={closeLayer}/>}
    {(sheet==='customers'||sheet==='help')&&<div className="sl-sheet-backdrop"><section className="sl-sheet" ref={sheetRef} role="dialog" aria-modal="true" aria-label={sheet==='customers'?'筛选客户':'样品库使用帮助'} tabIndex={-1}><header><h2>{sheet==='customers'?'选择客户':'使用手机样品库'}</h2><button aria-label="关闭筛选面板" onClick={closeLayer}><X/></button></header>{sheet==='customers'?<><label className="sl-search"><Search size={19}/><input aria-label="搜索客户" placeholder="输入客户名称" value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)}/></label><div className="sl-customer-options"><button onClick={()=>nav({customer:null,sheet:null,pages:null},true)}>全部客户{!params?.get('customer')&&<Check size={18}/>}</button>{list?.customers.filter(customer=>customer.name.includes(customerQuery.trim())).map(customer=><button key={customer.name} onClick={()=>nav({customer:customer.name,sheet:null,pages:null},true)}><span>{customer.name}<small>{customer.count} 个产品</small></span>{params?.get('customer')===customer.name&&<Check size={18}/>}</button>)}</div></>:<div className="sl-help"><p>型号不用记全。输入中间一段，或用空格分开几个型号片段，再按客户筛选。</p><p>每份记录都标明样品批次与审核状态。切换“历次记录”后，照片和参数会一起切换。</p><p>点开照片可双指缩放、双击放大、拖动和旋转。适屏后左右滑动切换。</p><p>可在浏览器菜单中选择“添加到主屏幕”或“添加书签”，下次直接进入。微信内若没有此选项，可用浏览器打开。</p><p>最近查看保存在当前设备，并按员工账号区分；查看资料需要联网和有效登录。</p>{returnTo&&<a href={returnTo}>返回打开前的页面</a>}</div>}</section></div>}
  </main>;
}
