'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, CalendarDays, ChevronDown, ClipboardCheck, Download, Plus, RefreshCw, Search, Trash2 } from 'lucide-react';
import { AppWorkbenchHeader } from '@/components/layout/AppWorkbenchHeader';
import { requestPreviewLeave } from '@/components/DocumentOrientation';
import { beijingInput, isFirstInspectionProcess, QUALITY_DATA_TYPES, QUALITY_LABELS, RESULT_LABELS, type QualityInspectionStep, type QualityOrder, type QualityRecord } from '@/lib/quality-data';
import type { CurrentUserDTO } from '@/types';
import QualityPaperEditor, { type PaperType } from './QualityPaperEditor';
import QualityPaperDetail from './QualityPaperDetail';
import { downloadQuality, qualityRequest } from './client';
import './quality-paper.css';

export type FirstOverview = { order: QualityOrder; steps: Array<QualityInspectionStep & { result: string | null; count: number; retired?: boolean }>; unassignedCount: number };
type Records = { total: number; page: number; items: QualityRecord[] };
type Orders = { total: number; page: number; items: QualityOrder[] };
type Props = { user: CurrentUserDTO; type: PaperType; initialRecordId?: string; onTypeChange: (type: string) => void; onReferences: () => void };

export default function QualityPaperWorkbench({ user, type, initialRecordId, onTypeChange, onReferences }: Props) {
  const first = type === 'FIRST';
  const today = beijingInput().slice(0, 10);
  const [orders, setOrders] = useState<Orders>({ total: 0, page: 1, items: [] }), [orderId, setOrderId] = useState(''), [orderPage, setOrderPage] = useState(1), [orderQ, setOrderQ] = useState(''), [orderSearch, setOrderSearch] = useState('');
  const [overview, setOverview] = useState<FirstOverview | null>(null), [stepId, setStepId] = useState(''), [allSteps, setAllSteps] = useState(false), [stepQ, setStepQ] = useState('');
  const [period, setPeriod] = useState(first ? 'all' : 'month'), [date, setDate] = useState(today), [start, setStart] = useState(today), [end, setEnd] = useState(today);
  const [q, setQ] = useState(''), [search, setSearch] = useState(''), [day, setDay] = useState(''), [days, setDays] = useState<Array<{ date: string; count: number }>>([]), [deleted, setDeleted] = useState(false);
  const [records, setRecords] = useState<Records>({ total: 0, page: 1, items: [] }), [selected, setSelected] = useState<QualityRecord | null>(null), [page, setPage] = useState(1);
  const [editor, setEditor] = useState<{ record?: QualityRecord } | null>(null), [refresh, setRefresh] = useState(0), [loading, setLoading] = useState(false), [error, setError] = useState(''), [exporting, setExporting] = useState(false);
  const [collapsedDays, setCollapsedDays] = useState<Set<string>>(new Set());
  const preferred = useRef(initialRecordId || ''), initialized = useRef(false);
  const step = overview?.steps.find(item => item.id === stepId) || null;
  useEffect(() => { const timer = setTimeout(() => { setOrderSearch(orderQ); setOrderPage(1); }, 300); return () => clearTimeout(timer); }, [orderQ]);
  useEffect(() => {
    if (!first) return;
    let active = true;
    qualityRequest<Orders>('orders?' + new URLSearchParams({ q: orderSearch, page: String(orderPage) })).then(value => { if (!active) return; setOrders(value); if (!initialized.current && !initialRecordId) { initialized.current = true; setOrderId(value.items[0]?.id || ''); } }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [first, orderSearch, orderPage, initialRecordId]);
  useEffect(() => {
    if (!initialRecordId) return; let active = true;
    qualityRequest<QualityRecord>('records/' + initialRecordId).then(value => { if (!active || value.type !== type) return; initialized.current = true; setOrderId(value.workOrderId || ''); setStepId(value.inspectionStepId || 'legacy'); setDeleted(Boolean(value.deletedAt)); setSelected(value); setDate(beijingInput(value.inspectedAt).slice(0, 10)); if (!first) setDay(beijingInput(value.inspectedAt).slice(0, 10)); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [initialRecordId, first, type]);
  useEffect(() => {
    if (!first || !orderId) { setOverview(null); return; } let active = true;
    qualityRequest<FirstOverview>('first-steps/' + orderId).then(value => { if (!active) return; setOverview(value); setStepId(previous => previous === 'legacy' || value.steps.some(item => item.id === previous) ? previous : value.steps.find(item => isFirstInspectionProcess(item.name))?.id || value.steps[0]?.id || 'legacy'); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [first, orderId, refresh]);
  const range = new URLSearchParams({ period, date, startDate: start, endDate: end, q: search, deleted: deleted ? '1' : '0' }).toString();
  useEffect(() => {
    if (first) return; let active = true;
    qualityRequest<Array<{ date: string; count: number }>>('archive-days?' + range).then(value => { if (active) setDays(value); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [first, range, refresh]);
  const params = new URLSearchParams(range); params.set('type', type); params.set('page', String(page));
  if (first) { params.set('workOrderId', orderId); if (stepId === 'legacy') params.set('unassignedStep', '1'); else params.set('inspectionStepId', stepId); }
  if (!first && day) { params.set('period', 'today'); params.set('date', day); }
  const query = params.toString();
  useEffect(() => {
    if (first && (!orderId || !stepId)) { setRecords({ total: 0, page: 1, items: [] }); setSelected(null); return; }
    let active = true; setLoading(true);
    qualityRequest<Records>('records?' + query).then(value => { if (!active) return; setRecords(value); setSelected(value.items.find(item => item.id === preferred.current) || value.items[0] || null); if (!value.items.length && page > 1) setPage(1); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [first, orderId, stepId, query, refresh, page]);
  function filter(action: () => void) { requestPreviewLeave(() => { preferred.current = ''; action(); setPage(1); setError(''); }); }
  function changed(record: QualityRecord) { preferred.current = record.id; setSelected(record); setRefresh(value => value + 1); }
  function create() { if(!user.access.capabilities.includes('QUALITY_DATA:CREATE'))return; if (first && (!overview || !step || step.retired)) { setError('请先选择当前工单的有效工序'); return; } requestPreviewLeave(() => setEditor({})); }
  async function exportRecords(format: 'xlsx' | 'zip') { setExporting(true); setError(''); try { await downloadQuality('export?' + query + '&format=' + format, QUALITY_LABELS[type] + (format === 'xlsx' ? '.xlsx' : '.zip')); } catch (e) { setError(e instanceof Error ? e.message : '导出失败'); } finally { setExporting(false); } }
  const matchingSteps = overview?.steps.filter(item => (allSteps || stepQ || isFirstInspectionProcess(item.name) || item.count || !overview.steps.some(s => isFirstInspectionProcess(s.name))) && (!stepQ || (String(item.position || '').padStart(2, '0') + ' ' + item.name).includes(stepQ))) || [];
  return <main className={"hm-workbench-root qd-root qp-root" + (!first ? " qp-patrol" : "")}>
    <AppWorkbenchHeader user={user} activeHref="/workspace/quality/data" subtitle="" menuItems={[]} hideHeader sidebarTriggerTargetId="qp-sidebar-trigger"/>
    <div className="qp-workbench"><header className="qp-page-head"><div><span id="qp-sidebar-trigger"/><span className="qd-logo"><ClipboardCheck size={22}/></span><div><h1>质量数据</h1><small>{first ? '产品检验 · 记录随工序留存' : '品质巡检 · 纸质报表归档'}</small></div><nav><button className="active"><ClipboardCheck size={15}/>检验记录</button><button onClick={onReferences}><BookOpen size={15}/>参考数据</button></nav></div><div><button aria-label="刷新记录" onClick={() => requestPreviewLeave(() => setRefresh(value => value + 1))} disabled={loading}><RefreshCw size={17}/></button><details className="qd-more-menu"><summary><Download size={16}/>导出记录</summary><div><button disabled={exporting} onClick={() => void exportRecords('xlsx')}>导出 Excel</button><button disabled={exporting} onClick={() => void exportRecords('zip')}>打包原始附件</button></div></details><button className="qd-primary" disabled={!user.access.capabilities.includes('QUALITY_DATA:CREATE')} onClick={create}><Plus size={18}/>{first ? '登记首件检验' : '上传巡检报表'}</button></div></header>
      <nav className="qd-type-bar qp-type-bar" aria-label="检验类型"><button onClick={() => requestPreviewLeave(() => onTypeChange(''))}>全部类型</button>{QUALITY_DATA_TYPES.map(value => <button className={type === value ? 'active' : ''} key={value} onClick={() => requestPreviewLeave(() => onTypeChange(value))}>{QUALITY_LABELS[value]}</button>)}</nav>
      {error && <div role="alert" className="qd-alert error">{error}<button onClick={() => setError('')}>关闭</button></div>}
      <div className="qp-filter"><CalendarDays size={17}/><select aria-label="检验日期范围" value={period} onChange={e => filter(() => { setPeriod(e.target.value); setDay(''); })}>{first && <option value="all">全部日期</option>}<option value="today">日</option><option value="week">周</option><option value="month">月</option><option value="custom">自定义</option></select>{period !== 'all' && (period === 'custom' ? <><input aria-label="开始日期" type="date" value={start} onInput={e=>{const value=e.currentTarget.value;filter(()=>{setStart(value);setDay('');});}} onChange={e => filter(() => { setStart(e.target.value); setDay(''); })}/><input aria-label="结束日期" type="date" value={end} onInput={e=>{const value=e.currentTarget.value;filter(()=>{setEnd(value);setDay('');});}} onChange={e => filter(() => { setEnd(e.target.value); setDay(''); })}/></> : <input type="date" aria-label="基准日期" value={date} onInput={e=>{const value=e.currentTarget.value;filter(()=>{setDate(value);setDay('');});}} onChange={e => filter(() => { setDate(e.target.value); setDay(''); })}/>)}<form onSubmit={e => { e.preventDefault(); filter(() => { setSearch(q); setDay(''); }); }}><Search size={17}/><input aria-label="搜索检验记录" placeholder={first ? '搜索检验人、说明或记录' : '搜索报表、区域或上传人'} value={q} onChange={e => setQ(e.target.value)}/><button>查询</button></form><button className={deleted ? 'active' : ''} onClick={() => filter(() => setDeleted(!deleted))}><Trash2 size={16}/>回收站</button></div>
      <div className="qp-grid">{first && <aside className="qp-primary-list">{first ? <><div className="qp-panel-title"><b>产品 / 工单</b><small>{orders.total}</small></div><div className="qp-list-search"><Search size={15}/><input aria-label="搜索产品工单" placeholder="型号、工单、客户" value={orderQ} onChange={e => setOrderQ(e.target.value)}/></div><div className="qp-scroll">{orders.items.map(item => <button key={item.id} className={'qp-order ' + (item.id === orderId ? 'active' : '')} onClick={() => filter(() => { setOverview(null); setOrderId(item.id); setStepId(''); })}><small>{item.customerName || '客户未填写'}</small><strong>{item.specification || item.productName}</strong><span>{item.productName}</span><span>{item.businessCode || item.code}</span><footer>{item.batchNo ? '第 ' + item.batchNo + ' 批' : '生产工单'}</footer></button>)}{!orders.items.length && <p className="qp-muted">没有匹配的工单</p>}</div><div className="qd-pagination"><button disabled={orderPage <= 1} onClick={() => setOrderPage(value => value - 1)}>上一页</button><span>{orderPage}</span><button disabled={orderPage * 20 >= orders.total} onClick={() => setOrderPage(value => value + 1)}>下一页</button></div></> : <><div className="qp-panel-title"><b>巡检日期</b><CalendarDays size={17}/></div><button className={'qp-day ' + (!day ? 'active' : '')} onClick={() => filter(() => setDay(''))}><b>全部日期</b><small>{days.reduce((sum, item) => sum + item.count, 0)} 份报表</small></button><div className="qp-scroll">{days.map(item => <button className={'qp-day ' + (day === item.date ? 'active' : '')} key={item.date} onClick={() => filter(() => setDay(item.date))}><b>{item.date.slice(5).replace('-', ' 月 ')} 日</b><span>{item.date === today ? '今天 · ' : ''}{item.count} 份报表</span></button>)}{!days.length && <p className="qp-muted">当前日期范围没有报表</p>}</div><p className="qp-muted">一份报表可包含多个产品</p></>}</aside>}
        <section className="qp-secondary-list">{first && <><div className="qp-panel-title"><div><b>首件检验工序</b><small>{overview?.order.specification || overview?.order.productName || '选择工单'}</small></div><button className="qp-text-button" onClick={() => setAllSteps(!allSteps)}>{allSteps ? '收起' : '全部工序'}</button></div>{(allSteps || (overview?.steps.length || 0) > 12) && <div className="qp-list-search"><Search size={15}/><input aria-label="搜索工序" placeholder="搜索工序名称或序号" value={stepQ} onChange={e => setStepQ(e.target.value)}/></div>}<div className="qp-step-list">{matchingSteps.map(item => <button className={'qp-step ' + (stepId === item.id ? 'active' : '')} key={item.id} onClick={() => filter(() => setStepId(item.id))}><span className="qp-sequence">{String(item.position || '').padStart(2, '0')}</span><div><b>{item.name}</b><small>{item.retired ? '历史工序' : item.count + ' 份记录'}</small></div><span className={'qd-badge ' + (item.result?.toLowerCase() || 'pending')}>{item.result ? RESULT_LABELS[item.result as keyof typeof RESULT_LABELS] : '待首件'}</span></button>)}{!!overview?.unassignedCount && <button className={'qp-step ' + (stepId === 'legacy' ? 'active' : '')} onClick={() => filter(() => setStepId('legacy'))}><HistoryLabel/><div><b>历史未指定工序</b><small>{overview.unassignedCount} 份 · 保留原始记录</small></div></button>}</div></>}
          <div className="qp-panel-title"><b>{deleted ? '回收站' : '巡检报表'}</b><small>{loading ? '加载中…' : records.total + ' 份'}</small></div>
          {!first && <div className="qp-archive-select"><CalendarDays size={16}/><select aria-label="按巡检日期筛选" value={day} onChange={e => filter(() => setDay(e.target.value))}><option value="">范围内全部日期</option>{days.map(item => <option key={item.date} value={item.date}>{item.date} · {item.count} 份</option>)}</select></div>}
          <div className="qp-scroll" aria-busy={loading}>{first ? records.items.map(item => <button key={item.id} className={'qp-record ' + (selected?.id === item.id ? 'active' : '')} onClick={() => requestPreviewLeave(() => { preferred.current = item.id; setSelected(item); })}><div><b>{beijingInput(item.inspectedAt).slice(5).replace('T', ' ')}</b><span className={'qd-badge ' + item.result.toLowerCase()}>{item.deletedAt ? '已作废' : item.status === 'DRAFT' ? '草稿' : RESULT_LABELS[item.result]}</span></div><span>{item.data.context.inspectedBy || item.createdByName}</span><footer>{item.attachments.filter(file => !file.deletedAt).length} 份照片 / 文件</footer></button>) : [...new Set(records.items.map(item => beijingInput(item.inspectedAt).slice(0, 10)))].map(groupDate => {
            const items = records.items.filter(item => beijingInput(item.inspectedAt).slice(0, 10) === groupDate);
            const collapsed = collapsedDays.has(groupDate);
            return <section className="qp-date-group" key={groupDate}><button className="qp-date-toggle" aria-expanded={!collapsed} onClick={() => setCollapsedDays(previous => { const next = new Set(previous); if(next.has(groupDate)) next.delete(groupDate); else next.add(groupDate); return next; })}><ChevronDown size={16} style={{transform: collapsed ? 'rotate(-90deg)' : undefined}}/><b>{groupDate.slice(5).replace('-', '月')}日</b><small>{items.length} 份{records.total > 20 ? ' · 本页' : ''}</small></button>{!collapsed && items.map(item => <button key={item.id} aria-current={selected?.id === item.id ? 'true' : undefined} className={'qp-record qp-patrol-record ' + (selected?.id === item.id ? 'active' : '')} onClick={() => requestPreviewLeave(() => { preferred.current = item.id; setSelected(item); })}><strong>{item.data.paper?.area ? item.data.paper.area + ' · ' : ''}{item.title}</strong><div><span>{item.data.context.inspectedBy || item.createdByName} · {item.attachments.filter(file => !file.deletedAt).length} 份附件</span><span className={'qd-badge ' + (item.deletedAt ? 'fail' : 'pending')}>{item.deletedAt ? '已作废' : item.status === 'DRAFT' ? '草稿' : '已归档'}</span></div></button>)}</section>;
          })}{!loading && !records.items.length && <p className="qp-muted">{first ? '本工序还没有检验记录' : '当前范围暂无巡检报表'}</p>}</div>
          {(first || records.total > 20) && <div className="qd-pagination"><button disabled={page <= 1 || loading} onClick={() => requestPreviewLeave(() => setPage(value => value - 1))}>上一页</button><span>{page} / {Math.max(1, Math.ceil(records.total / 20))}</span><button disabled={page * 20 >= records.total || loading} onClick={() => requestPreviewLeave(() => setPage(value => value + 1))}>下一页</button></div>}{first && !deleted && user.access.capabilities.includes('QUALITY_DATA:CREATE') && <button className="qp-list-add" onClick={create}><Plus size={16}/>登记本工序首件</button>}</section>
        <div className="qp-preview-pane">{selected ? <QualityPaperDetail record={selected} user={user} onChanged={changed} onEdit={() => setEditor({ record: selected })}/> : <div className="qp-empty"><ClipboardCheck size={42}/><h2>{loading ? '正在读取检验记录' : first ? '这道工序还没有首件记录' : '当前范围暂无巡检报表'}</h2><p>{first ? overview?.order.specification || '选择工单和工序开始登记' : '拍摄纸质巡检报表，按检验日期保存'}</p>{!deleted && <button className="qd-primary" onClick={create}><Plus size={17}/>{first ? '登记首件检验' : '上传巡检报表'}</button>}</div>}</div>
      </div>
    </div>{editor && <div className="qd-modal qp-modal" role="dialog" aria-modal="true" aria-label={QUALITY_LABELS[type] + '登记'}><QualityPaperEditor user={user} type={type} order={overview?.order || editor.record?.orderSnapshot} step={step || editor.record?.inspectionStepSnapshot} record={editor.record} onClose={() => setEditor(null)} onSaved={(record, done) => { if (done) { setEditor(null); changed(record); } else setSelected(record); }}/></div>}
  </main>;
}
function HistoryLabel() { return <ClipboardCheck size={20}/>; }
