'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { BookOpen, ClipboardCheck, Download, Plus, RefreshCw, Search, X } from 'lucide-react';
import type { CurrentUserDTO } from '@/types';
import { AppWorkbenchHeader } from '@/components/layout/AppWorkbenchHeader';
import { GlassNotice } from '@/components/GlassNotice';
import { PlanWeekFilter } from '@/components/PlanWeekFilter';
import { requestPreviewLeave } from '@/components/DocumentOrientation';
import { beijingInput, QUALITY_DATA_TYPES, QUALITY_LABELS, RESULT_LABELS, type QualityRecord, type QualityInspectionStep } from '@/lib/quality-data';
import { firstTime, type FirstOrders, type FirstRecords, type FirstRecord } from '@/lib/quality-first-types';
import type { FirstOverview } from './QualityPaperWorkbench';
import QualityPaperDetail from './QualityPaperDetail';
import QualityPaperEditor from './QualityPaperEditor';
import { downloadQuality, qualityRequest } from './client';
import './quality-paper.css';
import './quality-first.css';

export default function QualityFirstWorkbench({ user, initialRecordId, onTypeChange, onReferences }: { user: CurrentUserDTO; initialRecordId?: string; onTypeChange: (type: string) => void; onReferences: () => void }) {
  const [mode, setMode] = useState<'orders' | 'recent'>('orders'), [completion, setCompletion] = useState('ALL');
  const [q, setQ] = useState(''), [search, setSearch] = useState(''), [week, setWeek] = useState(''), [mine, setMine] = useState(false);
  const [period, setPeriod] = useState('all'), [timeField, setTimeField] = useState('upload'), [date, setDate] = useState(beijingInput().slice(0, 10)), [start, setStart] = useState(beijingInput().slice(0, 10)), [end, setEnd] = useState(beijingInput().slice(0, 10));
  const [result, setResult] = useState(''), [draft, setDraft] = useState(false), [deleted, setDeleted] = useState(false);
  const [orders, setOrders] = useState<FirstOrders>({ items: [], total: 0, page: 1, counts: { all: 0, done: 0, todo: 0 } });
  const [records, setRecords] = useState<FirstRecords>({ items: [], total: 0, page: 1 });
  const [orderId, setOrderId] = useState(''), [orderPage, setOrderPage] = useState(1), [page, setPage] = useState(1), [step, setStep] = useState('');
  const [overview, setOverview] = useState<FirstOverview | null>(null), [selected, setSelected] = useState<FirstRecord | null>(null), [pinned, setPinned] = useState(initialRecordId || '');
  const [refresh, setRefresh] = useState(0), [loading, setLoading] = useState(false), [ordersLoading, setOrdersLoading] = useState(false), [exporting, setExporting] = useState(false);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [chooser, setChooser] = useState(false), [newStep, setNewStep] = useState('');
  const [editor, setEditor] = useState<{ record?: QualityRecord; step?: QualityInspectionStep } | null>(null);
  const [initializing, setInitializing] = useState(Boolean(initialRecordId));
  const preferred = useRef(initialRecordId || '');
  const clearNotice = useCallback(() => setNotice(''), []), clearError = useCallback(() => setError(''), []);
  const canCreate = user.access.capabilities.includes('QUALITY_DATA:CREATE');
  const base = new URLSearchParams({ q: search, completion, week, mine: mine ? '1' : '0', period: completion === 'TODO' ? 'all' : period, timeField, date, startDate: start, endDate: end, result, draft: draft ? '1' : '0', deleted: deleted ? '1' : '0' }).toString();
  const orderQuery = base + '&page=' + orderPage;
  const query = base + '&page=' + page + (mode === 'orders' ? '&workOrderId=' + encodeURIComponent(orderId) + '&step=' + encodeURIComponent(step) : '');

  useEffect(() => { const timer = setTimeout(() => { if (q !== search) requestPreviewLeave(() => { setSearch(q); setMode(q ? 'recent' : 'orders'); setPage(1); setOrderPage(1); setPinned(''); setSelected(null); preferred.current = ''; }); }, 350); return () => clearTimeout(timer); }, [q, search]);
  useEffect(() => {
    if (!initialRecordId) return; let active = true;
    qualityRequest<QualityRecord>('records/' + initialRecordId).then(r => { if (!active) return; setOrderId(r.workOrderId || ''); setDeleted(Boolean(r.deletedAt)); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setInitializing(false); });
    return () => { active = false; };
  }, [initialRecordId]);
  useEffect(() => {
    let active = true; setOrdersLoading(true);
    qualityRequest<FirstOrders>('first-orders?' + orderQuery).then(value => { if (!active) return; setOrders(value); if (!pinned && mode === 'orders') setOrderId(previous => value.items.some(o => o.id === previous) ? previous : value.items[0]?.id || ''); if (value.total && orderPage > Math.ceil(value.total / 20)) setOrderPage(1); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setOrdersLoading(false); });
    return () => { active = false; };
  }, [orderQuery, refresh, pinned, mode, orderPage]);
  useEffect(() => {
    if (!orderId) { setOverview(null); return; } let active = true;
    qualityRequest<FirstOverview>('first-steps/' + orderId).then(value => { if (active) setOverview(value); }).catch(e => { if (active) { setOverview(null); setError(e.message); } });
    return () => { active = false; };
  }, [orderId, refresh]);
  useEffect(() => {
    if (initializing || (mode === 'orders' && !orderId)) { setRecords({ items: [], total: 0, page: 1 }); if (!pinned) setSelected(null); return; }
    let active = true; setLoading(true);
    qualityRequest<FirstRecords>('first-records?' + query).then(value => { if (!active) return; setRecords(value); if (!pinned) { const record = value.items.find(r => r.id === preferred.current) || value.items[0] || null; setSelected(record); if (mode === 'recent') setOrderId(record?.workOrderId || ''); } if (!value.items.length && page > 1) setPage(1); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [query, refresh, initializing, mode, orderId, pinned, page]);
  useEffect(() => {
    if (!pinned || initializing) return; let active = true;
    qualityRequest<FirstRecords>('first-records?' + new URLSearchParams({ recordId: pinned, deleted: deleted ? '1' : '0', period: 'all' })).then(value => { if (active && value.items[0]) setSelected(value.items[0]); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [pinned, refresh, initializing, deleted]);
  function change(action: () => void, resetOrders = true) { requestPreviewLeave(() => { const url = new URL(window.location.href); url.searchParams.delete('recordId'); window.history.replaceState(null, '', url); action(); setPage(1); if (resetOrders) setOrderPage(1); setPinned(''); preferred.current = ''; setSelected(null); setError(''); }); }
  function remember(record: QualityRecord) { const url = new URL(window.location.href); url.searchParams.set('type', 'FIRST'); url.searchParams.set('recordId', record.id); window.history.replaceState(null, '', url); }
  function choose(record: FirstRecord) { requestPreviewLeave(() => { setSelected(record); setOrderId(record.workOrderId || ''); setPinned(record.id); preferred.current = record.id; remember(record); }); }
  function changed(record: QualityRecord) { setPinned(record.id); preferred.current = record.id; setDeleted(Boolean(record.deletedAt)); setOrderId(record.workOrderId || ''); setSelected(previous => ({ ...record, activity: previous?.id === record.id ? previous.activity : { firstUploadedAt: null, lastUploadedAt: null, uploadedBy: '', changedAt: record.updatedAt } })); setRefresh(v => v + 1); remember(record); }
  function create() { requestPreviewLeave(() => { if (!overview || overview.order.id !== orderId) { setError('请先选择工单'); return; } setNewStep(overview.steps.some(s => s.id === step && !s.retired) ? step : ''); setChooser(true); }); }
  function clearFilters() { change(() => { setMode('orders'); setQ(''); setSearch(''); setCompletion('ALL'); setWeek(''); setMine(false); setPeriod('all'); setResult(''); setDraft(false); setDeleted(false); setStep(''); }); }
  async function exportRecords(format: string) { setExporting(true); try { await downloadQuality('first-export?' + query + '&format=' + format, '首件检验.' + (format === 'zip' ? 'zip' : 'xlsx')); } catch (e) { setError(e instanceof Error ? e.message : '导出失败'); } finally { setExporting(false); } }
  const activeOrder = orders.items.find(o => o.id === orderId);
  const outsideQueue = Boolean(pinned && selected && !records.items.some(r => r.id === selected.id));
  return <main className="hm-workbench-root qd-root qp-root qfirst">
    <AppWorkbenchHeader user={user} activeHref="/workspace/quality/data" subtitle="" menuItems={[]} hideHeader sidebarTriggerTargetId="qfirst-sidebar" />
    <div className="qp-workbench">
      <header className="qfirst-header"><div><span id="qfirst-sidebar"/><ClipboardCheck size={21}/><h1>质量数据</h1><span className="qfirst-divider"/><b>首件检验</b></div><div><button onClick={() => requestPreviewLeave(onReferences)}><BookOpen size={15}/><span>参考数据</span></button><button aria-label="刷新首件记录" onClick={() => requestPreviewLeave(() => setRefresh(v => v + 1))}><RefreshCw size={16}/></button><details className="qfirst-pop"><summary><Download size={15}/>导出</summary><div><button disabled={exporting || !records.total} onClick={() => void exportRecords('xlsx')}>导出筛选记录 Excel</button><button disabled={exporting || !records.total} onClick={() => void exportRecords('zip')}>打包筛选附件</button><button onClick={() => change(() => { setDeleted(!deleted); setMode('recent'); setCompletion('ALL'); })}>{deleted ? '返回有效记录' : '回收站'}</button></div></details><button className="qd-primary" disabled={!canCreate || !overview || overview.order.id !== orderId} onClick={create}><Plus size={17}/>登记首件</button></div></header>
      <nav className="qd-type-bar qp-type-bar" aria-label="检验类型"><button onClick={() => requestPreviewLeave(() => onTypeChange(''))}>全部类型</button>{QUALITY_DATA_TYPES.map(t => <button key={t} className={t === 'FIRST' ? 'active' : ''} onClick={() => requestPreviewLeave(() => onTypeChange(t))}>{QUALITY_LABELS[t]}</button>)}</nav>
      <div className="qfirst-filters"><div className="qfirst-segments" role="group" aria-label="首件登记完成状态">{[['ALL', '全部', orders.counts.all], ['TODO', '未完成', orders.counts.todo], ['DONE', '已完成', orders.counts.done]].map(([v, label, count]) => <button key={v} aria-pressed={completion === v} onClick={() => change(() => { setCompletion(String(v)); if (v === 'TODO') { setPeriod('all'); setMine(false); setResult(''); setDraft(false); setDeleted(false); } })}>{label}<small>{count}</small></button>)}</div><label className="qfirst-search"><Search size={16}/><input aria-label="搜索首件工单和记录" value={q} placeholder="型号、工单、客户、检验人或文件" onChange={e => setQ(e.target.value)}/></label><PlanWeekFilter compact value={week} onChange={v => change(() => setWeek(v))}/><details className="qfirst-pop"><summary>更多筛选{mine || period !== 'all' || result || draft ? ' · 已启用' : ''}</summary><div className="qfirst-filter-pop"><label>检验结果<select aria-label="首件检验结果" value={result} onChange={e => change(() => setResult(e.target.value))}><option value="">全部结果</option>{Object.entries(RESULT_LABELS).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label><input type="checkbox" checked={draft} onChange={e => change(() => setDraft(e.target.checked))}/>只看草稿</label><label>日期口径<select aria-label="首件日期口径" disabled={completion === 'TODO'} value={timeField} onChange={e => change(() => setTimeField(e.target.value))}><option value="upload">最近上传时间</option><option value="inspectedAt">实际检验时间</option></select></label><label>日期范围<select aria-label="首件日期范围" disabled={completion === 'TODO'} value={period} onChange={e => change(() => setPeriod(e.target.value))}><option value="all">全部日期</option><option value="today">日</option><option value="week">周</option><option value="month">月</option><option value="custom">自定义</option></select></label>{period !== 'all' && (period === 'custom' ? <><input aria-label="首件开始日期" type="date" value={start} onChange={e => change(() => setStart(e.target.value))}/><input aria-label="首件结束日期" type="date" value={end} onChange={e => change(() => setEnd(e.target.value))}/></> : <input type="date" aria-label="首件基准日期" value={date} onChange={e => change(() => setDate(e.target.value))}/>)}<small>{completion === 'TODO' ? '未完成工单按计划周查询，不使用上传日期。' : '上传日期与实际检验日期分别筛选。'}</small></div></details><button onClick={clearFilters}>清除</button></div>
      <div className="qfirst-viewbar"><div className="qfirst-segments"><button aria-pressed={mode === 'orders'} onClick={() => change(() => setMode('orders'))}>按工单</button><button aria-pressed={mode === 'recent'} onClick={() => change(() => setMode('recent'))}>最近上传</button></div><label><input type="checkbox" checked={mine} onChange={e => change(() => { setMine(e.target.checked); setMode('recent'); if (e.target.checked) setCompletion('ALL'); })}/>我上传的</label><small>{deleted ? '回收站 · 作废记录不计入已完成' : completion === 'DONE' ? '已完成指已登记首件，检验结果另行显示' : mode === 'recent' ? '跨工单查看上传与补传记录' : '选择工单后，默认查看全部工序的首件记录'}</small>{outsideQueue && <button className="qfirst-next" onClick={() => change(() => { setOrderId(''); setStep(''); })}>已保存 · {completion === 'TODO' ? '下一条未完成' : '返回筛选结果'} →</button>}</div>
      <div className="qp-grid qfirst-grid">
        <aside className="qp-primary-list"><div className="qp-panel-title"><b>产品 / 工单</b><small>{ordersLoading ? '加载中' : orders.total + ' 项'}</small></div><div className="qp-scroll" aria-label="首件工单列表">{orders.items.map(o => <button className={'qp-order ' + (o.id === orderId ? 'active' : '')} key={o.id} onClick={() => change(() => { setOrderId(o.id); setMode('orders'); setStep(''); }, false)}><div><strong title={o.specification || o.productName}>{o.specification || o.productName}</strong><span className={'qfirst-state ' + (o.submittedCount ? 'done' : '')}>{o.submittedCount ? '已完成' : '未完成'}</span></div><span>{o.customerName || '客户未填写'} · {o.productName}</span><small>{o.businessCode || o.code}{o.batchNo ? ' · 第 ' + o.batchNo + ' 批' : ''}</small><footer><span>{o.completedSteps} 道已登记 · {o.submittedCount} 份{o.draftCount ? ' · 草稿 ' + o.draftCount : ''}</span><time>{o.lastUploadedAt ? '上传 ' + firstTime(o.lastUploadedAt) : '尚无上传'}</time></footer></button>)}{!ordersLoading && !orders.total && <div className="qp-empty"><b>没有符合筛选的工单</b><button onClick={clearFilters}>清除筛选</button></div>}</div><Pagination page={orderPage} total={orders.total} disabled={ordersLoading} change={v => requestPreviewLeave(() => { setOrderPage(v); setPage(1); setPinned(''); setOrderId(''); setStep(''); setSelected(null); preferred.current = ''; })}/></aside>
        <section className="qp-secondary-list"><div className="qp-panel-title"><b>{deleted ? '首件回收站' : mode === 'recent' ? '最近上传记录' : '首件检验记录'}</b><small>{loading ? '加载中' : records.total + ' 份'}</small></div>{mode === 'orders' && <select className="qfirst-step" aria-label="首件工序筛选" value={step} onChange={e => change(() => setStep(e.target.value), false)}><option value="">全部工序</option>{overview?.steps.map(s => <option key={s.id} value={s.id}>{s.position ? String(s.position).padStart(2, '0') + ' ' : ''}{s.name} · {s.count} 份{s.retired ? '（历史工序）' : ''}</option>)}{Boolean(overview?.unassignedCount) && <option value="legacy">历史未指定工序 · {overview?.unassignedCount} 份</option>}</select>}<div className="qp-scroll" aria-label="首件记录列表" aria-busy={loading}>{records.items.map(r => <button className={'qp-record ' + (selected?.id === r.id ? 'active' : '')} key={r.id} onClick={() => choose(r)}><div><b>{r.inspectionStepSnapshot?.name || '历史未指定工序'}</b><span className={'qd-badge ' + (r.status === 'DRAFT' ? 'pending' : r.result.toLowerCase())}>{r.deletedAt ? '已作废' : r.status === 'DRAFT' ? '草稿' : RESULT_LABELS[r.result]}</span></div>{mode === 'recent' && <strong>{r.orderSnapshot.specification || r.orderSnapshot.productName}<small>{r.orderSnapshot.businessCode || r.orderSnapshot.code}</small></strong>}<span>{r.activity.lastUploadedAt ? '上传 ' + firstTime(r.activity.lastUploadedAt) : r.data.mode === 'FORM' ? '在线记录 · 提交 ' + firstTime(r.submittedAt) : '尚未上传凭证'}</span><span>{r.activity.lastUploadedAt ? r.activity.uploadedBy : r.createdByName} · {r.attachments.filter(f => !f.deletedAt).length} 份附件</span><footer>检验 {firstTime(r.inspectedAt)}</footer></button>)}{!loading && !records.total && <div className="qp-empty"><ClipboardCheck size={26}/><b>{outsideQueue ? '记录已保存，右侧继续查看' : mode === 'recent' || search || period !== 'all' || result || mine || draft ? '当前筛选没有记录' : step ? '该工序暂无首件记录' : '该工单尚未登记首件'}</b>{step && <button onClick={() => change(() => setStep(''), false)}>查看全部工序</button>}{mode === 'orders' && activeOrder?.draftCount ? <small>有 {activeOrder.draftCount} 份草稿可继续上传</small> : null}</div>}</div><Pagination page={page} total={records.total} disabled={loading} change={v => { requestPreviewLeave(() => { setPage(v); setPinned(''); preferred.current = ''; }); }}/></section>
        <div className="qp-preview-pane">{selected ? <><div className="qfirst-times"><span>上传 {firstTime(selected.activity.lastUploadedAt)}</span><span>变更 {firstTime(selected.activity.changedAt)}</span><details className="qfirst-pop"><summary>时间详情</summary><div><span>首次上传：{firstTime(selected.activity.firstUploadedAt)}</span><span>最近上传：{firstTime(selected.activity.lastUploadedAt)}</span><span>上传人：{selected.activity.lastUploadedAt ? selected.activity.uploadedBy || '未记录' : '未记录'}</span><span>正式提交：{firstTime(selected.submittedAt)}</span><span>实际检验：{firstTime(selected.inspectedAt)}</span><span>最近变更：{firstTime(selected.updatedAt)}</span></div></details></div><QualityPaperDetail record={selected} user={user} onChanged={changed} onEdit={() => setEditor({ record: selected })}/></> : <div className="qp-empty"><ClipboardCheck size={36}/><h2>{loading ? '正在读取首件记录' : '选择记录查看检验凭证'}</h2><p>{overview?.order.specification || '可从已完成或最近上传快速查找'}</p>{canCreate && overview && <button className="qd-primary" onClick={create}>登记首件检验</button>}</div>}</div>
      </div>
    </div>
    <GlassNotice message={error || notice} error={Boolean(error)} close={error ? clearError : clearNotice}/>
    {chooser && <div className="qd-modal qp-modal" role="dialog" aria-modal="true" aria-label="选择首件登记工序"><section className="qfirst-chooser"><header><h2>登记首件检验</h2><button aria-label="关闭工序选择" onClick={() => setChooser(false)}><X size={18}/></button></header><p>{overview?.order.specification || overview?.order.productName}</p><small>{overview?.order.businessCode || overview?.order.code}</small><label>所属工序<select aria-label="登记所属工序" value={newStep} onChange={e => setNewStep(e.target.value)}><option value="">请选择工序</option>{overview?.steps.filter(s => !s.retired).map(s => <option key={s.id} value={s.id}>{s.position} · {s.name}</option>)}</select></label>{!overview?.steps.some(s => !s.retired) && <p>该工单尚无有效工序，请先完善工艺路线。</p>}<footer><button onClick={() => setChooser(false)}>取消</button><button className="qd-primary" disabled={!overview?.steps.some(s => s.id === newStep && !s.retired)} onClick={() => { setChooser(false); setEditor({ step: overview?.steps.find(s => s.id === newStep) }); }}>继续登记</button></footer></section></div>}
    {editor && <div className="qd-modal qp-modal" role="dialog" aria-modal="true" aria-label="首件检验登记"><QualityPaperEditor type="FIRST" user={user} record={editor.record} order={editor.record?.orderSnapshot || overview?.order} step={editor.record?.inspectionStepSnapshot || editor.step} onClose={() => { setEditor(null); setRefresh(v => v + 1); }} onSaved={(record, done) => { changed(record); if (done) { setEditor(null); setNotice('首件记录已保存，正在显示本次上传资料'); } }}/></div>}
  </main>;
}

function Pagination({ page, total, disabled, change }: { page: number; total: number; disabled: boolean; change: (page: number) => void }) {
  return <div className="qd-pagination"><button disabled={disabled || page <= 1} onClick={() => change(page - 1)}>上一页</button><span>{page} / {Math.max(1, Math.ceil(total / 20))}</span><button disabled={disabled || page * 20 >= total} onClick={() => change(page + 1)}>下一页</button></div>;
}
