'use client';
/* Authenticated original images must be fetched with the viewer's session cookie. */
/* eslint-disable @next/next/no-img-element */
import { useState } from 'react';
import { Download, FileText, History, X } from 'lucide-react';
import { beijingInput } from '@/lib/quality-data';
import { REFERENCE_SOURCE, REFERENCE_STATUS, referenceConditions, type QualityReference } from '@/lib/quality-reference';
import { qualityRequest } from './client';
type Revision = { version:number;action:string;reason:string;actorName:string;createdAt:string };
export function ReferenceFacts({record,historyVersion}:{record:QualityReference;historyVersion?:number}) {
  const [preview,setPreview]=useState<{url:string;image:boolean;name:string}|null>(null);
  const d=record.data;
  function content(id:string){return '/api/quality-data/reference-files/'+id+'/content'+(historyVersion?'?historyVersion='+historyVersion:'');}
  return <><div className="qr-condition-strip">{referenceConditions(d)}</div><div className="qr-parameter-groups">{(['DIMENSION','MACHINE'] as const).map(group=><section key={group}><div className="qd-section-title"><b>{group==='DIMENSION'?'压接尺寸参考':'机器设定参数'}</b><span>{group==='DIMENSION'?'压接后的尺寸':'适用机台：'+(d.equipment||'未填写')}</span></div>{d.parameters.filter(p=>p.group===group).length?<div className="qr-value-grid">{d.parameters.filter(p=>p.group===group).map((p,i)=><article key={i}><span>{p.name}</span><strong>{p.value}<small>{p.unit}</small></strong>{p.tolerance&&<small>公差：{p.tolerance}</small>}{p.note&&<p>{p.note}</p>}</article>)}</div>:<p className="qd-help">本方案未记录{group==='DIMENSION'?'尺寸':'机器设定'}参数</p>}</section>)}</div><dl className="qd-detail-meta qr-meta">{[['资料来源',REFERENCE_SOURCE[d.source]],['依据',d.basis],['绝缘 / 并线说明',d.insulation],['验证人',d.verifiedBy],['验证时间',d.verifiedAt?beijingInput(d.verifiedAt).replace('T',' '):''],['创建人',record.createdByName]].filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{d.remark&&<div className="qd-summary"><b>备注</b><p>{d.remark}</p></div>}<div className="qd-section-title"><b>参考附件</b><span>{record.attachments.filter(f=>!f.deletedAt).length} 份</span></div><div className="qd-attachment-grid">{record.attachments.filter(f=>!f.deletedAt).map(file=><article key={file.id}><button className="qd-attachment-open" type="button" onClick={()=>{if(file.mimeType.startsWith('image/')||file.mimeType==='application/pdf')setPreview({url:content(file.id),image:file.mimeType.startsWith('image/'),name:file.originalName});else window.open(content(file.id),'_blank','noopener,noreferrer');}}><FileText size={28}/><b>{file.originalName}</b></button><a href={content(file.id)+(historyVersion?'&':'?')+'download=1'}><Download size={12}/>下载</a></article>)}</div>{!record.attachments.some(f=>!f.deletedAt)&&<p className="qd-help">可在编辑方案时补充机台照片或依据文件。</p>}{preview&&<div className="qd-preview-overlay" role="dialog" aria-label="参考附件预览"><header><b>{preview.name}</b><button onClick={()=>setPreview(null)} aria-label="关闭附件预览"><X size={20}/></button></header>{preview.image?<img src={preview.url} alt={preview.name}/>:<iframe src={preview.url} title={preview.name}/>}</div>}</>;
}
function differences(old:QualityReference,current:QualityReference){
  const pairs:(readonly [string,string,string])[]=[['方案名称',old.title,current.title],['状态',REFERENCE_STATUS[old.status],REFERENCE_STATUS[current.status]],['端子',old.terminalName,current.terminalName],['厂家',old.manufacturer,current.manufacturer],['适用条件',referenceConditions(old.data),referenceConditions(current.data)],['来源',REFERENCE_SOURCE[old.data.source],REFERENCE_SOURCE[current.data.source]],['依据',old.data.basis,current.data.basis],['备注',old.data.remark,current.data.remark]];
  const p=(r:QualityReference)=>r.data.parameters.map(x=>(x.group==='DIMENSION'?'尺寸':'机器')+' / '+x.name+'：'+x.value+' '+x.unit+(x.tolerance?' ±说明 '+x.tolerance:'')+(x.note?' · '+x.note:'')).join('\n');
  pairs.push(['参数',p(old),p(current)],['附件',old.attachments.filter(f=>!f.deletedAt).map(f=>f.originalName).join('\n'),current.attachments.filter(f=>!f.deletedAt).map(f=>f.originalName).join('\n')]);
  return pairs.filter(([,a,b])=>a!==b);
}
export default function QualityReferenceDetail({record}:{record:QualityReference}) {
  const [history,setHistory]=useState<Revision[]|null>(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[historical,setHistorical]=useState<QualityReference|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  async function loadHistory(next=1){setLoading(true);try{const data=await qualityRequest<{items:Revision[];total:number}>('references/'+record.id+'/revisions?page='+next);setHistory(data.items);setTotal(data.total);setPage(next);}catch(e){setError(e instanceof Error?e.message:'读取历史失败');}finally{setLoading(false);}}
  async function loadVersion(version:number){setLoading(true);try{setHistorical(await qualityRequest<QualityReference>('references/'+record.id+'/revisions/'+version));}catch(e){setError(e instanceof Error?e.message:'读取历史失败');}finally{setLoading(false);}}
  const shown=historical||record;
  return <><header className="qr-detail-head"><div><small>{shown.code} · V{shown.version}{historical?' · 历史版本':''}</small><h2>{shown.title}</h2><p>{shown.terminalName}{shown.manufacturer?' · '+shown.manufacturer:''}</p></div><span className={'qd-badge '+(shown.status==='ACTIVE'?'pass':'pending')}>{shown.deletedAt?'已删除':REFERENCE_STATUS[shown.status]}</span></header>{error&&<div role="alert" className="qd-alert error">{error}</div>}{historical&&<div className="qd-alert"><span>正在查看 V{historical.version}，当前为 V{record.version}</span><button onClick={()=>setHistorical(null)}>返回当前版本</button></div>}<ReferenceFacts key={shown.id+':'+shown.version} record={shown} historyVersion={historical?.version}/>{historical&&<section className="qr-compare"><h3>与当前版本比较</h3>{differences(historical,record).length?<table className="qd-measure-table"><thead><tr><th>内容</th><th>历史 V{historical.version}</th><th>当前 V{record.version}</th></tr></thead><tbody>{differences(historical,record).map(([name,old,current])=><tr key={name}><td>{name}</td><td>{old||'—'}</td><td>{current||'—'}</td></tr>)}</tbody></table>:<p className="qd-help">参数内容一致，操作记录见下方历史。</p>}</section>}<section className="qd-history"><button onClick={()=>history?setHistory(null):void loadHistory()} disabled={loading}><History size={16}/>修改历史 · 当前 V{record.version}</button>{history?.map(r=><button key={r.version} disabled={loading} onClick={()=>void loadVersion(r.version)}><strong>V{r.version} · {r.actorName} · {beijingInput(r.createdAt).replace('T',' ')}</strong><span>{r.reason}</span></button>)}{history&&<div className="qd-pagination"><button disabled={page<=1||loading} onClick={()=>void loadHistory(page-1)}>上一页</button><span>{page} / {Math.max(1,Math.ceil(total/20))}</span><button disabled={page*20>=total||loading} onClick={()=>void loadHistory(page+1)}>下一页</button></div>}</section></>;
}
