'use client';
import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Search, Send } from 'lucide-react';
import type { OrderPoolDTO } from '@/lib/order-pool-service';
import { poolPriority } from '@/lib/order-pool-domain';
import './OrderPoolTechnicalQueue.css';

type Data={orders:OrderPoolDTO[];total:number;page:number;pages:number;customers:string[]};
export function OrderPoolTechnicalQueue({selectedId,onSelect,canWrite,refreshKey}:{selectedId:string;onSelect:(itemId:string)=>void;canWrite:boolean;refreshKey?:string}){
 const [data,setData]=useState<Data|null>(null),[query,setQuery]=useState(''),[customer,setCustomer]=useState(''),[page,setPage]=useState(1),[status,setStatus]=useState('all'),[refresh,setRefresh]=useState(0),[selectedOrder,setSelectedOrder]=useState(''),[note,setNote]=useState(''),[clarify,setClarify]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const initial=useRef(false),scroll=useRef<HTMLDivElement>(null),request=useRef('');
 useEffect(()=>{try{const s=JSON.parse(sessionStorage.getItem('pool-technical-view')||'{}');setQuery(s.query||'');setCustomer(s.customer||'');setPage(s.page||1);setStatus(s.status||'all');setSelectedOrder(s.selectedOrder||'');}catch{}initial.current=true;},[]);
 useEffect(()=>{const abort=new AbortController();const timer=setTimeout(async()=>{try{const p=new URLSearchParams({q:query,customer,filter:status,page:String(page)});const r=await fetch('/api/order-pool?'+p,{cache:'no-store',signal:abort.signal}),b=await r.json();if(!r.ok||!b.ok)throw Error(b.error||'准备队列读取失败');if(!abort.signal.aborted){setData(b);setError('');}}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}},200);return()=>{clearTimeout(timer);abort.abort();};},[query,customer,page,status,refresh,refreshKey]);
 useEffect(()=>{const update=()=>{if(!document.hidden&&!saving)setRefresh(n=>n+1);};window.addEventListener('focus',update);const timer=setInterval(update,30000);return()=>{window.removeEventListener('focus',update);clearInterval(timer);};},[saving]);
 useEffect(()=>{if(initial.current)sessionStorage.setItem('pool-technical-view',JSON.stringify({query,customer,page,status,selectedOrder}));},[query,customer,page,status,selectedOrder]);
 useEffect(()=>{if(data&&scroll.current)scroll.current.scrollTop=Number(sessionStorage.getItem('pool-technical-scroll')||0);},[data]);
 const selected=data?.orders.find(o=>o.id===selectedOrder&&o.drawingLibraryItemId===selectedId)||data?.orders.find(o=>o.drawingLibraryItemId===selectedId);
 function choose(o:OrderPoolDTO){if(!o.drawingLibraryItemId)return;setSelectedOrder(o.id);setNote('');setClarify(false);request.current='';onSelect(o.drawingLibraryItemId);}
 async function send(){if(!selected||!note.trim()||saving)return;setSaving(true);setError('');try{request.current ||= crypto.randomUUID();const r=await fetch('/api/order-pool/'+selected.id+'/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note,clarify,requestKey:request.current})}),b=await r.json();if(!r.ok||!b.ok)throw Error(b.error||'保存失败');setNote('');request.current='';setClarify(false);setRefresh(n=>n+1);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <aside className="opt-queue" aria-label="订单池技术准备"><header><strong>订单池准备 <b>{data?.total??'—'}</b></strong><small>计划准备顺序</small></header><div className="opt-filters"><label><Search size={14}/><input aria-label="搜索技术准备订单" placeholder="规格 / 客户 / 订单号" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><select aria-label="技术准备客户" value={customer} onChange={e=>{setCustomer(e.target.value);setPage(1);}}><option value="">全部客户</option>{data?.customers.map(c=><option key={c}>{c}</option>)}</select><select aria-label="技术准备状态" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">全部待排</option><option value="documents">资料待准备</option><option value="clarify">待计划确认</option></select></div>{error&&<div className="opt-error" role="alert">{error}<button onClick={()=>setRefresh(n=>n+1)}>重试</button></div>}<div ref={scroll} className="opt-scroll" onScroll={e=>sessionStorage.setItem('pool-technical-scroll',String(e.currentTarget.scrollTop))}>{data?.orders.map(o=><button key={o.id} className={'opt-item '+(selected?.id===o.id?'active':'')} onClick={()=>choose(o)}><div><span className={'opt-priority '+o.priority}>{String(o.rank).padStart(2,'0')} · {poolPriority[o.priority as keyof typeof poolPriority]?.label||'常规'}</span><span className={o.documentsReady?'opt-ready':'opt-wait'}>{o.documentsReady?'已审核':o.drawingCount+o.sopCount?'待审核':'待上传'}</span></div><strong>{o.specification}</strong><small>{o.customerName} · {o.remaining} 套待排</small><small>{o.sourceOrderNo} / {o.sourceLineNo}</small>{o.note&&<p title={o.note}>{o.note}</p>}<footer><span>图纸 {o.drawingCount} · SOP {o.sopCount}</span><span>{o.preparationDueAt?o.preparationDueAt.slice(5)+' 前准备':'准备交期待定'}</span></footer></button>)}{data&&!data.orders.length&&<div className="opt-empty">当前筛选没有待排订单</div>}</div>{selected&&<div className="opt-progress">{selected.progress&&<p title={selected.progress}>{selected.progress}<small>{selected.progressBy} · {new Date(selected.progressAt).toLocaleString('zh-CN')}</small></p>}{canWrite&&<><div><input aria-label="技术准备进展" placeholder="补充准备进展…" value={note} onChange={e=>{setNote(e.target.value);request.current='';}}/><button aria-label="保存技术进展" disabled={!note.trim()||saving} onClick={send}><Send size={16}/></button></div><label><input type="checkbox" checked={clarify} onChange={e=>{setClarify(e.target.checked);request.current='';}}/>需要计划确认</label></>}</div>}<footer className="opt-pagination"><span>{data?.total??0} 项</span><button disabled={page<=1} aria-label="技术准备上一页" onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/></button><b>{page} / {data?.pages||1}</b><button disabled={page>=(data?.pages||1)} aria-label="技术准备下一页" onClick={()=>setPage(p=>p+1)}><ChevronRight size={15}/></button></footer></aside>;
}

