'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpRight, Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, FileText, GripVertical, Layers3, MoreHorizontal, PackageCheck, Pencil, Plus, Search, Upload, X } from 'lucide-react';
import type { CurrentUserDTO } from '@/types';
import type { OrderPoolDTO } from '@/lib/order-pool-service';
import { poolPriority } from '@/lib/order-pool-domain';
import { MaterialOrderDrawer } from '@/components/material/MaterialOrderDrawer';
import { useModalLayer } from '@/components/useModalLayer';
import './OrderPoolWorkbench.css';

type Queue={orders:OrderPoolDTO[];counts:Record<string,number>;totals:{remaining:number;milliseconds:number;missingTime:number};allTotal:number;total:number;page:number;pages:number;queueToken:string;customers:string[];currentWeek:string};
type ImportRow={line:number;input:Record<string,unknown>;action:string;id:string;version:string;error:string};
type Modal={kind:'create'|'edit'|'import'|'join'|'priority'|'move'|'cancel';rows:OrderPoolDTO[];key:string};
type Form=Record<string,string>;
const key=()=>crypto.randomUUID();
const day=(s:string)=>s?s.slice(5).replace('-','/'):'待确认';
const add=(s:string,n:number)=>{const d=new Date(s+'T12:00:00+08:00');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const minutes=(n:number|null)=>n==null?'待维护':Number((n/60000).toFixed(3)).toLocaleString();
async function json(url:string,options?:RequestInit){const r=await fetch(url,{cache:'no-store',...options});const b=await r.json();if(!r.ok||!b.ok)throw Object.assign(Error(b.error||'请求失败'),{status:r.status});return b;}
const post=(url:string,body:unknown)=>json(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
export function OrderPoolWorkbench({user,refreshToken=0,onChanged,onWeek}:{user:CurrentUserDTO;refreshToken?:number;onChanged:()=>void;onWeek:(week:string)=>void}){
 const [data,setData]=useState<Queue|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[customer,setCustomer]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('priority'),[page,setPage]=useState(1),[importIds,setImportIds]=useState<string[]>([]),[ready,setReady]=useState(false);
 const [selection,setSelection]=useState<OrderPoolDTO[]>([]),[refresh,setRefresh]=useState(0),[modal,setModal]=useState<Modal|null>(null),[form,setForm]=useState<Form>({}),[saving,setSaving]=useState(false),[importRows,setImportRows]=useState<ImportRow[]>([]),[updateExisting,setUpdateExisting]=useState(false),[fileName,setFileName]=useState(''),[joined,setJoined]=useState<string[]>([]),[materialId,setMaterialId]=useState('');
 const scroll=useRef<HTMLDivElement>(null),dialog=useRef<HTMLElement>(null),file=useRef<HTMLInputElement>(null);
 const canWrite=user.access.modulePermissions?.production!=='READ'&&user.access.capabilities.includes('PLANNING:UPDATE');
 useModalLayer({open:!!modal,layerRef:dialog,onClose:()=>{if(!saving)setModal(null);}});
 useEffect(()=>{try{const s=JSON.parse(sessionStorage.getItem('order-pool-view:'+user.id)||'{}');setSearch(s.q||'');setQuery(s.q||'');setCustomer(s.customer||'');setFilter(s.filter||'all');setSort(s.sort||'priority');setPage(s.page||1);}catch{}setReady(true);},[user.id]);
 useEffect(()=>{const t=setTimeout(()=>{if(query!==search.trim()){setQuery(search.trim());setPage(1);}},200);return()=>clearTimeout(t);},[search,query]);
 const reload=useCallback(()=>setRefresh(n=>n+1),[]);
 useEffect(()=>{if(!ready)return;const a=new AbortController();setLoading(true);const p=new URLSearchParams({q:query,customer,filter,sort,page:String(page)});if(importIds.length)p.set('ids',importIds.join(','));json('/api/order-pool?'+p,{signal:a.signal}).then(b=>{if(!a.signal.aborted){setData(b);setPage(b.page);setError('');}}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!a.signal.aborted)setLoading(false);});return()=>a.abort();},[ready,query,customer,filter,sort,page,importIds,refresh,refreshToken]);
 useEffect(()=>{if(ready)sessionStorage.setItem('order-pool-view:'+user.id,JSON.stringify({q:query,customer,filter,sort,page}));},[ready,query,customer,filter,sort,page,user.id]);
 useEffect(()=>{if(data&&scroll.current)scroll.current.scrollTop=Number(sessionStorage.getItem('order-pool-scroll:'+user.id)||0);},[data,user.id]);
 useEffect(()=>{const fn=()=>{if(!document.hidden&&!modal&&!saving)reload();};window.addEventListener('focus',fn);window.addEventListener('material-orders-changed',fn);const timer=setInterval(fn,30000);return()=>{window.removeEventListener('focus',fn);window.removeEventListener('material-orders-changed',fn);clearInterval(timer);};},[modal,saving,reload]);
 function choose(row:OrderPoolDTO,checked:boolean){setSelection(s=>checked?[...s.filter(x=>x.id!==row.id),row]:s.filter(x=>x.id!==row.id));}
 function open(kind:Modal['kind'],rows:OrderPoolDTO[]=[]){setError('');setModal({kind,rows,key:key()});setJoined([]);const row=rows[0];const week=data?.currentWeek||new Date().toISOString().slice(0,10);setForm({customerName:'',specification:'',productName:'',orderQuantity:row?String(row.orderQuantity):'',preparationQuantity:row?String(row.targetTotal):'',preparationDueAt:row?.preparationDueAt||'',customerDueDate:row?.customerDueDate||'',unitMinutes:(kind==='edit'?row?.planningUnitMilliseconds:row?.unitMilliseconds)?String((kind==='edit'?row!.planningUnitMilliseconds!:row!.unitMilliseconds!)/60000):'',orderDate:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'}),sourceOrderNo:'',sourceLineNo:'1',note:row?.note||'',priority:row?.priority||'normal',preparationState:row?.preparationState||'open',position:'1',week,completion:add(week,6),...Object.fromEntries(rows.map(o=>['qty:'+o.id,String(o.remaining)]))});if(kind==='import'){setImportRows([]);setFileName('');setUpdateExisting(false);}}
 function field(name:string){return{value:form[name]||'',onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(f=>({...f,[name]:e.target.value}))};}
 function goDrawings(o:OrderPoolDTO){const p=new URLSearchParams({scope:'pool',from:'planning',returnTo:'/weekly-plan-center?view=pool&restore=1',itemId:o.drawingLibraryItemId||''});return'/drawing-library?'+p;}
 async function upload(f:File){setSaving(true);setError('');setFileName(f.name);setImportRows([]);try{const body=new FormData();body.set('file',f);const b=await json('/api/order-pool/import',{method:'POST',body});setImportRows(b.rows);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!modal||saving)return;setSaving(true);setError('');try{
  if(modal.kind==='join'){
   const done=[...joined];for(const o of modal.rows){if(done.includes(o.id))continue;try{const b=await post('/api/planning/orders/'+o.id+'/batches',{requestKey:modal.key+':'+o.id,poolVersion:o.version,quantity:Number(form['qty:'+o.id]),weekStartDate:form.week,plannedCompletionDate:form.completion,...(form.unitMinutes&&modal.rows.length===1?{unitMilliseconds:Math.round(Number(form.unitMinutes)*60000)}:{})});done.push(o.id);setJoined([...done]);setNotice(`已加入 ${done.length}/${modal.rows.length} 项${b.automaticReleaseTarget?'，已同步周计划执行':'，下达状态可在周计划查看'}`);}catch(err){throw Error(`已加入 ${done.length}/${modal.rows.length} 项；${(err as Error).message}`);}}
   onChanged();reload();setSelection([]);return;
  }
  const row=modal.rows[0];const result=await post('/api/order-pool/commands',{requestKey:modal.key,action:modal.kind==='priority'?'priority':modal.kind,ids:modal.rows.map(o=>o.id),id:row?.id,versions:Object.fromEntries(modal.rows.map(o=>[o.id,o.version])),queueToken:data?.queueToken,
   ...(modal.kind==='create'?{row:{...form,preparationQuantity:form.preparationQuantity||form.orderQuantity}}:modal.kind==='import'?{rows:importRows,updateExisting}:{...form})});
  if(modal.kind==='import'||modal.kind==='create'){setImportIds(result.ids);setFilter('all');setCustomer('');setSearch('');setQuery('');setPage(1);setNotice(`新增 ${result.created} · 更新 ${result.updated} · 跳过 ${result.skipped}${result.errors?.length?' · 未导入 '+result.errors.length:''}`);}else setNotice('已保存 · 仓库与技术准备顺序同步');
  setModal(null);setSelection([]);reload();onChanged();
 }catch(err){setError((err as Error).message);}finally{setSaving(false);}}
 const picked=(o:OrderPoolDTO)=>selection.some(x=>x.id===o.id);
 const title=modal?({create:'新建订单池订单',edit:'调整准备要求',import:'导入订单池',join:'加入周计划',priority:'设置准备优先级',move:'调整准备顺序',cancel:'取消订单'}[modal.kind]):'';
 return <section className="op-workbench" aria-label="订单池准备工作区">
  <div className="op-toolbar"><nav aria-label="订单池状态">{[['all','全部待排'],['documents','资料待准备'],['materials','未齐料'],['ready','准备完成'],['clarify','待计划确认']].map(([k,l])=><button key={k} className={filter===k?'active':''} onClick={()=>{setFilter(k);setPage(1);}}>{l}<b>{data?.counts[k]??'—'}</b></button>)}</nav><div className="op-tools"><label className="op-search"><Search size={16}/><input aria-label="搜索订单池" placeholder="搜索规格、客户、订单号" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="订单池客户" value={customer} onChange={e=>{setCustomer(e.target.value);setPage(1);}}><option value="">全部客户</option>{data?.customers.map(c=><option key={c}>{c}</option>)}</select><select aria-label="订单池排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">计划准备顺序</option><option value="due">按客户交期查看</option></select><button disabled={!canWrite} onClick={()=>open('import')}><Upload size={15}/>导入订单池</button><button disabled={!canWrite} className="op-primary" onClick={()=>open('create')}><Plus size={16}/>新建订单</button></div></div>
  {(notice||importIds.length>0)&&<div className="op-feedback" role="status"><CheckCircle2 size={16}/>{notice}{importIds.length>0&&<><span>本次导入 {importIds.length} 项</span><button onClick={()=>{setImportIds([]);setNotice('');}}>查看全部<X size={13}/></button></>}</div>}
  {error&&!modal&&<div className="op-error" role="alert">{error}<button onClick={reload}>重试</button></div>}
  <div className="op-table-card"><div className="op-summary"><span><b>{data?.total.toLocaleString()??'—'}</b> 笔订单</span><span>待排 <b>{data?.totals.remaining.toLocaleString()??'—'}</b> 套</span><span>待排预计工时 <b>{data?(data.totals.milliseconds/3600000).toLocaleString(undefined,{maximumFractionDigits:2}):'—'}</b> h</span>{!!data?.totals.missingTime&&<em>{data.totals.missingTime} 项工时待维护</em>}<small>未排入周产能</small></div><div className="op-table-scroll" ref={scroll} onScroll={e=>sessionStorage.setItem('order-pool-scroll:'+user.id,String(e.currentTarget.scrollTop))}>
   <table className="op-table"><colgroup>{[3,5,21,9,7,10,10,8,14,13].map((width,i)=><col key={i} style={{width:width+'%'}}/>)}</colgroup><thead><tr><th><input type="checkbox" aria-label="选择本页订单" checked={!!data?.orders.length&&data.orders.every(picked)} onChange={e=>{const check=e.target.checked;setSelection(s=>check?[...s.filter(o=>!data?.orders.some(x=>x.id===o.id)),...data!.orders]:s.filter(o=>!data?.orders.some(x=>x.id===o.id)));}}/></th><th>准备序</th><th>客户 / 产品规格</th><th>待排 / 订单</th><th>客户交期</th><th>图纸资料</th><th>仓库配料</th><th>计划工时</th><th>最新进展</th><th>操作</th></tr></thead><tbody>{data?.orders.map(o=><tr key={o.id} className={picked(o)?'selected':''}>
    <td><input type="checkbox" aria-label={'选择 '+o.specification} checked={picked(o)} onChange={e=>choose(o,e.target.checked)}/></td><td><button disabled={!canWrite} className="op-rank" title="调整同优先级准备顺序" onClick={()=>open('move',[o])}><GripVertical size={13}/>{String(o.rank).padStart(2,'0')}</button><span className={'op-priority '+o.priority}>{poolPriority[o.priority as keyof typeof poolPriority]?.label||'常规'}</span></td>
    <td><strong className="op-spec" title={o.specification}>{o.specification}</strong><small>{o.customerName} · {o.productName}</small><small className="op-order-no">{o.sourceOrderNo} / {o.sourceLineNo}</small></td>
    <td><strong>{o.remaining.toLocaleString()}</strong><small>订单 {o.orderQuantity.toLocaleString()}{o.allocated>0?' · 已排 '+o.allocated:''}</small><small>待准备 {o.targetRemaining} 套</small></td><td><span className={!o.customerDueDate?'op-muted':''}>{day(o.customerDueDate)}</span></td>
    <td><a className={'op-status '+(o.documentsReady?'green':'amber')} href={goDrawings(o)}><FileText size={13}/>{o.documentsReady?'资料已审核':o.drawingCount+o.sopCount?'待资料审核':'待上传'}</a><small>图纸 {o.drawingCount} · SOP {o.sopCount}</small></td>
    <td><button className={'op-status '+(o.openCount?'red':o.readyRemaining>=o.targetRemaining&&o.targetRemaining>0?'green':'blue')} onClick={()=>setMaterialId(o.warehouseTaskId||'')}>{o.openCount?'缺料 '+o.openCount+' 项':o.targetRemaining===0?'待追加准备':o.readyRemaining>=o.targetRemaining?'准备齐全':o.readyRemaining?'部分齐料':'待核对'}<ChevronRight size={12}/></button><small>{o.targetRemaining===0?'原准备任务已转周计划':`已配 ${o.readyRemaining} / ${o.targetRemaining}`}</small></td>
    <td><span className={!o.unitMilliseconds?'op-muted':''}>{minutes(o.unitMilliseconds)}</span><small>{o.unitMilliseconds?'分钟 / 套':'尚未维护'}</small>{o.unitMilliseconds&&<small>待排 {(o.unitMilliseconds*o.remaining/3600000).toLocaleString(undefined,{maximumFractionDigits:2})} h</small>}</td><td><p className="op-progress-text" title={o.progress||o.note}>{o.progress||o.note||'—'}</p><small>{o.progressAt?new Date(o.progressAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):o.preparationDueAt?day(o.preparationDueAt)+' 前准备':''}</small></td>
    <td><div className="op-row-actions"><button className="op-join" disabled={!canWrite} onClick={()=>open('join',[o])}>加入周计划<ArrowUpRight size={13}/></button><button className="op-icon" aria-label={'编辑 '+o.specification} disabled={!canWrite} onClick={()=>open('edit',[o])}><Pencil size={15}/></button><details><summary aria-label={'更多操作 '+o.specification}><MoreHorizontal size={16}/></summary><div><button disabled={!canWrite} onClick={()=>open('priority',[o])}>设置优先级</button><button disabled={!canWrite} onClick={()=>open('move',[o])}>调整准备顺序</button><a href={goDrawings(o)}>打开图纸资料</a><button disabled={!canWrite} onClick={()=>open('cancel',[o])}>取消订单</button></div></details></div>{o.preparationState==='clarify'&&<span className="op-needs-plan" title={o.note}>待计划确认</span>}</td>
   </tr>)}</tbody></table>{!data?.orders.length&&<div className="op-empty"><Layers3 size={38}/><h3>{loading?'正在加载订单池…':error?'订单池暂未加载':'当前筛选没有待排订单'}</h3>{!loading&&!error&&<button onClick={()=>{setFilter('all');setCustomer('');setSearch('');setImportIds([]);}}>清除筛选</button>}</div>}
  </div><footer className="op-footer"><span>已选 <b>{selection.length}</b> 项</span>{selection.length>0&&<><button disabled={!canWrite} onClick={()=>open('priority',selection)}>批量优先级</button><button disabled={!canWrite} className="op-primary" onClick={()=>open('join',selection)}>加入周计划</button><button onClick={()=>setSelection([])}>取消选择</button></>}<span className="op-grow"/><small>当前 {data?.total??0} / 全部 {data?.allTotal??0} 项</small><button aria-label="订单池上一页" disabled={page<=1} onClick={()=>{setPage(n=>n-1);sessionStorage.removeItem('order-pool-scroll:'+user.id);}}><ChevronLeft size={16}/></button><b>{page} / {data?.pages||1}</b><button aria-label="订单池下一页" disabled={page>=(data?.pages||1)} onClick={()=>{setPage(n=>n+1);sessionStorage.removeItem('order-pool-scroll:'+user.id);}}><ChevronRight size={16}/></button></footer></div>
  {materialId&&<MaterialOrderDrawer user={user} orderId={materialId} onClose={()=>{setMaterialId('');reload();}}/>}
  {modal&&<div className="op-overlay"><section ref={dialog} className={'op-dialog '+(modal.kind==='import'?'wide':'')} role="dialog" aria-modal="true" aria-labelledby="op-title"><header><span className="op-modal-icon">{modal.kind==='import'?<Upload size={22}/>:modal.kind==='join'?<PackageCheck size={22}/>:<Layers3 size={22}/>}</span><div><h2 id="op-title">{title}</h2>{modal.rows.length>0&&<small>{modal.rows.length===1?modal.rows[0].specification:`已选 ${modal.rows.length} 项订单`}</small>}</div><button aria-label="关闭弹窗" disabled={saving} onClick={()=>setModal(null)}><X size={20}/></button></header><form onSubmit={submit}><div className="op-modal-body">
   {error&&<div className="op-error" role="alert">{error}</div>}
   {modal.kind==='import'?<><div className="op-import-tools"><input ref={file} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/><button type="button" disabled={saving} onClick={()=>file.current?.click()}><Upload size={17}/>{fileName||'选择 Excel / CSV'}</button><a href="/api/order-pool/import">下载订单池模板</a></div><div className="op-import-summary">新增 <b>{importRows.filter(r=>r.action==='create').length}</b>　更新 <b>{importRows.filter(r=>r.action==='update').length}</b>　重复 <b>{importRows.filter(r=>r.action==='skip').length}</b>　错误 <b>{importRows.filter(r=>r.action==='error').length}</b></div><div className="op-import-preview"><table><thead><tr><th>行</th><th>客户 / 规格</th><th>数量</th><th>结果</th></tr></thead><tbody>{importRows.map(r=><tr key={r.line}><td>{r.line}</td><td>{String(r.input.customerName||'')}<strong>{String(r.input.specification||'')}</strong></td><td>{String(r.input.orderQuantity||'')}</td><td className={r.error?'op-red':''}>{r.error||({create:'新增',update:'待确认更新',skip:'重复，跳过'} as Record<string,string>)[r.action]}</td></tr>)}</tbody></table></div><label className="op-check"><input type="checkbox" checked={updateExisting} onChange={e=>setUpdateExisting(e.target.checked)}/>更新已存在的订单行（保留准备记录）</label></>:
   modal.kind==='join'?<><div className="op-form-grid"><label>目标周<select aria-label="目标周" value={form.week} onChange={e=>setForm(f=>({...f,week:e.target.value,completion:add(e.target.value,6)}))}>{Array.from({length:12},(_,i)=>{const w=add(data?.currentWeek||form.week,i*7);return<option key={w} value={w}>{i===0?'本周':i===1?'下周':i===2?'下下周':'计划周'} {w} — {add(w,6)}</option>;})}</select></label><label>内部计划完成日期<input type="date" required min={form.week} max={add(form.week,6)} {...field('completion')}/></label></div><div className="op-join-list">{modal.rows.map(o=><article key={o.id}><div><strong>{o.specification}</strong><small>{o.customerName} · 待排 {o.remaining} · 可配套 {o.readyRemaining}</small><span className={'op-status '+(o.documentsReady?'green':'amber')}>{o.documentsReady?'资料已审核':'资料待准备'}</span></div>{joined.includes(o.id)?<span className="op-status green"><Check/>已加入</span>:<label>本次排产<input aria-label={'排产数量 '+o.specification} required type="number" min="1" max={o.remaining} step="1" {...field('qty:'+o.id)}/></label>}</article>)}</div>{modal.rows.length===1&&<label>单套计划工时（分钟）<input type="number" min="0.000017" max="1440" step="any" placeholder="留空显示工时待维护" {...field('unitMinutes')}/></label>}<div className="op-join-total"><span>本次计划工时</span><strong>{modal.rows.some(o=>!o.unitMilliseconds&&!(modal.rows.length===1&&form.unitMinutes))?'待补工时':(modal.rows.reduce((n,o)=>n+Number(form['qty:'+o.id]||0)*(modal.rows.length===1&&form.unitMinutes?Number(form.unitMinutes)*60000:o.unitMilliseconds||0),0)/3600000).toLocaleString(undefined,{maximumFractionDigits:3})+' h'}</strong></div><p className="op-inline-note">齐料状态随本次数量分配；未齐料仍由计划决定排周，生产放行沿用现有规则。</p></>:
   modal.kind==='priority'?<div className="op-priority-options">{Object.entries(poolPriority).map(([k,v])=><label key={k} className={k+(form.priority===k?' selected':'')}><input type="radio" name="priority" value={k} checked={form.priority===k} onChange={()=>setForm(f=>({...f,priority:k}))}/>{v.label}</label>)}</div>:
   modal.kind==='move'?<><label>移到同优先级的第几项<input type="number" required min="1" {...field('position')}/></label><p className="op-inline-note">统一调整仓库、技术的准备顺序。筛选后仍使用全局顺序。</p></>:
   modal.kind==='cancel'?<label>取消原因<textarea required maxLength={500} {...field('note')}/></label>:
   <div className="op-form-grid">{modal.kind==='create'&&<><label>客户<input required maxLength={120} {...field('customerName')}/></label><label>产品规格 / 品番<input required maxLength={180} {...field('specification')}/></label><label className="op-span">产品名称<input maxLength={160} placeholder="可沿用规格名称" {...field('productName')}/></label><label>订单号<input maxLength={120} placeholder="留空自动生成" {...field('sourceOrderNo')}/></label><label>订单行号<input required type="number" min="1" {...field('sourceLineNo')}/></label><label>下单日期<input required type="date" {...field('orderDate')}/></label><label>客户交期<input type="date" {...field('customerDueDate')}/></label><label>单套工时（分钟）<input type="number" min="0.000017" max="1440" step="any" {...field('unitMinutes')}/></label></>}{modal.kind==='edit'&&<><label>客户交期<input type="date" disabled={modal.rows[0].allocated>0} {...field('customerDueDate')}/></label><label>单套工时（分钟）<input type="number" disabled={modal.rows[0].allocated>0} min="0.000017" max="1440" step="any" {...field('unitMinutes')}/></label></>}<label>订单数量<input type="number" min="1" step="1" required {...field('orderQuantity')}/></label><label>累计准备目标（套）<input type="number" min="0" step="1" required={modal.kind==='edit'} placeholder="默认全部订单数量" {...field('preparationQuantity')}/></label><label>准备完成日期<input type="date" {...field('preparationDueAt')}/></label>{modal.kind==='edit'&&<label>计划确认<select {...field('preparationState')}><option value="open">正常准备</option><option value="clarify">待计划确认</option></select></label>}<label className="op-span">准备备注<textarea maxLength={500} {...field('note')}/></label></div>}
   </div><footer><button type="button" disabled={saving} onClick={()=>setModal(null)}>关闭</button>{modal.kind==='join'&&joined.length===modal.rows.length?<button className="op-primary" type="button" onClick={()=>{setModal(null);onWeek(form.week);}}>查看对应周计划<ArrowUpRight size={16}/></button>:<button className="op-primary" type="submit" disabled={saving||modal.kind==='import'&&!importRows.some(r=>r.action!=='error')}>{saving?'处理中…':modal.kind==='join'?'确认加入':modal.kind==='import'?'导入有效行':'保存'}</button>}</footer></form></section></div>}
 </section>;
}
