ALTER TYPE "access_profile_key" ADD VALUE IF NOT EXISTS 'PLANNING_COLLABORATOR';
ALTER TYPE "access_profile_key" ADD VALUE IF NOT EXISTS 'PRODUCTION_COLLABORATOR';
ALTER TYPE "access_profile_key" ADD VALUE IF NOT EXISTS 'MATERIAL_FOLLOW_UP_OPERATOR';
