'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, ClipboardCheck, Copy, History, Layers3, Package, PackageCheck, Plus, RefreshCw, Search, Send, Truck, Warehouse, X } from 'lucide-react';
import { AppWorkbenchHeader } from '@/components/layout/AppWorkbenchHeader';
import { useModalLayer } from '@/components/useModalLayer';
import { materialOrderStates } from '@/lib/material-order-domain';
import type { MaterialOrderDTO } from '@/lib/material-order-service';
import type { CurrentUserDTO } from '@/types';
import './MaterialOrderWorkbench.css';

type Mode = 'warehouse' | 'tracking' | 'planning';
type Event = MaterialOrderDTO['events'][number];
type Batch = Event['arrivals'][number];
type Queue = { orders: MaterialOrderDTO[]; summary: { [key: string]: number }; older: number; weeks: string[]; currentWeek: string; week: string; pagination: { page: number; total: number; pages: number } };
type Edit = { action: string; event?: Event; batch?: Batch; version: number; key: string };
type Form = { [key: string]: string };
const sourceText: { [key: string]: string } = { PURCHASED: '采购', CUSTOMER: '客供', UNKNOWN: '待确认' };
const actionText: { [key: string]: string } = { confirm_prepared: '确认可配套数量', confirm_arrival: '确认到料', report_exception: '登记缺料', update_exception: '修改缺料', eta: '更新到料交期', record_shipment: '登记发货', report_arrival: '登记到料', verify_arrival: '核验本批', complete: '确认整单配齐', reopen: '重新核对', resolve: '确认本项解决', cancel_shipment: '取消发货' };
const fmt = (v?: string | null, clock = false) => v ? (/^\d{2}[-/]\d{2}$/.test(v) ? v.replace('-', '/') : Number.isNaN(new Date(v).getTime()) ? v : new Date(v).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', month: '2-digit', day: '2-digit', ...(clock ? { hour: '2-digit', minute: '2-digit', hour12: false } : {}) })) : '待确认';
const day = (v?: string | null) => v ? new Date(v).toLocaleDateString('en-CA', { timeZone: 'Asia/Shanghai' }) : '';
const key = () => crypto.randomUUID();
const past = (v?: string | null) => !!v && /^\d{4}-\d{2}-\d{2}/.test(v) && day(v) < day(new Date().toISOString());
const weekPlus = (v: string, n: number) => { const d = new Date(v + 'T12:00:00+08:00'); d.setUTCDate(d.getUTCDate() + n); return day(d.toISOString()); };
const safeReturn = (v: string | null) => v && /^\/(?:workspace(?:\/|\?)|weekly-plan-center(?:\?|$)|home(?:\?|$))/.test(v) ? v : '';
async function json(url: string, options?: RequestInit) { const r = await fetch(url, { cache: 'no-store', ...options }); const b = await r.json(); if (!r.ok || !b.ok) throw Object.assign(Error(b.error || '加载失败，请重试'), { status: r.status }); return b; }
function phase(e: Event) { if (e.status === 'RESOLVED') return '已解决'; if (e.status === 'CANCELLED') return '已取消'; if (e.pending) return e.remaining === 0 ? '待仓库确认' : '部分到料'; if (e.transit) return '运输中'; return e.expectedAt ? '等待到料' : '交期待确认'; }

export default function MaterialOrderWorkbench({ user, mode = 'warehouse', workOrderId, orderId, onClose, onChanged, onEditorChange }: { user: CurrentUserDTO; mode?: Mode; workOrderId?: string; orderId?: string; onClose?: () => void; onChanged?: () => void; onEditorChange?: (open: boolean) => void }) {
  const embedded = !!(workOrderId || orderId), tracking = mode === 'tracking';
  const [ready, setReady] = useState(false), [scope, setScope] = useState('current'), [week, setWeek] = useState('');
  const [status, setStatus] = useState('active'), [source, setSource] = useState('ALL'), [search, setSearch] = useState(''), [query, setQuery] = useState(''), [page, setPage] = useState(1);
  const [selected, setSelected] = useState(orderId || ''), [data, setData] = useState<Queue | null>(null), [order, setOrder] = useState<MaterialOrderDTO | null>(null);
  const [refresh, setRefresh] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState(''), [returnTo, setReturnTo] = useState('');
  const [listPending, setListPending] = useState(true);
  const [chosen, setChosen] = useState(''), [allEvents, setAllEvents] = useState(false), [allHistory, setAllHistory] = useState(false);
  const [note, setNote] = useState(''), [noteFor, setNoteFor] = useState(''), [saving, setSaving] = useState(false), [edit, setEdit] = useState<Edit | null>(null), [form, setForm] = useState<Form>({});
  const panel = useRef<HTMLElement>(null), modal = useRef<HTMLElement>(null), main = useRef<HTMLElement>(null), queueScroll = useRef<HTMLDivElement>(null);
  const noteRequest = useRef(key()), listLoaded = useRef(false);
  const canConfirm = mode === 'warehouse' && user.access.modulePermissions?.materials !== 'READ' && user.access.capabilities.includes('WAREHOUSE:UPDATE');
  const canWrite = mode !== 'planning' && !order?.cancelled && user.access.modulePermissions?.materials !== 'READ' && (canConfirm || tracking && user.access.capabilities.includes('PROCUREMENT:UPDATE'));
  useModalLayer({ open: !!edit, layerRef: modal, onClose: () => { if (!saving) setEdit(null); } });
  useEffect(() => { onEditorChange?.(!!edit); return () => onEditorChange?.(false); }, [edit, onEditorChange]);
  useEffect(() => {
    if (embedded) { if (workOrderId) json('/api/warehouse/material-orders?workOrderId=' + encodeURIComponent(workOrderId)).then(b => { if (b.order) { setOrder(b.order); setSelected(b.order.id); } else { setError('该订单尚未建立配料任务'); setLoading(false); } }).catch(e => { setError(e.message); setLoading(false); }); setReady(true); return; }
    const p = new URLSearchParams(location.search), saved = p.get('scope');
    setScope(saved === 'preparation' ? 'next' : saved === 'open' ? 'overdue' : ['current','next','history','overdue','pool'].includes(saved || '') ? saved! : 'current');
    setWeek(p.get('week') || p.get('weekStart') || ''); setStatus(p.get('status') === 'pending' ? 'unchecked' : p.get('status') || 'active');
    setSource(p.get('source') || 'ALL'); setSearch(p.get('q') || ''); setQuery(p.get('q') || ''); setPage(Number(p.get('page')) || 1); setReturnTo(safeReturn(p.get('returnTo')));
    if (p.get('orderId')) setSelected(p.get('orderId')!);
    else if (p.get('taskId') && !tracking) setSelected(p.get('taskId')!);
    else if (p.get('taskId')) json('/api/warehouse/material-orders?followUpId=' + encodeURIComponent(p.get('taskId')!)).then(b => { if (b.order) setSelected(b.order.id); }).catch(e => setError(e.message));
    setReady(true);
  }, [embedded, workOrderId, tracking]);
  useEffect(() => { if (!ready) return; const t = setTimeout(() => { if (query !== search.trim()) { setQuery(search.trim()); setPage(1); setSelected(''); } }, 220); return () => clearTimeout(t); }, [search, query, ready]);
  useEffect(() => {
    if (!ready || embedded) return;
    const abort = new AbortController(); setListPending(true);
    const p = new URLSearchParams({ scope, status, source, q: query, page: String(page), view: tracking ? 'tracking' : 'warehouse' }); if (week) p.set('week', week);
    json('/api/warehouse/material-orders?' + p, { signal: abort.signal }).then(b => { if (abort.signal.aborted) return; setData(b); setPage(b.pagination.page); setSelected(id => id || b.orders[0]?.id || ''); listLoaded.current = true; }).catch(e => { if (e.name !== 'AbortError') setError(e.message); }).finally(() => { if (!abort.signal.aborted) { setListPending(false); setLoading(false); } });
    return () => abort.abort();
  }, [ready, embedded, scope, week, status, source, query, page, tracking, refresh]);
  useEffect(() => {
    if (!selected) { setOrder(null); return; }
    const abort = new AbortController();
    json('/api/warehouse/material-orders/' + selected, { signal: abort.signal }).then(b => { if (!abort.signal.aborted) { setOrder(b.order); setLoading(false); } }).catch(e => { if (e.name !== 'AbortError') { setError(e.message); setLoading(false); } });
    return () => abort.abort();
  }, [selected, refresh]);
  useEffect(() => { setChosen(''); setAllEvents(false); setNoteFor(''); setAllHistory(false); setNote(sessionStorage.getItem(`material-note:${user.id}:${selected}`) || ''); setNoteFor(sessionStorage.getItem(`material-note-for:${user.id}:${selected}`) || ''); noteRequest.current = key(); }, [selected, user.id]);
  useEffect(() => { if (order?.id === selected && panel.current) panel.current.scrollTop = Number(sessionStorage.getItem(`material-detail:${user.id}:${location.pathname}:${selected}`) || 0); }, [selected, order?.id, user.id]);
  useEffect(() => { if (!data || !queueScroll.current) return; queueScroll.current.scrollTop = Number(sessionStorage.getItem(`material-queue:${location.pathname}:${scope}:${week}:${status}:${source}:${query}:${page}`) || 0); }, [data, scope, week, status, source, query, page]);
  const href = useCallback((target: 'warehouse' | 'procurement', returning = false) => {
    const p = new URLSearchParams({ scope, status: 'all', source: 'ALL' }); if (week) p.set('week', week); if (selected) p.set('orderId', selected);
    if (returning && typeof location !== 'undefined') p.set('returnTo', location.pathname + location.search);
    return '/workspace/' + target + '?' + p;
  }, [scope, week, selected]);
  useEffect(() => {
    if (!ready || embedded) return;
    const p = new URLSearchParams({ scope, status, source, page: String(page) }); if (week) p.set('week', week); if (query) p.set('q', query); if (selected) p.set('orderId', selected); if (returnTo) p.set('returnTo', returnTo);
    window.history.replaceState(window.history.state, '', location.pathname + '?' + p);
  }, [ready, embedded, scope, status, source, page, week, query, selected, returnTo]);
  useEffect(() => { const update = () => { if (!document.hidden && !saving && !edit) setRefresh(n => n + 1); }; window.addEventListener('focus', update); window.addEventListener('material-orders-changed', update); const timer = setInterval(update, 30000); return () => { window.removeEventListener('focus', update); window.removeEventListener('material-orders-changed', update); clearInterval(timer); }; }, [saving, edit]);
  useEffect(() => { if (!notice) return; const t = setTimeout(() => setNotice(''), 3500); return () => clearTimeout(t); }, [notice]);
  function filter(type: 'scope' | 'status' | 'source', value: string, valueWeek = '') { if (saving) return; if (type === 'scope') { setScope(value); setWeek(valueWeek); } else if (type === 'status') setStatus(value); else setSource(value); setSelected(''); setPage(1); }
  function open(action: string, event?: Event, batch?: Batch) {
    if (!order) return;
    setError(''); setChosen(event?.id || '');
    setEdit({ action, event, batch, version: order.version, key: key() });
    setForm({ preparedQuantity: String(order.preparedQuantity || 0), note: '', supplySource: event?.source === 'UNKNOWN' ? '' : event?.source || 'PURCHASED', materialModel: event?.model || '', shortageQuantity: event?.required == null ? '' : String(event.required), unit: event?.unit || '个', exceptionNote: event?.note || '', expectedAt: day(event?.expectedAt), quantity: batch ? String(batch.quantity) : event?.unallocated ? String(event.unallocated) : '', logisticsMode: 'EXPRESS', carrier: '', trackingNumber: '', acceptedQuantity: batch ? String(batch.quantity) : '' });
  }
  async function mutate(body: { [key: string]: unknown }, successful?: () => void) {
    if (!order || saving) return; setSaving(true); setError('');
    try { const b = await json('/api/warehouse/material-orders/' + order.id, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...body, workspace: mode }) }); setOrder(b.order); setRefresh(n => n + 1); setNotice('已保存 · 仓库与计划已同步'); successful?.(); onChanged?.(); window.dispatchEvent(new Event('material-orders-changed')); }
    catch (e) { const err = e as Error & { status?: number }; setError(err.message); if (err.status === 409) { const b = await json('/api/warehouse/material-orders/' + order.id).catch(() => null); if (b) { setOrder(b.order); setEdit(v => v ? { ...v, version: b.order.version, key: key() } : v); } } }
    finally { setSaving(false); }
  }
  const currentEvent = order?.events.find(e => e.id === chosen) || order?.events.find(e => e.status === 'OPEN') || order?.events[0];
  const shownEvents = order?.events.filter(e => allEvents || order.cancelled || e.status === 'OPEN') || [];
  const title = tracking ? '物料追踪' : '仓库配料';
  const detail = order && order.id === selected ? <>
    <header className="mo-order-head"><div><h2>{order.specification}</h2>{order.scheduleState === 'DEFERRED' && <span className="planning-week-tag">暂退待排{order.state === 'READY' ? ' · 待计划加入' : ''}</span>}<p title={order.code}>{order.customer} · {order.planOrderId ? '订单池准备' : order.sampleTaskId ? '样品订单' : `计划周 ${fmt(order.weekStart)}`} · 计划 <b>{order.quantity}</b> 件{order.batchNo ? ` · 第 ${order.batchNo} 批` : ''} <span className="mo-order-ref">{order.code}</span></p></div><div className="mo-due"><small>产品交期</small><strong className={order.state !== "READY" && past(order.dueDate) ? "mo-red" : ""}>{fmt(order.dueDate)}</strong></div>{embedded && <button className="mo-icon" aria-label="关闭订单缺料" onClick={onClose}><X size={20}/></button>}</header>
    <div className="mo-order-strip"><span className={'mo-state ' + order.state}>{order.cancelled ? '订单已取消' : materialOrderStates[order.state]}</span><span>采购 <b>{order.purchased}</b> 项</span><span>客供 <b>{order.customerProvided}</b> 项</span>{order.unknownSource > 0 && <span>来源待确认 <b>{order.unknownSource}</b></span>}{order.pendingBatches > 0 && <span className="mo-blue">待确认 <b>{order.pendingBatches}</b> 批</span>}<div className="mo-spacer"/>{canWrite && <button className="mo-outline" onClick={() => open('report_exception')}><Plus size={15}/>{order.state === 'READY' ? '重新登记缺料' : '登记缺料'}</button>}</div>
    <section ref={panel} className="mo-detail-scroll" onScroll={e => sessionStorage.setItem(`material-detail:${user.id}:${location.pathname}:${selected}`, String(e.currentTarget.scrollTop))}>
      {order.poolQuantities && <div className="mo-pool-coverage"><span>累计准备目标 <b>{order.poolQuantities.targetTotal}</b> 套</span><span>已配套 <b>{order.preparedQuantity}</b> 套</span><span>已分配周计划 <b>{order.poolQuantities.consumed}</b> 套</span><span>待排可用 <b>{order.poolQuantities.readyRemaining}</b> 套</span>{order.preparationDueAt&&<span>准备交期 <b>{fmt(order.preparationDueAt)}</b></span>}</div>}{order.planOrderId&&order.preparationNote&&<div className="mo-pool-note">{order.preparationNote}</div>}{order.preparationTaskId && <a className="mo-source-pool" href={'/workspace/warehouse?scope=pool&orderId='+order.preparationTaskId+'&returnTo='+encodeURIComponent(location.pathname+location.search)}>查看订单池准备与缺料<ArrowUpRight size={14}/></a>}
      {order.openCount > 0 && (order.forecast.latest || order.forecast.unknown > 0) && <div className="mo-risk"><CalendarDays size={16}/>{order.forecast.latest ? `最晚已知到料 ${fmt(order.forecast.latest)} · ` : ''}{order.forecast.unknown > 0 ? `${order.forecast.unknown} 项交期待确认` : "各项到料后仍需仓库核验"}</div>}
      <div className="mo-section-heading"><h3>本单缺料明细 <small>{order.openCount} 项未结</small></h3><button onClick={() => setAllEvents(v => !v)}>{allEvents ? '仅看未结' : `含历史 ${order.events.length} 项`}<ChevronDown size={14}/></button></div>
      {shownEvents.length ? <div className="mo-material-table"><div className="mo-material-header"><span>物料型号 / 来源</span><span>登记缺料</span><span>已确认</span><span>待确认</span><span>仍缺可用</span><span>预计到料 / 物流</span><span>操作</span></div>{shownEvents.map(e => <article key={e.id} className={'mo-material-line ' + (currentEvent?.id === e.id ? 'selected' : '')}>
        <button className="mo-material-name" onClick={() => setChosen(e.id)}><strong>{e.model}</strong><small>{sourceText[e.source]} · {e.unit}<em className={e.pending ? 'blue' : e.status === 'RESOLVED' ? 'green' : 'orange'}>{phase(e)}</em></small></button>
        <div className="mo-amount"><strong>{e.required ?? '待确认'}</strong><small>{embedded ? `登记 · ${e.unit}` : e.unit}</small></div>
        <div className="mo-amount"><strong className={e.usable ? 'mo-green' : ''}>{e.usable}</strong>{embedded && <small>已确认</small>}</div>
        <div className="mo-amount"><strong className={e.pending ? 'mo-blue' : ''}>{e.pending}</strong>{embedded && <small>待确认</small>}</div>
        <div className="mo-amount"><strong className={e.remaining ? 'mo-red' : ''}>{e.missing ?? '待确认'}</strong>{embedded && <small>仍缺可用</small>}{e.rejected > 0 && <small title={`异常需补货 ${e.rejected} ${e.unit}`}>异常 {e.rejected}</small>}</div>
        <div className="mo-logistics-cell"><button className={!e.expectedAt ? 'mo-orange' : e.remaining !== 0 && past(e.expectedAt) ? 'mo-red' : ''} disabled={!tracking || !canWrite || e.status !== 'OPEN'} onClick={() => open('eta', e)}>{e.expectedAt ? fmt(e.expectedAt) : tracking ? '填写交期' : '待回复'}</button><small title={e.arrivals.filter(b => b.status !== 'CANCELLED').at(-1)?.trackingNumber}>{e.arrivals.filter(b => b.status !== 'CANCELLED').at(-1)?.trackingNumber || '暂无物流'}</small></div>
        <div className="mo-line-action">{canConfirm && e.status === 'OPEN' ? <button className="mo-blue-button" onClick={() => open('confirm_arrival', e, e.arrivals.find(b => b.status === 'ARRIVED') || e.arrivals.find(b => b.status === 'SHIPPED'))}>确认到料</button> : tracking && canWrite && e.status === 'OPEN' && (e.unallocated === null || e.unallocated > 0 || e.transit > 0) ? <button onClick={() => open(e.transit ? 'report_arrival' : 'record_shipment', e, e.arrivals.find(b => b.status === 'SHIPPED'))}>{e.transit ? '反馈已到' : '登记发货'}</button> : <button onClick={() => setChosen(e.id)}>查看进展</button>}</div>
      </article>)}</div> : <div className="mo-empty"><PackageCheck size={36}/><strong>{order.state === 'READY' ? '仓库已确认配齐' : order.state === 'PARTIAL' ? `累计已配套 ${order.preparedQuantity} / ${order.poolQuantities?.targetTotal} 套` : order.state === 'CONFIRM' ? '缺料事项已解决，等待整单确认' : '尚未核对物料'}</strong>{order.state === 'READY' && <small>{order.completedBy} · {fmt(order.completedAt, true)}</small>}{order.state === 'UNCHECKED' && canConfirm && <button onClick={() => open(order.planOrderId ? 'confirm_prepared' : 'complete')}>核对齐料后确认</button>}</div>}
      <div className="mo-order-panels">
      {currentEvent && (shownEvents.length > 0) && <section className="mo-batches"><header><h3><Truck size={17}/>{tracking ? '物流进展' : '到料记录'} <small>{currentEvent.model}</small></h3>{canWrite && currentEvent.status === 'OPEN' && <button onClick={() => open('update_exception', currentEvent)}>修改缺料</button>}</header>{currentEvent.arrivals.length ? currentEvent.arrivals.map(b => <article key={b.id}>
        <div><strong>{b.quantity} {currentEvent.unit}</strong><span className={'mo-pill ' + (b.status === 'ARRIVED' ? 'blue' : b.status === 'VERIFIED' ? 'green' : '')}>{({ SHIPPED: '运输中', ARRIVED: '待确认', VERIFIED: '已确认', CANCELLED: '已取消' } as { [key: string]: string })[b.status]}</span>{b.legacy && <span className="mo-pill">历史报到</span>}<small>{b.carrier || ({ EXPRESS: '快递', SELF_DELIVERY: '自送', PICKUP: '自提', UNKNOWN: '物流待补充' } as { [key: string]: string })[b.logisticsMode]} {b.trackingNumber}{b.trackingNumber && <button className="mo-icon" aria-label="复制快递单号" onClick={() => navigator.clipboard.writeText(b.trackingNumber).then(() => setNotice('单号已复制')).catch(() => setError('复制失败，请选择单号复制'))}><Copy size={13}/></button>}</small></div>
        <div><small>{b.status === 'VERIFIED' ? `可用 ${b.acceptedQuantity} · 待补货 ${b.rejectedQuantity}` : b.status === 'ARRIVED' ? `报到 ${fmt(b.arrivedAt, true)}` : `预计 ${fmt(b.expectedAt)}`}</small>{b.note && <small className="mo-batch-note">{b.note}</small>}</div>
        {canWrite && currentEvent.status === 'OPEN' && <div className="mo-batch-actions">{tracking && b.status === 'SHIPPED' && <><button onClick={() => open('report_arrival', currentEvent, b)}>报到料</button><button className="mo-muted-button" onClick={() => open('cancel_shipment', currentEvent, b)}>取消</button></>}{canConfirm && ['ARRIVED','SHIPPED'].includes(b.status) && <button className="mo-blue-button" onClick={() => open('confirm_arrival', currentEvent, b)}>确认到料</button>}</div>}
      </article>) : <p className="mo-muted">暂无发货 / 到料批次</p>}{canWrite && currentEvent.status === 'OPEN' && <footer>{tracking && (currentEvent.unallocated === null || currentEvent.unallocated > 0) && <><button onClick={() => open('record_shipment', currentEvent)}><Plus size={14}/>登记发货</button><button onClick={() => open('report_arrival', currentEvent)}>直接登记到料</button></>}{canConfirm && !currentEvent.pending && !currentEvent.transit && <button onClick={() => open('confirm_arrival', currentEvent)}>确认到料</button>}</footer>}</section>}
      <section className="mo-timeline"><header><h3>协同记录</h3><button onClick={() => setAllHistory(v => !v)}>{allHistory ? '收起' : '展开记录'}<History size={14}/></button></header>{(allHistory ? order.activities : order.activities.slice(0, 5)).map(a => <article key={a.id}><span className="mo-timeline-dot"/><div><p>{a.content}</p><small>{a.actor} · {fmt(a.at, true)}</small></div></article>)}{!order.activities.length && <p className="mo-muted">暂无进展</p>}</section></div>
    </section>
    <footer className="mo-compose">{canWrite && order.state !== 'READY' ? <><select aria-label="进展关联物料" value={noteFor} onChange={e => { setNoteFor(e.target.value); sessionStorage.setItem(`material-note-for:${user.id}:${selected}`,e.target.value); }}><option value="">关联：本单</option>{order.events.filter(e => e.status === 'OPEN').map(e => <option key={e.id} value={e.id}>{e.model}</option>)}</select><input aria-label="本单进展" placeholder="补充本单进展…" value={note} onChange={e => { setNote(e.target.value); noteRequest.current = key(); sessionStorage.setItem(`material-note:${user.id}:${selected}`, e.target.value); }}/><button className="mo-send" aria-label="保存进展" disabled={!note.trim() || saving} onClick={() => mutate({ action: 'note', note, exceptionId: noteFor || undefined, requestKey: noteRequest.current }, () => { setNote(''); sessionStorage.removeItem(`material-note:${user.id}:${selected}`); noteRequest.current = key(); })}><Send size={18}/></button></> : <span className="mo-muted">{order.cancelled ? '已取消 · 保留到料与核验记录' : order.state === 'READY' ? `${order.completedBy} · ${fmt(order.completedAt, true)} 确认配齐` : '只读查看'}</span>}<div className="mo-spacer"/>{canConfirm&&canWrite&&order.planOrderId&&order.preparedQuantity>0&&order.state!=='READY'&&<button className="mo-outline" disabled={saving} onClick={()=>open('reopen')}>重新核对配套</button>}{canConfirm && canWrite && <button className="mo-primary" title={order.openCount ? '仍有未结缺料，请先核验并解决' : undefined} disabled={saving || !order.planOrderId && order.openCount > 0} onClick={() => open(order.state === 'READY' ? 'reopen' : order.planOrderId ? 'confirm_prepared' : 'complete')}><Check size={16}/>{order.state === 'READY' ? '重新核对' : order.planOrderId ? '确认可配套数量' : '确认整单配齐'}</button>}{embedded && <a className="mo-outline" href={href('procurement', true)}>物料追踪<ArrowUpRight size={15}/></a>}</footer>
  </> : <div className="mo-empty"><Package size={32}/><strong>{loading ? '加载订单…' : '选择一笔周订单'}</strong></div>;
  return <main ref={main} className={embedded ? 'mo-embedded' : 'mo-workbench hm-workbench-root'}>
    {!embedded && <><AppWorkbenchHeader user={user} activeHref={tracking ? '/workspace/procurement' : '/workspace/warehouse'} subtitle="物料协同" menuItems={[]} hideHeader sidebarTriggerTargetId="mo-sidebar"/><header className="mo-top"><div id="mo-sidebar"/><span className="mo-brand-icon">{tracking ? <Layers3 size={23}/> : <Warehouse size={23}/>}</span><h1>{title}</h1>{!tracking && <select aria-label="业务模式" value="mass" onChange={e => { if (e.target.value === 'sample') location.href = '/workspace/warehouse?branch=samples'; }}><option value="mass">量产</option><option value="sample">样品</option></select>}<div className="mo-weeks"><select aria-label="历史周" value={scope === 'history' ? week || data?.week || '' : ''} onChange={e => filter('scope', 'history', e.target.value)}><option value="" disabled>历史周</option>{data?.weeks.map(w => <option key={w} value={w}>{w} 周</option>)}</select><button className={scope === 'current' ? 'active' : ''} onClick={() => filter('scope', 'current')}>本周 <span>{data ? `${fmt(data.currentWeek)}—${fmt(weekPlus(data.currentWeek, 6))}` : ''}</span></button><button className={scope === 'next' ? 'active' : ''} onClick={() => filter('scope', 'next')}>下周 <span>{data ? `${fmt(weekPlus(data.currentWeek, 7))}—${fmt(weekPlus(data.currentWeek, 13))}` : ''}</span></button><button className={scope === 'pool' ? 'active' : ''} onClick={() => filter('scope', 'pool')}>订单池{tracking ? '追踪' : '配料'}</button></div><div className="mo-spacer"/><button className={scope === 'overdue' ? 'active' : ''} onClick={() => filter('scope', 'overdue')}>历史未结 <b>{data?.older ?? '—'}</b></button><a className="mo-outline" href={returnTo || href(tracking ? 'warehouse' : 'procurement', true)}>{returnTo ? '返回来源' : tracking ? '仓库配料' : '物料追踪'}<ArrowUpRight size={16}/></a><button className="mo-icon" aria-label="刷新" onClick={() => setRefresh(n => n + 1)}><RefreshCw size={18}/></button></header>
      <div className="mo-toolbar"><div className="mo-filter-tabs">{(tracking ? [['active','未结订单'],['waiting','待确认'],['ready','已配齐'],['all','全部']] : [['active','未配齐'],['waiting','待确认'],['unchecked','待核对'],['ready','已配齐'],['all','全部']]).map(([s,l]) => <button key={s} className={status === s ? 'active' : ''} onClick={() => filter('status',s)}>{l} <b>{data?.summary[s] ?? '—'}</b></button>)}</div><label className="mo-search"><Search size={17}/><input aria-label="搜索产品规格、客户、物料或快递单号" placeholder="搜索产品规格、客户、物料或快递单号" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="物料来源" value={source} onChange={e => filter('source',e.target.value)}><option value="ALL">全部来源</option>{Object.entries(sourceText).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><select aria-label="更多筛选" value={['unknown','late','cancelled'].includes(status) ? status : ''} onChange={e => filter('status',e.target.value || 'active')}><option value="">更多筛选</option><option value="unknown">交期待确认</option><option value="late">到料逾期</option><option value="cancelled">已取消订单</option></select></div></>}
    {error && <div role="alert" className="mo-error">{error}<button aria-label="关闭提示" onClick={() => setError('')}><X size={15}/></button></div>}{notice && <div role="status" className="mo-toast"><Check size={15}/>{notice}</div>}
    <div className="mo-layout">{!embedded && <aside className="mo-queue"><header><h3>{scope === 'pool' ? '订单池准备' : scope === 'overdue' ? '历史未结' : scope === 'history' ? `${fmt(data?.week)} 周订单` : scope === 'next' ? '下周订单' : '本周订单'} <small>{data?.pagination.total ?? '—'} 单</small></h3><span className="mo-muted">{scope === 'pool' ? '按计划准备顺序' : '产品交期排序'}</span></header><div className="mo-queue-label"><span>产品规格 / 客户</span><span>产品交期</span><span>配料概况</span></div><div ref={queueScroll} className="mo-queue-scroll" onScroll={e => sessionStorage.setItem(`material-queue:${location.pathname}:${scope}:${week}:${status}:${source}:${query}:${page}`, String(e.currentTarget.scrollTop))}>{data?.orders.map(o => <button key={o.id} className={'mo-order-row ' + (o.id === selected ? 'active' : '')} disabled={saving} onClick={() => setSelected(o.id)}><div><strong>{scope === 'pool' && <em className={'mo-prep-priority ' + o.preparationPriority}>{o.preparationRank} · {({insert:'特急',urgent:'优先',normal:'常规'} as Record<string,string>)[o.preparationPriority || 'normal']}</em>}{o.specification}</strong><small>{o.customer} · {o.quantity} 件</small><small className="mo-order-code" title={o.code}>{o.code}</small></div><b className={o.state !== "READY" && past(o.dueDate) ? "mo-red" : ""}>{fmt(o.dueDate)}</b><div><span className={o.openCount ? 'mo-red' : o.state === 'READY' ? 'mo-green' : ''}>{o.openCount ? `缺料 ${o.openCount} 项` : materialOrderStates[o.state]}</span>{o.pendingBatches > 0 && <small className="mo-blue">{o.pendingBatches} 批待确认</small>}{o.forecast.unknown > 0 && <small className="mo-orange">{o.forecast.unknown} 项交期待确认</small>}<small>{o.events.find(e => e.status === 'OPEN')?.progress || (o.poolQuantities && o.preparedQuantity > 0 ? `已配套 ${o.preparedQuantity} / ${o.poolQuantities.targetTotal} 套` : o.state === 'READY' ? '仓库已确认' : '尚未确认齐料')}</small></div></button>)}{listPending && !listLoaded.current && <div className="mo-empty">加载中…</div>}{!listPending && !data?.orders.length && <div className="mo-empty"><PackageCheck size={28}/>当前筛选没有订单<button onClick={() => { filter('status','all'); setSearch(''); setSource('ALL'); }}>查看本周全部</button></div>}</div><footer><span>共 {data?.pagination.total ?? 0} 单</span><button aria-label="上一页" disabled={page <= 1} onClick={() => { setPage(n => n - 1); setSelected(''); }}><ChevronLeft size={17}/></button><b>{page} / {data?.pagination.pages || 1}</b><button aria-label="下一页" disabled={page >= (data?.pagination.pages || 1)} onClick={() => { setPage(n => n + 1); setSelected(''); }}><ChevronRight size={17}/></button></footer></aside>}<section className="mo-detail">{detail}</section></div>
    {edit && <div className="mo-overlay"><section ref={modal} className="mo-dialog" role="dialog" aria-modal="true" aria-labelledby="mo-dialog-title"><header><span className="mo-brand-icon"><ClipboardCheck size={23}/></span><div><h2 id="mo-dialog-title">{actionText[edit.action]}</h2><small>{edit.event?.model || order?.specification}</small></div><button className="mo-icon" aria-label="关闭" disabled={saving} onClick={() => setEdit(null)}><X size={20}/></button></header><form onSubmit={e => { e.preventDefault(); if (!order) return; void mutate({ action: edit.action, version: edit.version, requestKey: edit.key, exceptionId: edit.event?.id, arrivalId: edit.batch?.id, ...(edit.action === 'confirm_prepared' ? { preparedQuantity: Number(form.preparedQuantity), note: form.note } : edit.action === 'complete' || edit.action === 'reopen' || edit.action === 'resolve' || edit.action === 'cancel_shipment' ? { note: form.note || '仓库核对齐料' } : edit.action === 'report_exception' || edit.action === 'update_exception' ? { exceptionType: 'shortage', supplySource: form.supplySource, materialModel: form.materialModel, shortageQuantity: form.shortageQuantity, unit: form.unit, exceptionNote: form.exceptionNote || form.materialModel } : edit.action === 'eta' ? { expectedAt: form.expectedAt, supplySource: form.supplySource, note: form.note } : edit.action === 'confirm_arrival' ? { quantity: form.quantity, acceptedQuantity: form.hasIssue === 'yes' ? form.acceptedQuantity : form.quantity, itemComplete: form.itemComplete === 'yes', confirmComplete: form.confirmComplete === 'yes', note: form.note } : edit.action === 'verify_arrival' ? { acceptedQuantity: form.acceptedQuantity, note: form.note } : { quantity: form.quantity, logisticsMode: form.logisticsMode, carrier: form.carrier, trackingNumber: form.trackingNumber, expectedAt: form.expectedAt, note: form.note }) }, () => setEdit(null)); }}><div className="mo-dialog-body">
      {error && <p className="mo-error" role="alert">{error}</p>}
      {['report_exception','update_exception','eta'].includes(edit.action) && <label>物料来源<select required value={form.supplySource} onChange={e => setForm(f => ({ ...f, supplySource: e.target.value }))}><option value="" disabled>请选择物料来源</option><option value="PURCHASED">采购物料</option><option value="CUSTOMER">客供物料</option></select></label>}
      {['report_exception','update_exception'].includes(edit.action) && <><label className="mo-wide">缺料型号<input required maxLength={160} value={form.materialModel} onChange={e => setForm(f => ({ ...f, materialModel: e.target.value }))}/></label><label>登记缺料数量<input type="number" min="0.001" step="0.001" placeholder="数量待确认" value={form.shortageQuantity} onChange={e => setForm(f => ({ ...f, shortageQuantity: e.target.value }))}/></label><label>单位<input required maxLength={12} value={form.unit} onChange={e => setForm(f => ({ ...f, unit: e.target.value }))}/></label><label className="mo-wide">缺料说明<textarea value={form.exceptionNote} onChange={e => setForm(f => ({ ...f, exceptionNote: e.target.value }))}/></label></>}
      {['record_shipment','report_arrival'].includes(edit.action) && (edit.batch ? <div className="mo-wide mo-confirm-amount">本批 <strong>{edit.batch.quantity} {edit.event?.unit}</strong><span>{edit.batch.carrier} {edit.batch.trackingNumber}</span></div> : <><label>本批数量<input required type="number" min="0.001" step="0.001" value={form.quantity} onChange={e => setForm(f => ({ ...f, quantity: e.target.value }))}/></label><label>物流方式<select aria-label="物流方式" value={form.logisticsMode} onChange={e => setForm(f => ({ ...f, logisticsMode: e.target.value }))}><option value="EXPRESS">快递</option><option value="SELF_DELIVERY">自送</option><option value="PICKUP">自提</option><option value="UNKNOWN">待补充</option></select></label>{form.logisticsMode === 'EXPRESS' && <><label>物流公司<input value={form.carrier} onChange={e => setForm(f => ({ ...f, carrier: e.target.value }))}/></label><label>快递单号<input maxLength={100} value={form.trackingNumber} onChange={e => setForm(f => ({ ...f, trackingNumber: e.target.value }))}/></label></> }</>)}
      {['eta','record_shipment'].includes(edit.action) && <label>预计到料日期<input type="date" value={form.expectedAt} onChange={e => setForm(f => ({ ...f, expectedAt: e.target.value }))}/></label>}
      {edit.action === 'confirm_arrival' && <><div className="mo-wide mo-confirm-amount"><span>仍缺可用</span><strong>{edit.event?.missing ?? '数量待确认'} {edit.event?.unit}</strong>{edit.batch && <small>本批待确认 {edit.batch.quantity} {edit.event?.unit} {edit.batch.trackingNumber || ''}</small>}</div><label>本次到料数量<input required={form.itemComplete !== 'yes' || !!edit.batch} type="number" min="0.001" step="0.001" max={edit.batch?.quantity} placeholder="现场确认数量" value={form.quantity} onChange={e => setForm(f => ({ ...f, quantity: e.target.value, acceptedQuantity: e.target.value }))}/></label><label className="mo-check"><input type="checkbox" checked={form.hasIssue === 'yes'} onChange={e => setForm(f => ({ ...f, hasIssue: e.target.checked ? 'yes' : '', acceptedQuantity: f.quantity }))}/>有少料、错料或来料异常</label>{form.hasIssue === 'yes' && <label>可用数量<input required type="number" min="0" step="0.001" max={form.quantity} value={form.acceptedQuantity} onChange={e => setForm(f => ({ ...f, acceptedQuantity: e.target.value }))}/></label>}{edit.event?.required == null && <label className="mo-wide mo-check"><input type="checkbox" checked={form.itemComplete === 'yes'} onChange={e => setForm(f => ({ ...f, itemComplete: e.target.checked ? 'yes' : '' }))}/>现场已核对，本项缺料全部补齐</label>}{order?.openCount === 1 && !order.planOrderId && <label className="mo-wide mo-check"><input type="checkbox" checked={form.confirmComplete === 'yes'} onChange={e => setForm(f => ({ ...f, confirmComplete: e.target.checked ? 'yes' : '' }))}/>同时确认整单配齐</label>}</>}
      {edit.action === 'verify_arrival' && <><div className="mo-wide mo-confirm-amount">本批报到 <strong>{edit.batch?.quantity} {edit.event?.unit}</strong></div><label>核验可用数量<input required type="number" min="0" step="0.001" max={edit.batch?.quantity} value={form.acceptedQuantity} onChange={e => setForm(f => ({ ...f, acceptedQuantity: e.target.value }))}/></label><div className="mo-confirm-amount">需补货 <strong className="mo-red">{Math.max(0, (edit.batch?.quantity || 0) - Number(form.acceptedQuantity || 0))} {edit.event?.unit}</strong></div></>}
      {edit.action === 'confirm_prepared' && <><label className="mo-wide">累计可配套产品数量（套）<input aria-label="累计可配套数量" required type="number" min={order?.poolQuantities?.consumed || 0} max={order?.poolQuantities?.targetTotal} step="1" value={form.preparedQuantity} onChange={e => setForm(f => ({...f,preparedQuantity:e.target.value}))}/></label><div className="mo-wide mo-pool-hint">已分配 {order?.poolQuantities?.consumed || 0} 套 · 本次确认后待排可用 {Math.max(0,Number(form.preparedQuantity||0)-(order?.poolQuantities?.consumed||0))} 套</div><label className="mo-wide mo-check"><input type="checkbox" required/>已按实物核对以上产品套数</label></>}
      {edit.action === 'complete' && <label className="mo-wide mo-check"><input type="checkbox" required/>已核对该订单所需实物，确认物料齐全</label>}
      {!['report_exception','update_exception'].includes(edit.action) && <label className="mo-wide">{edit.action === 'reopen' || edit.action === 'cancel_shipment' ? '原因' : '备注'}<textarea required={edit.action === 'confirm_arrival' && form.hasIssue === 'yes' || ['reopen','cancel_shipment','resolve'].includes(edit.action) || edit.action === 'verify_arrival' && Number(form.acceptedQuantity) < (edit.batch?.quantity || 0)} maxLength={600} value={form.note} onChange={e => setForm(f => ({ ...f, note: e.target.value }))}/></label>}
    </div><footer><button type="button" disabled={saving} onClick={() => setEdit(null)}>取消</button><button className="mo-primary" disabled={saving} type="submit">{saving ? '保存中…' : actionText[edit.action]}</button></footer></form></section></div>}
  </main>;
}

